# Generated by Django 3.1.7 on 2022-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220922_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
