# Generated by Django 2.0.5 on 2020-06-01 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181203_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1500)),
                ('ab_stufe', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('illegal', models.BooleanField(default=False)),
                ('lizenz_benötigt', models.BooleanField(default=False)),
                ('frei_editierbar', models.BooleanField(default=True)),
                ('kategorie', models.CharField(choices=[('t', 'Tränke'), ('r', 'Rezepte'), ('z', 'Zutaten'), ('b', 'Zubehör')], default='t', max_length=2)),
            ],
            options={
                'verbose_name': 'Alchemie',
                'verbose_name_plural': 'Alchemie',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlchemieSonderangebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('preis', models.CharField(default='0', max_length=11)),
                ('until', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Angebotsende')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Firma')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Alchemie')),
            ],
            options={
                'verbose_name': 'Sonderangebot',
                'verbose_name_plural': 'Sonderangebote',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirmaAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.CharField(default='0', max_length=11)),
                ('verfügbarkeit', models.PositiveIntegerField(choices=[(0, '0%'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%'), (14, '14%'), (15, '15%'), (16, '16%'), (17, '17%'), (18, '18%'), (19, '19%'), (20, '20%'), (21, '21%'), (22, '22%'), (23, '23%'), (24, '24%'), (25, '25%'), (26, '26%'), (27, '27%'), (28, '28%'), (29, '29%'), (30, '30%'), (31, '31%'), (32, '32%'), (33, '33%'), (34, '34%'), (35, '35%'), (36, '36%'), (37, '37%'), (38, '38%'), (39, '39%'), (40, '40%'), (41, '41%'), (42, '42%'), (43, '43%'), (44, '44%'), (45, '45%'), (46, '46%'), (47, '47%'), (48, '48%'), (49, '49%'), (50, '50%'), (51, '51%'), (52, '52%'), (53, '53%'), (54, '54%'), (55, '55%'), (56, '56%'), (57, '57%'), (58, '58%'), (59, '59%'), (60, '60%'), (61, '61%'), (62, '62%'), (63, '63%'), (64, '64%'), (65, '65%'), (66, '66%'), (67, '67%'), (68, '68%'), (69, '69%'), (70, '70%'), (71, '71%'), (72, '72%'), (73, '73%'), (74, '74%'), (75, '75%'), (76, '76%'), (77, '77%'), (78, '78%'), (79, '79%'), (80, '80%'), (81, '81%'), (82, '82%'), (83, '83%'), (84, '84%'), (85, '85%'), (86, '86%'), (87, '87%'), (88, '88%'), (89, '89%'), (90, '90%'), (91, '91%'), (92, '92%'), (93, '93%'), (94, '94%'), (95, '95%'), (96, '96%'), (97, '97%'), (98, '98%'), (99, '99%'), (100, '100%')], default=0)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Firma')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Alchemie')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirmaStAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.CharField(default='0', max_length=11)),
                ('verfügbarkeit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Firma')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1500)),
                ('ab_stufe', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('illegal', models.BooleanField(default=False)),
                ('lizenz_benötigt', models.BooleanField(default=False)),
                ('frei_editierbar', models.BooleanField(default=True)),
                ('kategorie', models.CharField(choices=[('t', 'Tränke'), ('r', 'Rezepte'), ('z', 'Zutaten'), ('b', 'Zubehör')], default='t', max_length=2)),
                ('firmen', models.ManyToManyField(blank=True, through='shop.FirmaStAlchemie', to='shop.Firma')),
            ],
            options={
                'verbose_name': 'Alchemie (stufenabh)',
                'verbose_name_plural': 'Alchemie (stufenabh)',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StAlchemieSonderangebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('preis', models.CharField(default='0', max_length=11)),
                ('until', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Angebotsende')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Firma')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StAlchemie')),
            ],
            options={
                'verbose_name': 'Sonderangebot',
                'verbose_name_plural': 'Sonderangebote',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='firmastalchemie',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StAlchemie'),
        ),
        migrations.AddField(
            model_name='alchemie',
            name='firmen',
            field=models.ManyToManyField(blank=True, through='shop.FirmaAlchemie', to='shop.Firma'),
        ),
    ]
