# Generated by Django 2.0.5 on 2020-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200602_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe'), ('z', 'Zauber/Upgrades'), ('p', 'Produktionsstätten')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe'), ('z', 'Zauber/Upgrades'), ('p', 'Produktionsstätten')], default='m', max_length=2),
        ),
    ]
