# Generated by Django 2.0.5 on 2020-06-08 20:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200608_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='StTinkerNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'benötigt',
                'verbose_name_plural': 'benötigt',
            },
        ),
        migrations.CreateModel(
            name='TinkerNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'benötigt',
                'verbose_name_plural': 'benötigt',
            },
        ),
        migrations.RenameField(
            model_name='tinker',
            old_name='benötigt',
            new_name='benötigt_txt',
        ),
        migrations.RenameField(
            model_name='tinker',
            old_name='herstellung_via',
            new_name='herstellung_via_txt',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='benötigt',
        ),
        migrations.AlterField(
            model_name='sttinker',
            name='herstellung_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_herstellung_via', related_query_name='r_herstellung_via', to='shop.StTinker'),
        ),
        migrations.AlterField(
            model_name='sttinker',
            name='herstellungsdauer',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='herstellungsdauer (dd:hh:mm)'),
        ),
        migrations.AlterField(
            model_name='sttinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe/Werkstoffe'), ('z', 'Zauber/Upgrades'), ('p', 'Produktionsstätten')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='herstellungsdauer',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='herstellungsdauer (dd:hh:mm)'),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe/Werkstoffe'), ('z', 'Zauber/Upgrades'), ('p', 'Produktionsstätten')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='tinkerneeds',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part', related_query_name='part', to='shop.Tinker'),
        ),
        migrations.AddField(
            model_name='tinkerneeds',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='product', to='shop.Tinker'),
        ),
        migrations.AddField(
            model_name='sttinkerneeds',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part', related_query_name='part', to='shop.StTinker'),
        ),
        migrations.AddField(
            model_name='sttinkerneeds',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='product', to='shop.StTinker'),
        ),
        migrations.AddField(
            model_name='sttinker',
            name='benötigt',
            field=models.ManyToManyField(blank=True, related_name='r_benötigt', related_query_name='r_benötigt', through='shop.StTinkerNeeds', to='shop.StTinker'),
        ),
    ]
