# Generated by Django 2.0.5 on 2020-06-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200608_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinker',
            name='benötigt',
            field=models.ManyToManyField(blank=True, related_name='r_benötigt', related_query_name='r_benötigt', through='shop.TinkerNeeds', to='shop.Tinker'),
        ),
        migrations.AddField(
            model_name='tinker',
            name='herstellung_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_herstellung_via', related_query_name='r_herstellung_via', to='shop.Tinker'),
        ),
    ]
