# Generated by Django 2.0.5 on 2020-06-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200608_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinker',
            name='benötigt_txt',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='herstellung_via_txt',
        ),
    ]
