# Generated by Django 2.0.5 on 2020-06-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200609_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkerWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Nebenprodukt',
                'verbose_name_plural': 'Nebenprodukte',
            },
        ),
        migrations.AlterField(
            model_name='sttinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe/Werkstoffe'), ('z', 'Zauber/Upgrades/Verbesserungen'), ('p', 'Produktionsstätten'), ('u', 'Müll')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe/Werkstoffe'), ('z', 'Zauber/Upgrades/Verbesserungen'), ('p', 'Produktionsstätten'), ('u', 'Müll')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='tinkerwaste',
            name='neben',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neben', related_query_name='neben', to='shop.Tinker'),
        ),
        migrations.AddField(
            model_name='tinkerwaste',
            name='rezept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezept', related_query_name='rezept', to='shop.Tinker'),
        ),
        migrations.AddField(
            model_name='tinker',
            name='nebenprodukte',
            field=models.ManyToManyField(blank=True, related_name='r_nebenprodukte', related_query_name='r_nebenprodukte', through='shop.TinkerWaste', to='shop.Tinker'),
        ),
    ]
