# Generated by Django 2.0.5 on 2020-06-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200615_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='StTinkerWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neben', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neben', related_query_name='neben', to='shop.StTinker')),
                ('rezept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezept', related_query_name='rezept', to='shop.StTinker')),
            ],
            options={
                'verbose_name': 'Nebenprodukt',
                'verbose_name_plural': 'Nebenprodukte',
            },
        ),
        migrations.AddField(
            model_name='sttinker',
            name='nebenprodukte',
            field=models.ManyToManyField(blank=True, related_name='r_nebenprodukte', related_query_name='r_nebenprodukte', through='shop.StTinkerWaste', to='shop.StTinker'),
        ),
    ]
