# Generated by Django 2.0.5 on 2020-06-15 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200615_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttinkerwaste',
            name='num',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tinkerwaste',
            name='num',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
