# Generated by Django 2.0.4 on 2020-06-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200623_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttinker',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Für Selbstständige (stufenabh)', 'verbose_name_plural': 'Für Selbstständige (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='tinker',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Für Selbstständige', 'verbose_name_plural': 'Für Selbstständige'},
        ),
    ]
