# Generated by Django 2.2.13 on 2020-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200815_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='einbauten',
            name='manifestverlust_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stausrüstung_technik',
            name='manifestverlust',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='steinbauten',
            name='manifestverlust',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
