# Generated by Django 2.2.13 on 2020-08-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200815_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einbauten',
            name='manifestverlust',
        ),
    ]
