# Generated by Django 2.2.13 on 2020-08-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200815_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausrüstung_technik',
            name='manifestverlust_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
