# Generated by Django 2.2.13 on 2020-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200815_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaalchemie',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmaausrüstung_technik',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmaeinbauten',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmafahrzeug',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmaitem',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmamagazin',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmamagische_ausrüstung',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmapfeil_bolzen',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmarüstungen',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmaschusswaffen',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmatinker',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmawaffen_werkzeuge',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmazauber',
            name='verfügbarkeit_int',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
