# Generated by Django 2.2.13 on 2020-08-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200815_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmaalchemie',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmaausrüstung_technik',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmaeinbauten',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmafahrzeug',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmaitem',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmamagazin',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmamagische_ausrüstung',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmapfeil_bolzen',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmarüstungen',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmaschusswaffen',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmatinker',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmawaffen_werkzeuge',
            name='preis',
        ),
        migrations.RemoveField(
            model_name='firmazauber',
            name='preis',
        ),
    ]
