# Generated by Django 2.2.13 on 2020-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_firma_price_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='price_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
