# Generated by Django 2.2.13 on 2020-10-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20201022_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkerwaste',
            name='neben',
        ),
        migrations.RemoveField(
            model_name='tinkerwaste',
            name='rezept',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='benötigt',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='herstellung_via',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='herstellungsdauer',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='nebenprodukte',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='num_product',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='probe_spezial',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='probe_wissen',
        ),
        migrations.DeleteModel(
            name='TinkerNeeds',
        ),
        migrations.DeleteModel(
            name='TinkerWaste',
        ),
    ]
