# Generated by Django 3.1.7 on 2022-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_modifier_shopcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='price_modifier',
            field=models.FloatField(default=1.0),
        ),
    ]
