# Generated by Django 3.1.7 on 2022-08-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20220829_2303'),
    ]

    operations = [
    ]
