# Generated by Django 3.1.7 on 2022-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20220830_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinker',
            name='minecraft_mod_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
