# Generated by Django 4.1.7 on 2023-04-07 19:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_tinker_minecraft_mod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alchemie',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='ausrüstung_technik',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='begleiter',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='einbauten',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='fahrzeug',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='magische_ausrüstung',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='pfeil_bolzen',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='rituale_runen',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='rüstungen',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='schusswaffen',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='vergessenerzauber',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='waffen_werkzeuge',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
        migrations.AlterField(
            model_name='zauber',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
    ]
