# Generated by Django 4.1.7 on 2023-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_engelsroboter_firmaengelsroboter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engelsroboter',
            name='IN',
            field=models.PositiveSmallIntegerField(default=0, help_text='Intelligenz'),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='MA',
            field=models.PositiveSmallIntegerField(default=0, help_text='Magie'),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='ST',
            field=models.PositiveSmallIntegerField(default=0, help_text='Stärke'),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='UM',
            field=models.PositiveSmallIntegerField(default=0, help_text='Umgang'),
        ),
    ]
