# Generated by Django 4.1.7 on 2023-06-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_zauber_will_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zauber',
            name='will_create',
        ),
    ]
