# Generated by Django 4.1.7 on 2023-07-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_zauber_astralsch_is_direct_alter_zauber_verteidigung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zauber',
            name='astralsch_is_direct',
            field=models.BooleanField(default=False, verbose_name='direkter Astralschaden?'),
        ),
    ]
