# Generated by Django 4.2.8 on 2024-02-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_zauber_astralsch_is_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alchemie',
            name='kategorie',
            field=models.CharField(choices=[('t', 'Tränke'), ('d', 'Drogen'), ('r', 'Rezepte'), ('z', 'Zutaten'), ('b', 'Zubehör')], default='t', max_length=2),
        ),
        migrations.AlterField(
            model_name='ausrüstung_technik',
            name='kategorie',
            field=models.CharField(choices=[('c', 'Computerzubehör'), ('p', 'Programme'), ('a', 'Akkumulatoren'), ('v', 'Verschiedenes')], default='c', max_length=2),
        ),
        migrations.AlterField(
            model_name='rituale_runen',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Grundrituale'), ('u', 'Grundrunen'), ('g', "'o Grome")], default='i', max_length=2),
        ),
    ]
