# Generated by Django 4.2.8 on 2024-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_alchemie_kategorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemie',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='ausrüstung_technik',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='einbauten',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='item',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='magische_ausrüstung',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='pfeil_bolzen',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='rituale_runen',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='rüstungen',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='schusswaffen',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='tinker',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='vergessenerzauber',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='waffen_werkzeuge',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AddField(
            model_name='zauber',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
    ]
