# Generated by Django 4.2.8 on 2025-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_remove_zauber_astralsch_is_direct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinker',
            name='wooble_buy_price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tinker',
            name='wooble_sell_price',
            field=models.FloatField(default=1.0),
        ),
    ]
