# Generated by Django 4.2.27 on 2025-12-19 15:48

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0196_remove_klasse_beschreibung_remove_klasse_icon'),
        ('shop', '0066_rename_stärke_rüstungen_härte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rüstungen',
            new_name='Rüstung',
        ),
        migrations.RenameModel(
            old_name='FirmaRüstungen',
            new_name='FirmaRüstung',
        ),
    ]
