# Generated by Django 5.2.9 on 2026-02-14 15:14

from django.db import migrations, models

def copy_ruestung_vals(apps, schema_editor):
    Rüstung = apps.get_model('shop', 'Rüstung')
    Rüstung.objects.update(schutz=models.F("schutz_old"), härte=models.F("härte_old"))


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_rüstung_remove_rüstungen_firmen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rüstung',
            old_name='härte',
            new_name='härte_old',
        ),
        migrations.RenameField(
            model_name='rüstung',
            old_name='schutz',
            new_name='schutz_old',
        ),
        migrations.AddField(
            model_name='rüstung',
            name='härte',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='rüstung',
            name='schutz',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.RunPython(copy_ruestung_vals),
                migrations.RemoveField(
            model_name='rüstung',
            name='härte_old',
        ),
        migrations.RemoveField(
            model_name='rüstung',
            name='schutz_old',
        ),
    ]
