# Generated by Django 5.2.9 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_rename_härte_rüstung_härte_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rüstung',
            name='härte',
        ),
    ]
