# Generated by Django 5.2.9 on 2026-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_remove_rüstung_härte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zauber',
            name='verteidigung',
            field=models.CharField(choices=[('n', 'kein Ziel gewählt'), ('a', 'astral'), ('r', 'physisch')], default='n', max_length=1),
        ),
    ]
