# Generated by Django 5.2.9 on 2026-02-21 10:45

from django.db import migrations, models

def delete_category_vergessene_zauber(apps, schema_editor):
    ShopCategory = apps.get_model('shop', 'ShopCategory')
    
    # delete kategory ('v', 'vergessene Zauber'),
    ShopCategory.objects.filter(kategorie="v").delete()




class Migration(migrations.Migration):

    dependencies = [
        ('character', '0205_remove_relvergessenerzauber_char_and_more'),
        ('shop', '0070_alter_zauber_verteidigung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vergessenerzauber',
            name='firmen',
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('w', 'Waffen & Werkzeuge'), ('m', 'Magazine'), ('p', 'Pfeile & Bolzen'), ('s', 'Schusswaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
        migrations.DeleteModel(
            name='FirmaVergessenerZauber',
        ),
        migrations.DeleteModel(
            name='VergessenerZauber',
        ),
        migrations.AlterField(
            model_name='zauber',
            name='verteidigung',
            field=models.CharField(choices=[('n', 'kein Ziel gewählt'), ('a', 'astral'), ('r', 'physisch')], default='n', max_length=1, verbose_name='Reaktion'),
        ),
        migrations.RunPython(delete_category_vergessene_zauber),
    ]
