# Generated by Django 5.2.9 on 2026-09-17 09:44

import django.db.models.deletion
from django.db import migrations, models

def migrate_schusswaffe_kategorie(apps, schema_editor):
    apps.get_model('shop', 'schusswaffen').objects.update(kategorie='k')



class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_remove_vergessenerzauber_firmen_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_schusswaffe_kategorie),
        migrations.AlterField(
            model_name='schusswaffen',
            name='kategorie',
            field=models.CharField(choices=[('k', 'Kurzwaffe'), ('w', 'Gewehr'), ('m', 'Maschinengewehr'), ('s', 'Scharfschützengewehr'), ('g', 'Geschütz'), ('e', 'Exotische Waffe'), ('t', 'Taktikwaffe')], default='k', max_length=1),
        ),
        migrations.AddField(
            model_name='schusswaffen',
            name='fertigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.fertigkeit'),
        ),
    ]
