# Generated by Django 5.2.9 on 2026-09-19 12:52

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0206_alter_relramsch_options_and_more'),
        ('shop', '0072_alter_schusswaffen_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='bs',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='magazin',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='magazin',
            name='zs',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('w', 'Waffen & Werkzeuge'), ('m', 'Magazine'), ('p', 'Pfeile & Bolzen'), ('s', 'Fernkampfwaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
        migrations.RenameModel(
            old_name='Schusswaffen',
            new_name='Fernkampfwaffe',
        ),
        migrations.RenameModel(
            old_name='FirmaSchusswaffen',
            new_name='FirmaFernkampfwaffe',
        ),
        migrations.AlterModelOptions(
            name='fernkampfwaffe',
            options={'ordering': ['name'], 'verbose_name': 'Fernkampfwaffe', 'verbose_name_plural': 'Fernkampfwaffen'},
        ),
    ]
