# Generated by Django 5.2.9 on 2026-09-19 13:19

from django.db import migrations


def copy_pfeile_bolzen_to_magazine(apps, schema_editor):
    Magazin = apps.get_model('shop', 'Magazin')
    Pfeil_Bolzen = apps.get_model('shop', 'Pfeil_Bolzen')

    FirmaPfeil_Bolzen = apps.get_model('shop', 'FirmaPfeil_Bolzen')
    FirmaMagazin = apps.get_model('shop', 'FirmaMagazin')

    RelPfeil_Bolzen = apps.get_model('character', 'RelPfeil_Bolzen')
    RelMagazin = apps.get_model('character', 'RelMagazin')

    fields = [
        'name',
        'beschreibung',
        'icon',
        'ab_stufe',
        'illegal',
        'lizenz_benötigt',
        'frei_editierbar',
        'stufenabhängig',
        'has_implementation',
        'bs',
        'zs',
        'schadensart',
    ]

    firmen = []
    relchars = []
    for pfeil in Pfeil_Bolzen.objects.all():
        magazin = Magazin.objects.create(
            schuss = 1,
            **{field: pfeil.__dict__[field] for field in fields}
        )

        # FirmaPfeil_Bolzen -> FirmaMagazin
        for pf in FirmaPfeil_Bolzen.objects.prefetch_related("firma").filter(item=pfeil):
            firmen.append(
                FirmaMagazin(
                    item=magazin,
                    firma = pf.firma,
                    preis = pf.preis,
                    verfügbarkeit = pf.verfügbarkeit,
                )
            )

        # RelPfeil_Bolzen -> RelMagazin
        for pchar in RelPfeil_Bolzen.objects.prefetch_related("char").filter(item=pfeil):
            relchars.append(
                RelMagazin(
                    item = magazin,
                    char = pchar.char,
                    anz = pchar.anz,
                    stufe = pchar.stufe,
                    notizen = pchar.notizen,
                )
            )
    FirmaMagazin.objects.bulk_create(firmen)
    RelMagazin.objects.bulk_create(relchars)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_remove_schusswaffen_fertigkeit_and_more'),
        ('character', '0207_rename_relschusswaffen_relfernkampfwaffe_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_pfeile_bolzen_to_magazine)
    ]
