# Generated by Django 5.2.9 on 2026-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0208_remove_relpfeil_bolzen_char_and_more'),
        ('shop', '0074_auto_20260919_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfeil_bolzen',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='pfeile_bolzen',
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('w', 'Waffen & Werkzeuge'), ('m', 'Magazine'), ('s', 'Fernkampfwaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
        migrations.DeleteModel(
            name='FirmaPfeil_Bolzen',
        ),
        migrations.DeleteModel(
            name='Pfeil_Bolzen',
        ),
    ]
