# Generated by Django 5.2.9 on 2026-09-19 14:05

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0209_rename_relfirmamagazin_relfirmamunition'),
        ('shop', '0075_remove_pfeil_bolzen_firmen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('w', 'Waffen & Werkzeuge'), ('m', 'Munition'), ('s', 'Fernkampfwaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
        migrations.RenameModel(
            old_name='FirmaMagazin',
            new_name='FirmaMunition',
        ),
        migrations.RenameModel(
            old_name='Magazin',
            new_name='Munition',
        ),
        migrations.AlterModelOptions(
            name='munition',
            options={'ordering': ['name'], 'verbose_name': 'Munition', 'verbose_name_plural': 'Munition'},
        ),
        migrations.RenameField(
            model_name='fernkampfwaffe',
            old_name='magazine',
            new_name='munition',
        ),
    ]
