# Generated by Django 5.2.9 on 2026-09-19 15:54

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0209_rename_relfirmamagazin_relfirmamunition'),
        ('effect', '0032_rename_source_shopeinbauten_releffect_source_shopeinbaute_and_more'),
        ('shop', '0076_remove_magazin_firmen_remove_fernkampfwaffe_magazine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirmaEinbauten',
            new_name='FirmaEinbaute',
        ),
        migrations.RenameModel(
            old_name='Einbauten',
            new_name='Einbaute',
        ),
        migrations.RenameModel(
            old_name='FirmaRituale_Runen',
            new_name='FirmaRitual_Rune',
        ),
        migrations.RenameModel(
            old_name='Rituale_Runen',
            new_name='Ritual_Rune',
        ),
        migrations.RenameModel(
            old_name='FirmaWaffen_Werkzeuge',
            new_name='FirmaWaffe_Werkzeug',
        ),
        migrations.RenameModel(
            old_name='Waffen_Werkzeuge',
            new_name='Waffe_Werkzeug',
        ),
        migrations.AlterModelOptions(
            name='einbaute',
            options={'ordering': ['name'], 'verbose_name': 'Einbaute', 'verbose_name_plural': 'Einbauten'},
        ),
        migrations.AlterModelOptions(
            name='ritual_rune',
            options={'ordering': ['name'], 'verbose_name': 'Ritual/Rune', 'verbose_name_plural': 'Rituale/Runen'},
        ),
    ]
