# Generated by Django 5.2.9 on 2026-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_remove_rituale_runen_firmen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fernkampfwaffe',
            name='kategorie',
            field=models.CharField(choices=[('k', 'Kurzwaffe'), ('w', 'Gewehr'), ('m', 'Maschinengewehr'), ('s', 'Scharfschützengewehr'), ('g', 'Geschütz'), ('e', 'Exotische Waffe'), ('t', 'Taktikwaffe'), ('b', 'Bögen/Armbrüste')], default='k', max_length=1),
        ),
    ]
