# Generated by Django 5.2.9 on 2026-09-20 12:10

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0211_rename_relfirmawaffe_werkzeug_relfirmanahkampfwaffe'),
        ('shop', '0079_remove_alchemie_illegal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='waffe_werkzeug',
            new_name='nahkampfwaffe',
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('h', 'Nahkampfwaffen'), ('m', 'Munition'), ('s', 'Fernkampfwaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
        migrations.RenameModel(
            old_name='FirmaWaffe_Werkzeug',
            new_name='FirmaNahkampfwaffe',
        ),
        migrations.AlterModelOptions(
            name='nahkampfwaffe',
            options={'ordering': ['name'], 'verbose_name': 'Nahkampf-/Wurfwaffe', 'verbose_name_plural': 'Nahkampf-/Wurfwaffen'},
        ),
        migrations.AlterField(
            model_name='nahkampfwaffe',
            name='kategorie',
            field=models.CharField(choices=[('d', 'Dolche/Messer'), ('s', 'Schwerter'), ('a', 'Äxte'), ('h', 'Hämmer'), ('h', 'stumpfe Waffen'), ('c', 'Schwungwaffen'), ('l', 'Schlagringe'), ('w', 'weitere Waffen'), ('g', 'Granaten/Bomben'), ('e', 'sonstige Exoten')], default='d', max_length=2),
        ),
    ]
