# Generated by Django 5.2.9 on 2026-09-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0211_rename_relfirmawaffe_werkzeug_relfirmanahkampfwaffe'),
        ('shop', '0080_remove_waffe_werkzeug_firmen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nahkampfwaffe',
            name='erfolge',
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='fertigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.fertigkeit'),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='händigkeit',
            field=models.CharField(choices=[('1', '🤚'), ('.', '🤚/🤲'), ('2', '🤲')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='reichweite',
            field=models.FloatField(default=0.0, help_text='in m'),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='schaden',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='wirkbereich',
            field=models.TextField(default=''),
        ),
    ]
