# Generated by Django 5.2.9 on 2026-09-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_remove_nahkampfwaffe_erfolge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nahkampfwaffe',
            name='reichweite',
            field=models.FloatField(default=0.0, verbose_name='Reichweite in m'),
        ),
    ]
