# Generated by Django 5.2.9 on 2026-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_alter_nahkampfwaffe_reichweite'),
    ]

    operations = [
        migrations.AddField(
            model_name='munition',
            name='schaden',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='munition',
            name='wirkbereich',
            field=models.TextField(default=''),
        ),
    ]
