# Generated by Django 5.2.9 on 2026-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_munition_schaden_munition_wirkbereich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='erfolge',
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='feuerrate',
            field=models.CharField(choices=[('1', 'sehr langsam'), ('2', 'langsam'), ('3', 'normal'), ('4', 'schnell'), ('5', 'sehr schnell')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='händigkeit',
            field=models.CharField(choices=[('1', '🤚'), ('.', '🤚/🤲'), ('2', '🤲')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='reichweite',
            field=models.FloatField(default=0.0, verbose_name='Reichweite in m'),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='schaden',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='wirkbereich',
            field=models.TextField(default=''),
        ),
    ]
