# Generated by Django 5.2.9 on 2026-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_remove_fernkampfwaffe_erfolge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmaritual_rune',
            options={'ordering': ['item', 'firma'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.RenameField(
            model_name='firmaritual_rune',
            old_name='stufe_1',
            new_name='preis',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='stufe_2',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='stufe_3',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='stufe_4',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='stufe_5',
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='manaverbrauch',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='schaden',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='wirkbereich',
            field=models.TextField(default=''),
        ),
    ]
