# Generated by Django 5.2.9 on 2026-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_alter_firmaritual_rune_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rüstung',
            name='damage_speciality',
            field=models.TextField(default='', verbose_name='Besonderheiten bei Schadensarten'),
        ),
        migrations.AddField(
            model_name='rüstung',
            name='kategorie',
            field=models.CharField(choices=[('g', 'Ganzkörper'), ('m', 'Mäntel'), ('s', 'Schilde'), ('u', 'Upgrades')], default='g', max_length=2),
        ),
    ]
