# Generated by Django 5.2.9 on 2026-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_rüstung_damage_speciality_rüstung_kategorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fahrzeug',
            old_name='schnelligkeit',
            new_name='geschwindigkeit',
        ),
        migrations.RenameField(
            model_name='fahrzeug',
            old_name='rüstung',
            new_name='hp',
        ),
        migrations.AlterField(
            model_name='fahrzeug',
            name='kategorie',
            field=models.CharField(choices=[('z', 'Zweiräder'), ('w', 'PKW/LKW'), ('r', 'Raumschiffe'), ('p', 'Panzer'), ('s', 'Schiffe'), ('d', 'Drohnen')], default='z', max_length=2),
        ),
    ]
