# Generated by Django 5.2.9 on 2026-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_rename_schnelligkeit_fahrzeug_geschwindigkeit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zauber',
            name='schaden',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='zauber',
            name='wirkbereich',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='zauber',
            name='wirkdauer',
            field=models.TextField(default=''),
        ),
    ]
