# Generated by Django 5.2.9 on 2026-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_zauber_schaden_zauber_wirkbereich_zauber_wirkdauer'),
    ]

    operations = [
        migrations.AddField(
            model_name='begleiter',
            name='astrale_reaktion',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='astraler_widerstand',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='hp',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='physische_reaktion',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='physischer_widerstand',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='astrale_reaktion',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='astraler_widerstand',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='hp',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='physische_reaktion',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='physischer_widerstand',
            field=models.CharField(default='', max_length=64),
        ),
    ]
