# Generated by Django 5.2.9 on 2026-09-20 15:21

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_begleiter_astrale_reaktion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to='')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Upgrade',
                'verbose_name_plural': 'Upgrades',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='slots',
            field=models.ManyToManyField(to='shop.slot'),
        ),
        migrations.AddField(
            model_name='slot',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag'),
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('beschreibung', models.TextField(default='')),
                ('ab_stufe', models.PositiveSmallIntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('achievement_unlock', models.BooleanField(default=False, verbose_name='nur manuell von SL nach Achievement freischaltbar')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Upgrade',
                'verbose_name_plural': 'Upgrades',
                'ordering': ['tag', 'name', 'ab_stufe', 'price'],
            },
        ),
    ]
