# Generated by Django 5.2.9 on 2026-09-20 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_slot_tag_nahkampfwaffe_slots_slot_tag_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotNahkampfwaffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.nahkampfwaffe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='nahkampfwaffe',
            name='slots',
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotNahkampfwaffe', to='shop.tag'),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
