# Generated by Django 5.2.9 on 2026-09-20 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_slotnahkampfwaffe_alter_nahkampfwaffe_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBegleiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.begleiter')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='begleiter',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotBegleiter', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='SlotEinbaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.einbaute')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='einbaute',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotEinbaute', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='SlotFernkampfwaffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fernkampfwaffe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotFernkampfwaffe', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='SlotRitual_Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ritual_rune')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotRitual_Rune', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='SlotZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zauber')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zauber',
            name='slots',
            field=models.ManyToManyField(through='shop.SlotZauber', to='shop.tag'),
        ),
    ]
