# Generated by Django 5.2.9 on 2026-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0092_slotbegleiter_begleiter_slots_sloteinbaute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='begleiter',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.AddField(
            model_name='einbaute',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.AddField(
            model_name='zauber',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
    ]
