# Generated by Django 5.2.9 on 2026-09-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_begleiter_possible_upgrades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
