# Generated by Django 5.2.9 on 2026-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='field_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='influenced_field',
            field=models.CharField(blank=True, choices=[('schaden', 'Schaden'), ('schadensart', 'Schadensart'), ('dk', 'DK'), ('präzision', 'Präzision'), ('reichweite', 'Reichweite'), ('wirkbereich', 'Wirkbereich'), ('händigkeit', 'Händigkeit'), ('feuerrate', 'Feuerrate'), ('manaverbrauch', 'Manaverbrauch'), ('hp', 'HP'), ('physische_reaktion', 'physische Reaktion'), ('astrale_reaktion', 'astrale Reaktion'), ('physischer_widerstand', 'physischer Widerstand'), ('astraler_widerstand', 'astraler Widerstand')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fernkampfwaffe',
            name='wirkbereich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='munition',
            name='wirkbereich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nahkampfwaffe',
            name='wirkbereich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ritual_rune',
            name='wirkbereich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='beschreibung',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='zauber',
            name='wirkbereich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='zauber',
            name='wirkdauer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
