# Generated by Django 5.2.9 on 2026-09-21 12:07

from django.db import migrations, models
from django.db.models import F
from django.db.models.aggregates import Count

def migrate_fwaffe_munition(apps, schema_editor):
    Fernkampfwaffe = apps.get_model('shop', 'Fernkampfwaffe')
    RelMunition = apps.get_model('character', 'RelMunition')

    for w in Fernkampfwaffe.objects.annotate(m=Count("munition")).prefetch_related("munition").filter(m=1):
        m = w.munition.first()    

        # schadensart, bs, zs on munition
        m.zs += w.zs
        m.bs += w.bs
        m.schadensart = m.schadensart or w.schadensart
        m.save()

        # update price for 1 bullet
        for f in m.firmamunition_set.all():
            f.preis=f.preis // m.schuss
            f.save()

        # schuss on fwaffe
        w.schuss = m.schuss
        w.save()

    # give people munition * schuss
    for rel in RelMunition.objects.prefetch_related("item").exclude(item__schuss=1):
        rel.anz*= rel.item.schuss
        rel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_upgrade_field_value_upgrade_influenced_field_and_more'),
        ('character', '0211_rename_relfirmawaffe_werkzeug_relfirmanahkampfwaffe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='schuss',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(migrate_fwaffe_munition),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='schaden',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='schadensart',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='zs',
        ),
        migrations.RemoveField(
            model_name='munition',
            name='schuss',
        ),
    ]
