# Generated by Django 5.2.9 on 2026-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0096_auto_20260921_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='influenced_field',
            field=models.CharField(blank=True, choices=[('schaden', 'Schaden'), ('schadensart', 'Schadensart'), ('dk', 'DK'), ('schuss', 'Schuss'), ('präzision', 'Präzision'), ('reichweite', 'Reichweite'), ('wirkbereich', 'Wirkbereich'), ('händigkeit', 'Händigkeit'), ('feuerrate', 'Feuerrate'), ('manaverbrauch', 'Manaverbrauch'), ('hp', 'HP'), ('physische_reaktion', 'physische Reaktion'), ('astrale_reaktion', 'astrale Reaktion'), ('physischer_widerstand', 'physischer Widerstand'), ('astraler_widerstand', 'astraler Widerstand')], max_length=64, null=True),
        ),
    ]
