# Generated by Django 5.2.9 on 2026-09-21 15:03

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0212_rename_relfirmaausrüstung_technik_relfirmatechnik'),
        ('shop', '0097_alter_upgrade_influenced_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ausrüstung_Technik',
            new_name='Technik',
        ),
        migrations.RenameModel(
            old_name='FirmaAusrüstung_Technik',
            new_name='FirmaTechnik',
        ),
        migrations.AlterModelOptions(
            name='technik',
            options={'ordering': ['name'], 'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
        migrations.RemoveField(
            model_name='technik',
            name='manifestverlust',
        ),
        migrations.RemoveField(
            model_name='technik',
            name='manifestverlust_str',
        ),
        migrations.AlterField(
            model_name='item',
            name='kategorie',
            field=models.CharField(choices=[('n', 'Nahrungsmittel'), ('h', 'Heilung'), ('t', 'Tränke'), ('bt', 'besondere Tränke'), ('d', 'Drogen'), ('hd', 'harte Drogen'), ('g', 'Mono-/Oligo-/Polygrome'), ('a', 'Technik - Verschiedenes'), ('p', 'Technik - Programme')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('h', 'Nahkampfwaffen'), ('m', 'Munition'), ('s', 'Fernkampfwaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
    ]
