# Generated by Django 5.2.9 on 2026-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0098_remove_ausrüstung_technik_firmen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kategorie',
            field=models.CharField(choices=[('n', 'Nahrungsmittel'), ('h', 'Heilung'), ('t', 'Tränke'), ('bt', 'besondere Tränke'), ('d', 'Drogen'), ('hd', 'harte Drogen'), ('s', 'Sonstiges')], default='n', max_length=2),
        ),
    ]
