# Generated by Django 5.2.9 on 2026-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_alter_item_kategorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotbegleiter',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='sloteinbaute',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='slotfernkampfwaffe',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='slotnahkampfwaffe',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='slotritual_rune',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='slotzauber',
            options={'ordering': ['item', 'tag__name'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),


        migrations.RemoveField(
            model_name='slotbegleiter',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='sloteinbaute',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='slotfernkampfwaffe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='slotnahkampfwaffe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='slotritual_rune',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='slotzauber',
            name='tag',
        ),


        migrations.AddField(
            model_name='slotbegleiter',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
        migrations.AddField(
            model_name='sloteinbaute',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
        migrations.AddField(
            model_name='slotfernkampfwaffe',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
        migrations.AddField(
            model_name='slotnahkampfwaffe',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
        migrations.AddField(
            model_name='slotritual_rune',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
        migrations.AddField(
            model_name='slotzauber',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),


        migrations.RemoveField(
            model_name='begleiter',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='einbaute',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='nahkampfwaffe',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='ritual_rune',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='zauber',
            name='slots',
        ),


        migrations.AddField(
            model_name='begleiter',
            name='slots',
            field=models.ManyToManyField(to='shop.slotbegleiter'),
        ),
        migrations.AddField(
            model_name='einbaute',
            name='slots',
            field=models.ManyToManyField(to='shop.sloteinbaute'),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='slots',
            field=models.ManyToManyField(to='shop.slotfernkampfwaffe'),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='slots',
            field=models.ManyToManyField(to='shop.slotnahkampfwaffe'),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='slots',
            field=models.ManyToManyField(to='shop.slotritual_rune'),
        ),
        migrations.AddField(
            model_name='zauber',
            name='slots',
            field=models.ManyToManyField(to='shop.slotzauber'),
        ),
    ]
