# Generated by Django 5.2.9 on 2026-09-25 09:57

from django.db import migrations, models

def migrate_wirkbereich_Fwaffe(apps, schema_editor):
    Fernkampfwaffe = apps.get_model('shop', 'Fernkampfwaffe')

    for f in Fernkampfwaffe.objects.exclude(wirkbereich=''):
        for m in f.munition_set.all():
            m.wirkbereich = f"{m.wirkbereich}, {f.wirkbereich}" if m.wirkbereich else f.wirkbereich
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0100_alter_slotbegleiter_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_wirkbereich_Fwaffe),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='wirkbereich',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='achievement_requirement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
