# Generated by Django 5.2.9 on 2026-10-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_alter_alchemie_icon_alter_begleiter_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['factor'], 'verbose_name': 'Modifier', 'verbose_name_plural': 'Modifier'},
        ),
        migrations.RenameField(
            model_name='modifier',
            old_name='price_modifier',
            new_name='factor',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='is_factor_not_addition',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='prio',
        ),
    ]
