# Generated by Django 5.2.9 on 2026-10-03 15:48

from django.db.models import F, OuterRef, Subquery
import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Coalesce

def migrate_prices(apps, schema_editor):
    modelnames = ["item","nahkampfwaffe","munition","fernkampfwaffe","magische_ausrüstung","ritual_rune","rüstung","technik","fahrzeug","einbaute","zauber","alchemie","tinker","begleiter","engelsroboter"]
    for model_name in modelnames:
        model = apps.get_model('shop', model_name)
        firma_model = apps.get_model('shop', f"firma{model_name}")

        model.objects.annotate(
            ofirma = Subquery(firma_model.objects.filter(item=OuterRef("pk")).order_by("-verfügbarkeit").values("firma")[:1]),
            oprice = Subquery(firma_model.objects.filter(item=OuterRef("pk")).order_by("-verfügbarkeit").values("preis")[:1]),
            overfügbarkeit = Coalesce(Subquery(firma_model.objects.filter(item=OuterRef("pk")).order_by("-verfügbarkeit").values("verfügbarkeit")[:1]), 0),
        ).update(firma=F("ofirma"), price=F("oprice"), verfügbarkeit=F("overfügbarkeit"))


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0213_remove_relfirmabegleiter_char_and_more'),
        ('shop', '0103_alter_modifier_options_and_more'),
    ]

    operations = [
        # add price, firma, verfügbarkeit to BaseShops
        migrations.AddField(
            model_name='alchemie',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='alchemie',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alchemie',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='begleiter',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='einbaute',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='einbaute',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einbaute',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fernkampfwaffe',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magische_ausrüstung',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='magische_ausrüstung',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magische_ausrüstung',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='munition',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='munition',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='munition',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nahkampfwaffe',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritual_rune',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rüstung',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='rüstung',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rüstung',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technik',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='technik',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technik',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tinker',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='tinker',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tinker',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zauber',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.firma'),
        ),
        migrations.AddField(
            model_name='zauber',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zauber',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),

        # migrate price, firma, verfügbarkeit of most expensive
        migrations.RunPython(migrate_prices),

        # Delete M2M-relations
        migrations.RemoveField(
            model_name='alchemie',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmabegleiter',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmabegleiter',
            name='item',
        ),
        migrations.RemoveField(
            model_name='begleiter',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmaeinbaute',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmaeinbaute',
            name='item',
        ),
        migrations.RemoveField(
            model_name='einbaute',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmaengelsroboter',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmaengelsroboter',
            name='item',
        ),
        migrations.RemoveField(
            model_name='engelsroboter',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmafahrzeug',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmafahrzeug',
            name='item',
        ),
        migrations.RemoveField(
            model_name='fahrzeug',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmafernkampfwaffe',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmafernkampfwaffe',
            name='item',
        ),
        migrations.RemoveField(
            model_name='fernkampfwaffe',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmaitem',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmaitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmamagische_ausrüstung',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmamagische_ausrüstung',
            name='item',
        ),
        migrations.RemoveField(
            model_name='magische_ausrüstung',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmamunition',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmamunition',
            name='item',
        ),
        migrations.RemoveField(
            model_name='munition',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmanahkampfwaffe',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmanahkampfwaffe',
            name='item',
        ),
        migrations.RemoveField(
            model_name='nahkampfwaffe',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmaritual_rune',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ritual_rune',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmarüstung',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmarüstung',
            name='item',
        ),
        migrations.RemoveField(
            model_name='rüstung',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmatechnik',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmatechnik',
            name='item',
        ),
        migrations.RemoveField(
            model_name='technik',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmatinker',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmatinker',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='firmazauber',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmazauber',
            name='item',
        ),
        migrations.RemoveField(
            model_name='zauber',
            name='firmen',
        ),

        # Delete FirmaShop models
        migrations.DeleteModel(
            name='FirmaAlchemie',
        ),
        migrations.DeleteModel(
            name='FirmaBegleiter',
        ),
        migrations.DeleteModel(
            name='FirmaEinbaute',
        ),
        migrations.DeleteModel(
            name='FirmaEngelsroboter',
        ),
        migrations.DeleteModel(
            name='FirmaFahrzeug',
        ),
        migrations.DeleteModel(
            name='FirmaFernkampfwaffe',
        ),
        migrations.DeleteModel(
            name='FirmaItem',
        ),
        migrations.DeleteModel(
            name='FirmaMagische_Ausrüstung',
        ),
        migrations.DeleteModel(
            name='FirmaMunition',
        ),
        migrations.DeleteModel(
            name='FirmaNahkampfwaffe',
        ),
        migrations.DeleteModel(
            name='FirmaRitual_Rune',
        ),
        migrations.DeleteModel(
            name='FirmaRüstung',
        ),
        migrations.DeleteModel(
            name='FirmaTechnik',
        ),
        migrations.DeleteModel(
            name='FirmaTinker',
        ),
        migrations.DeleteModel(
            name='FirmaZauber',
        ),
    ]
