# Generated by Django 5.2.9 on 2026-10-05 11:57

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_remove_alchemie_firmen_remove_firmabegleiter_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to=''),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='manaverbrauch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='upgrade', to='shop.upgrade'),
        ),
        migrations.AlterField(
            model_name='nahkampfwaffe',
            name='kategorie',
            field=models.CharField(choices=[('d', 'Dolche/Messer'), ('s', 'Schwerter'), ('a', 'Äxte'), ('h', 'Hämmer'), ('h', 'stumpfe Waffen'), ('c', 'Schwungwaffen'), ('l', 'waffenloser Kampf'), ('g', 'Granaten/Bomben'), ('e', 'Exoten'), ('w', 'weitere Waffen')], default='d', max_length=2),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='influenced_field',
            field=models.CharField(blank=True, choices=[('schaden', 'Schaden'), ('schadensart', 'Schadensart'), ('dk', 'DK'), ('schuss', 'Schuss'), ('präzision', 'Präzision'), ('reichweite', 'Reichweite'), ('wirkbereich', 'Wirkbereich'), ('händigkeit', 'Händigkeit'), ('feuerrate', 'Feuerrate'), ('hp', 'HP'), ('physische_reaktion', 'physische Reaktion'), ('astrale_reaktion', 'astrale Reaktion'), ('physischer_widerstand', 'physischer Widerstand'), ('astraler_widerstand', 'astraler Widerstand')], max_length=64, null=True),
        ),
    ]
