# Generated by Django 5.2.9 on 2026-10-05 19:56

from django.db import migrations

def set_most_to_frei_editierbar(apps, schema_editor):
    model_names = ['begleiter','einbaute', 'fernkampfwaffe', 'nahkampfwaffe', 'ritual_rune', 'zauber']
    for model_name in model_names:
        Model = apps.get_model('shop', model_name)
        Model.objects.filter(possible_upgrades=None).update(frei_editierbar=True)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0105_firma_icon_upgrade_manaverbrauch_and_more'),
    ]

    operations = [
        migrations.RunPython(set_most_to_frei_editierbar)
    ]
