# Generated by Django 5.2.9 on 2026-10-06 09:27

from django.db import migrations, models

def add_Tier_slots_on_zaubers(apps, schema_editor):
    Tag = apps.get_model("shop", "tag")
    tags = [Tag.objects.get_or_create(name=name)[0] for name in ["Tier I", "Tier II", "Tier III", "Tier IV", "Tier V", "Tier VI", "Tier VII"]]
    
    Zauber = apps.get_model('shop', 'zauber')
    SlotZauber = apps.get_model('shop', 'slotzauber')

    for zauber in Zauber.objects.filter(slotzauber=None):
        for tag in tags:
            slot = SlotZauber.objects.create(item=zauber)
            slot.tag.add(tag)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_auto_20261005_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.RunPython(add_Tier_slots_on_zaubers)
    ]
