# Generated by Django 5.2.9 on 2026-10-06 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def set_rüstung_to_frei_editierbar(apps, schema_editor):
    Model = apps.get_model('shop', 'rüstung')
    Model.objects.filter(possible_upgrades=None).update(frei_editierbar=True)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_alter_upgrade_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgrade',
            options={'ordering': ['name', 'tag', 'ab_stufe', 'price'], 'verbose_name': 'Upgrade', 'verbose_name_plural': 'Upgrades'},
        ),
        migrations.AddField(
            model_name='rüstung',
            name='possible_upgrades',
            field=models.ManyToManyField(to='shop.upgrade'),
        ),
        migrations.CreateModel(
            name='SlotRüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rüstung')),
                ('tag', models.ManyToManyField(to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['item', 'tag__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rüstung',
            name='slots',
            field=models.ManyToManyField(to='shop.slotrüstung'),
        ),
        migrations.RunPython(set_rüstung_to_frei_editierbar),
    ]
