# Generated by Django 5.2.9 on 2026-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_alter_upgrade_options_rüstung_possible_upgrades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='influenced_field',
            field=models.CharField(blank=True, choices=[('schaden', 'Schaden'), ('schadensart', 'Schadensart'), ('dk', 'DK'), ('schuss', 'Schuss'), ('präzision', 'Präzision'), ('reichweite', 'Reichweite'), ('wirkbereich', 'Wirkbereich'), ('händigkeit', 'Händigkeit'), ('feuerrate', 'Feuerrate'), ('hp', 'HP'), ('schutz', 'Schutz'), ('damage_speciality', 'Besonderheiten bei Schadensarten'), ('haltbarkeit', 'Haltbarkeit'), ('physische_reaktion', 'physische Reaktion'), ('astrale_reaktion', 'astrale Reaktion'), ('physischer_widerstand', 'physischer Widerstand'), ('astraler_widerstand', 'astraler Widerstand')], max_length=64, null=True),
        ),
    ]
