# Generated by Django 5.2.9 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0109_alter_upgrade_influenced_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rüstung',
            name='damage_speciality',
            field=models.TextField(blank=True, default='', verbose_name='Besonderheiten bei Schadensarten'),
        ),
    ]
