# Generated by Django 5.2.9 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_alter_rüstung_damage_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rüstung',
            name='schutz',
            field=models.CharField(blank=True, default='0', max_length=64),
        ),
    ]
