# Generated by Django 5.2.9 on 2026-10-08 11:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_alter_rüstung_schutz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to=''),
        ),
    ]
