# Generated by Django 4.2.8 on 2024-09-15 12:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='textColor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
