# Generated by Django 4.2.8 on 2024-09-15 13:34

from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0002_party_textcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Gesetzbuch', max_length=128)),
                ('paragraph', models.CharField(max_length=16)),
                ('text', markdownfield.models.MarkdownField(rendered_field='text_rendered')),
                ('text_rendered', markdownfield.models.RenderedMarkdownField()),
                ('voting_deadline', models.DateTimeField(blank=True, null=True)),
                ('voting_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gesetz',
                'verbose_name_plural': 'Gesetze',
                'ordering': ['code', 'paragraph'],
            },
        ),
        migrations.CreateModel(
            name='PoliticianVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('y', 'Ja'), ('n', 'Nein'), ('e', 'Enthaltung'), ('a', 'nicht anwesend')], default='a', max_length=1)),
                ('legal_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.legalact')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.politician')),
            ],
            options={
                'verbose_name': 'Abstimmung',
                'verbose_name_plural': 'Abstimmungen',
                'ordering': ['legal_act', 'politician'],
                'unique_together': {('legal_act', 'politician')},
            },
        ),
        migrations.AddField(
            model_name='legalact',
            name='votes',
            field=models.ManyToManyField(through='politics.PoliticianVote', to='politics.politician'),
        ),
    ]
