# Generated by Django 2.0.5 on 2019-01-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='show_in_admin',
            field=models.BooleanField(default=True),
        ),
    ]
