# Generated by Django 4.1.7 on 2023-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0078_remove_charakter_eco_remove_charakter_morph_and_more'),
        ('fileserver', '0002_file_show_in_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='files',
        ),
        migrations.RemoveField(
            model_name='story',
            name='sichtbar_für',
        ),
        migrations.RemoveField(
            model_name='file',
            name='show_in_admin',
        ),
        migrations.RenameModel(
            old_name='Map',
            new_name='Topic'
        ),
        migrations.DeleteModel(
            name='Story',
        )
    ]
