"""
Django settings for ppServer project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = int(os.environ.get('DEBUG'))

ALLOWED_HOSTS = [i.strip() for i in os.environ.get('ALLOWED_HOSTS').split(",")]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'daphne',   # needs to be before "django.contrib.staticfiles"
    
    # django
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    # libs/plugins
    'colorfield',
    'dbbackup',
    'debug_toolbar',
    'django_bootstrap5',
    'django_filters',
    'django_prometheus',
    'django_tables2',
    'markdownfield',
    'markdown_view',
    'push_notifications',
    "crispy_forms",
    "crispy_bootstrap5",
    "django_password_eye",

    # own apps
    'admin',   # replacement for 'django.contrib.admin'
    'auth_custom',
    'base',
    'cards',
    'campaign',
    'changelog',
    'character',
    'characterExport',
    'chat',
    'combat',
    'crafting',
    'create',
    'dex',
    'effect',
    'fileserver',
    'httpChat',
    'lerneinheiten',
    'levelUp',
    'log',
    'logRequest',
    'news',
    'planner',
    'politics',
    'polls',
    'quiz',
    'service',
    'shop',
    'time_space',
    'todays_fact',
    'todo',
    'webPush',
    'wiki',
]

MIDDLEWARE = [
    "logRequest.middleware.SentryignoreDisallowedHostMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",

    # django
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # own middleware
    "character.middleware.SpielerMiddleware",
    "logRequest.middleware.RequestMiddleware",

    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'ppServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # custom
                "webPush.context_processors.push_settings",
            ],
        },
    },
]

# WSGI_APPLICATION = 'ppServer.wsgi.application'
ASGI_APPLICATION = 'ppServer.routing.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT'),
        'CONN_MAX_AGE': 0,
    }
}

# storages, see https://docs.djangoproject.com/en/4.2/ref/settings/#storages
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


###################################################
# dbbackup config
STORAGES['dbbackup'] = {
    'BACKEND': 'django.core.files.storage.FileSystemStorage',
    'OPTIONS': {
        'location': os.path.join(BASE_DIR, 'backups'),
    },
}
DBBACKUP_FILENAME_TEMPLATE = 'postgres_{datetime}.{extension}'
DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'media_{datetime}.{extension}'


###################################################
# PASSWORD VALIDATION

# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'auth_custom.module.EmailOrUsernameBackend',
)


###################################################
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'de-de'
USE_I18N = True

TIME_ZONE = 'Europe/Berlin'
USE_TZ = True

USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = "."
APPEND_SLASH = True

LOGIN_URL = "/auth/login/"


###################################################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2048 # higher than the count of fields
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'   # use int as model-ids

###################################################
# DJANGO CHANNELS

# TODO use redis or similar?
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


###################################################
# SMTP Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# show debug-toolbar if matches
INTERNAL_IPS = ["localhost", "127.0.0.1"] if DEBUG else []


###################################################
# django-tables2

# default template for tables generated with django-tables2
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5-responsive.html"


###################################################
# BOOTSTRAP
# TODO?
# BOOTSTRAP5 = {
#     "theme_url": os.path.join(BASE_DIR, 'static', "base", "css", "theme") # Or I could override the theme here
# }

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG

###################################################
# markdown-field

# AttributeError: 'Settings' object has no attribute 'SITE_URL' of markdown-field
SITE_URL = ''


###################################################
# LOGGING
import logging.config

# Clear prev config
LOGGING_CONFIG = None

# Get loglevel from env
LOGLEVEL = os.environ.get('DJANGO_LOGLEVEL', 'info').upper()

logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(module)s %(process)d %(thread)d %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'loggers': {
        '': {
            'level': LOGLEVEL,
            'handlers': ['console',],
        },
    },
})


###################################################
# SENTRY
if not DEBUG:
    sentry_sdk.init(
        dsn=os.environ.get('SENTRY_DSN'),
        integrations=[DjangoIntegration()],

        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=1.0,

        # If you wish to associate users to errors (assuming you are using django.contrib.auth) you may enable sending PII data.
        send_default_pii=True
    )


###################################################
# PUSHIES
PUSH_NOTIFICATIONS_SETTINGS = {
    "WP_PRIVATE_KEY": os.path.join(BASE_DIR, "webPush", "certs", "private_key.pem"),
    "WP_CLAIMS": {'sub': os.environ.get('PUSH_NOTIFICATION_CONTACT') },
    "UNIQUE_REG_ID": True,
}

PUSH_NOTIFICATION_KEY = os.environ.get('PUSH_NOTIFICATION_KEY')


###################################################
# PROMETHEUS
PROMETHEUS_EXPORT_MIGRATIONS = os.environ.get("PROMETHEUS_EXPORT_MIGRATIONS", True)
# PROMETHEUS_METRIC_NAMESPACE='local'

CACHES = {
    "default": {
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
    }
}
