services:
  db:
    container_name: postgres
    image: dhi.io/postgres:18-alpine3.22
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./ppServer/backups:/var/lib/postgresql/backups:ro
    networks:
      - django_internal
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev.db
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5


  # django:
  #   container_name: django
  #   restart: unless-stopped
  #   build:
  #     context: ./ppServer
  #     dockerfile: Dockerfile.dev    
  #   volumes:
  #     - ./ppServer/backend:/var/www
  #   networks:
  #     - django_nginx
  #     - visual_prometheus_django
  #     - django_internal
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     db:
  #       condition: service_healthy


  # nginx:
  #   container_name: nginx
  #   image: dhi.io/nginx:1-alpine3.21-dev
  #   restart: unless-stopped
  #   networks:
  #     - django_nginx
  #     - visual_grafana_nginx
  #   ports:
  #     - 80:80
  #     # - 443:443
  #   volumes:
  #     - ./nginx_dev:/etc/nginx:ro
  #   environment:
  #     - TZ=Europe/Berlin


  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - django_internal
    ports:
      - 5000:5000
    environment:
      - PGADMIN_LISTEN_PORT=5000
      - PGADMIN_DEFAULT_EMAIL=vsteinbr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - ./ppServer/backups:/backups:ro
      - pgadmin_workdir:/var/lib/pgadmin



volumes:
  postgres_data:
  django_src_volume:
  pgadmin_workdir:


networks:
  django_internal: # db, django
  django_nginx:    # django, nginx
  visual_prometheus_django: # django
    external: true
  visual_grafana_nginx: # nginx
    external: true