version: '3.7'

services:

  wordpress:
    container_name: wordpress
    image: wordpress:6
    restart: unless-stopped
    env_file:
      - ./.env.prod
    expose:
      - 80
    depends_on:
      - wordpress-db

  wordpress-db:
    container_name: wordpress-db
    image: mysql:8.0-debian
    restart: unless-stopped
    env_file:
      - ./.env.prod.db
    volumes:
      - wordpressdb_data:/var/lib/mysql/
    expose:
      - 3306


  monsterdex-backend:
    container_name: monsterdex-backend
    build: ./monsterdexBackend
    env_file:
      - ./.env.dev
    ports:
      - 5000:5000

  monsterdex-app-build:
    container_name: monsterdex-app-build
    build: ./monsterdexApp
    env_file:
      - ./.env.dev
    volumes:
      - monsterdex_app:/usr/angular-workdir/www

volumes:
  monsterdex_app:
  wordpressdb_data:
