version: '3.7'

services:
  db:
    container_name: pnp-db
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - ./.env.staging.db

  nginx:
    container_name: pnp-webserver
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_staging:/etc/nginx:ro
      - ./log/nginx:/var/log/nginx/

volumes:
  postgres_data: