# Generated by Django 2.2.13 on 2020-12-19 12:05

from django.db import migrations, models
import time_space.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Looper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
                ('nodeType', models.PositiveSmallIntegerField(choices=[(0, 'Linearriss'), (1, 'Liniendeletion'), (2, 'Splinter'), (3, 'Duplikator'), (4, 'Looper'), (5, 'Timelagger'), (6, 'Timedelayer'), (7, 'Runner'), (30, 'Consumer'), (31, 'Eraser'), (32, 'Blurr'), (33, 'Short'), (34, 'Traceback'), (70, 'Raumfissur'), (71, 'Wurmloch'), (72, 'Raumloch'), (73, 'Kapselphänomen'), (74, 'Bizarrgebiet'), (100, 'Mirror'), (101, 'Inverter'), (102, 'Aktivator'), (103, 'Switch'), (104, 'Konverter'), (105, 'Barriere'), (130, 'Manadegenerator'), (131, 'Manabombe'), (132, 'Supportgatter'), (133, 'Teleportgatter'), (170, 'Sensorgatter'), (171, 'Tracinggatter')], default=time_space.enums.NodeType(4))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
                ('nodeType', models.PositiveSmallIntegerField(choices=[(0, 'Linearriss'), (1, 'Liniendeletion'), (2, 'Splinter'), (3, 'Duplikator'), (4, 'Looper'), (5, 'Timelagger'), (6, 'Timedelayer'), (7, 'Runner'), (30, 'Consumer'), (31, 'Eraser'), (32, 'Blurr'), (33, 'Short'), (34, 'Traceback'), (70, 'Raumfissur'), (71, 'Wurmloch'), (72, 'Raumloch'), (73, 'Kapselphänomen'), (74, 'Bizarrgebiet'), (100, 'Mirror'), (101, 'Inverter'), (102, 'Aktivator'), (103, 'Switch'), (104, 'Konverter'), (105, 'Barriere'), (130, 'Manadegenerator'), (131, 'Manabombe'), (132, 'Supportgatter'), (133, 'Teleportgatter'), (170, 'Sensorgatter'), (171, 'Tracinggatter')], default=time_space.enums.NodeType(100))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startNodeId', models.IntegerField()),
            ],
        ),
    ]
