# Generated by Django 2.2.13 on 2020-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0003_auto_20201219_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looper',
            name='nodeType',
        ),
        migrations.RemoveField(
            model_name='mirror',
            name='nodeType',
        ),
        migrations.AlterField(
            model_name='net',
            name='startNode',
            field=models.TextField(default=''),
        ),
    ]
