# Generated by Django 3.1.4 on 2021-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0004_auto_20201219_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='net',
            options={'verbose_name': 'Netz', 'verbose_name_plural': 'Netze'},
        ),
    ]
