# Generated by Django 3.1.7 on 2022-04-07 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0006_activator_barrier_converter_duplikator_inverter_linearriss_liniendeletion_manabomb_manadegenerator_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorgatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supportgatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teleportgatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracinggatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Activator',
            new_name='Aktivator',
        ),
        migrations.RenameModel(
            old_name='Barrier',
            new_name='Barriere',
        ),
        migrations.RenameModel(
            old_name='Converter',
            new_name='Konverter',
        ),
        migrations.RenameModel(
            old_name='Manabomb',
            new_name='Manabombe',
        ),
        migrations.AddField(
            model_name='duplikator',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='duplikator',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='linearriss',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='linearriss',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='liniendeletion',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='liniendeletion',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='looper',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='looper',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='runner',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='runner',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='splinter',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='splinter',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='timedelayer',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timedelayer',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='timelagger',
            name='net_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timelagger',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
