# Generated by Django 3.1.7 on 2022-04-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0008_looper_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplikator',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linearriss',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liniendeletion',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='looper',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runner',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='splinter',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedelayer',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedelayer',
            name='prev_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timelagger',
            name='next_required_input_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='looper',
            name='outputs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
