# Generated by Django 2.0.5 on 2018-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20181120_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachteil',
            name='wann_wählbar',
            field=models.CharField(choices=[('i', 'immer'), ('e', 'in Erstellung'), ('n', 'nicht Erstelllung')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='vorteil',
            name='wann_wählbar',
            field=models.CharField(choices=[('i', 'immer'), ('e', 'in Erstellung'), ('n', 'nicht Erstelllung')], default='i', max_length=1),
        ),
    ]
