# Generated by Django 2.0.5 on 2018-12-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20181120_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='geburtstag',
            field=models.DateField(blank=True, null=True),
        ),
    ]
