# Generated by Django 2.0.5 on 2019-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20181210_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreeentrykategorie',
            name='kategorie',
            field=models.CharField(choices=[('sk', 'Krit. Schaden'), ('st', 'Tödl. Schaden'), ('ak', 'Krit. Abwehr'), ('at', 'Totale Abwehr'), ('ss', 'Schaden'), ('sm', 'Munition'), ('sp', 'Präzision'), ('sd', 'Durchschlagskraft'), ('sr', 'Reichweite'), ('sb', 'BS'), ('zs', 'Wirkung'), ('sa', 'Astralschaden'), ('zw', 'Wirkdauer'), ('ze', 'Aufrechterhalten'), ('zc', 'Schwellwert'), ('tp', 'Prozession'), ('tw', 'Wifi'), ('tj', 'Projektion'), ('ts', 'Sicherheit'), ('te', 'Speicher'), ('ru', 'Schutz'), ('rt', 'Stärke'), ('kw', 'Wirkdauer'), ('ke', 'Effekt')], max_length=2, null=True),
        ),
    ]
