# Generated by Django 2.0.5 on 2020-06-01 15:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200601_1653'),
        ('character', '0014_auto_20200601_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Alchemie')),
            ],
            options={
                'verbose_name': 'Alchemie',
                'verbose_name_plural': 'Alchemie',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaAlchemie')),
            ],
            options={
                'verbose_name': 'Alchemie Verfügbarkeit',
                'verbose_name_plural': 'Alchemie Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStAlchemie')),
            ],
            options={
                'verbose_name': 'Alchemie (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Alchemie (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelStAlchemie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StAlchemie')),
            ],
            options={
                'verbose_name': 'Alchemie (stufenabh)',
                'verbose_name_plural': 'Alchemie (stufenabh)',
            },
        ),
    ]
