# Generated by Django 2.0.5 on 2020-06-08 20:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200608_2248'),
        ('character', '0015_relalchemie_relfirmaalchemie_relfirmastalchemie_relstalchemie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelFirmaStTinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStTinker')),
            ],
            options={
                'verbose_name': 'Für Selbstständige (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Für Selbstständige (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaTinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaTinker')),
            ],
            options={
                'verbose_name': 'Für Selbstständige Verfügbarkeit',
                'verbose_name_plural': 'Für Selbstständige Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelStTinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StTinker')),
            ],
            options={
                'verbose_name': 'Für Selbstständige (stufenabh)',
                'verbose_name_plural': 'Für Selbstständige (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelTinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tinker')),
            ],
            options={
                'verbose_name': 'Für Selbstständige',
                'verbose_name_plural': 'Für Selbstständige',
            },
        ),
    ]
