# Generated by Django 2.2.13 on 2020-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_relfirmasttinker_relfirmatinker_relsttinker_reltinker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='useEco',
            field=models.BooleanField(blank=True, default=True, verbose_name="benutze 'eco':y, benutze 'morph':n"),
        ),
    ]
