# Generated by Django 2.2.13 on 2020-07-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_auto_20200731_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='fertigkeiten',
            field=models.ManyToManyField(through='character.ProfessionFertigkeit', to='character.Fertigkeit'),
        ),
        migrations.AlterUniqueTogether(
            name='gfsnachteil',
            unique_together={('teil', 'gfs')},
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
            ],
            options={
                'verbose_name': 'Talent',
                'unique_together': {('titel',)},
                'verbose_name_plural': 'Talente',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionWissensfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession')),
                ('wissen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Wissensfertigkeit')),
            ],
            options={
                'verbose_name': 'Startwissensfertigkeit',
                'unique_together': {('profession', 'wissen')},
                'verbose_name_plural': 'Startwissensfertigkeiten',
                'ordering': ['profession', 'wissen'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Talent')),
            ],
            options={
                'verbose_name': 'Starttalent',
                'unique_together': {('profession', 'talent')},
                'verbose_name_plural': 'Starttalente',
                'ordering': ['profession'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionSpezialfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession')),
                ('spezial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezialfertigkeit')),
            ],
            options={
                'verbose_name': 'Startspezialfertigkeit',
                'unique_together': {('profession', 'spezial')},
                'verbose_name_plural': 'Startspezialfertigkeiten',
                'ordering': ['profession', 'spezial'],
            },
        ),
        migrations.RemoveField(
            model_name='gfsnachteil',
            name='notizen',
        ),
        migrations.AddField(
            model_name='profession',
            name='spezial',
            field=models.ManyToManyField(through='character.ProfessionSpezialfertigkeit', to='character.Spezialfertigkeit'),
        ),
        migrations.AddField(
            model_name='profession',
            name='talente',
            field=models.ManyToManyField(through='character.ProfessionTalent', to='character.Talent'),
        ),
        migrations.AddField(
            model_name='profession',
            name='wissen',
            field=models.ManyToManyField(through='character.ProfessionWissensfertigkeit', to='character.Wissensfertigkeit'),
        ),
    ]
