# Generated by Django 2.2.14 on 2020-08-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_auto_20200731_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreeentrygfs',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase'),
        ),
        migrations.AlterField(
            model_name='skilltreeentrygfs',
            name='gfs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Gfs'),
        ),
        migrations.AlterField(
            model_name='skilltreeentrygfs',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
