# Generated by Django 2.2.14 on 2020-08-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0025_auto_20200802_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreeentryprofession',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase'),
        ),
        migrations.AlterField(
            model_name='skilltreeentryprofession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession'),
        ),
        migrations.AlterField(
            model_name='skilltreeentryprofession',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
