# Generated by Django 2.2.14 on 2020-08-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_auto_20200802_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='ap_max',
        ),
    ]
