# Generated by Django 2.2.13 on 2020-08-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0028_auto_20200802_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gfsstufenplan',
            options={'ordering': ['gfs', 'basis'], 'verbose_name': 'Stufenplan', 'verbose_name_plural': 'Stufenpläne'},
        ),
        migrations.AlterModelOptions(
            name='professionstufenplan',
            options={'ordering': ['profession', 'basis'], 'verbose_name': 'Stufenplan', 'verbose_name_plural': 'Stufenpläne'},
        ),
        migrations.CreateModel(
            name='ProfessionStufenplanBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveIntegerField(default=0)),
                ('ep', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('stufe',)},
                'verbose_name': 'Profession Basis-Stufenplan',
                'verbose_name_plural': 'Profession Basis-Stufenpläne',
                'ordering': ['stufe'],
            },
        ),
        migrations.CreateModel(
            name='GfsStufenplanBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveIntegerField(default=0)),
                ('ep', models.PositiveIntegerField(default=0)),
                ('ap', models.PositiveSmallIntegerField(default=0)),
                ('fp', models.PositiveSmallIntegerField(default=0)),
                ('fg', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'unique_together': {('stufe',)},
                'verbose_name': 'Gfs Basis-Stufenplan',
                'verbose_name_plural': 'Gfs Basis-Stufenpläne',
                'ordering': ['stufe'],
            },
        ),
        migrations.AddField(
            model_name='gfsstufenplan',
            name='basis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.GfsStufenplanBase'),
        ),
        migrations.AddField(
            model_name='professionstufenplan',
            name='basis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.ProfessionStufenplanBase'),
        ),
        migrations.AlterUniqueTogether(
            name='gfsstufenplan',
            unique_together={('gfs', 'basis')},
        ),
        migrations.AlterUniqueTogether(
            name='professionstufenplan',
            unique_together={('profession', 'basis')},
        ),
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='ap',
        ),
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='ep',
        ),
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='fg',
        ),
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='gfsstufenplan',
            name='stufe',
        ),
        migrations.RemoveField(
            model_name='professionstufenplan',
            name='ep',
        ),
        migrations.RemoveField(
            model_name='professionstufenplan',
            name='stufe',
        ),
    ]
