# Generated by Django 2.2.13 on 2020-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_auto_20200802_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relnachteil',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='relnachteil',
            name='in_story_erworben',
        ),
        migrations.RemoveField(
            model_name='relvorteil',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='relvorteil',
            name='in_story_erworben',
        ),
        migrations.AddField(
            model_name='gfsnachteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gfsnachteil',
            name='notizen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gfsvorteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relnachteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
