# Generated by Django 2.2.14 on 2020-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0031_auto_20200804_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionstufenplan',
            name='spezial',
        ),
        migrations.RemoveField(
            model_name='professionstufenplan',
            name='wissensp',
        ),
        migrations.AlterField(
            model_name='talent',
            name='tp',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
