# Generated by Django 2.2.13 on 2020-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0035_manually_via_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relfertigkeit',
            name='fp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relfertigkeit',
            name='fp_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
