# Generated by Django 2.2.13 on 2020-08-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0036_auto_20200811_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionfertigkeit',
            name='pool',
        ),
    ]
