# Generated by Django 2.2.13 on 2020-08-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0042_auto_20200815_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relfirmasteinbauten',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmasteinbauten',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmastmagische_ausrüstung',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmastmagische_ausrüstung',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmastwaffen_werkzeuge',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmastwaffen_werkzeuge',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relstausrüstung_technik',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relstausrüstung_technik',
            name='item',
        ),
        migrations.RemoveField(
            model_name='relsteinbauten',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relsteinbauten',
            name='item',
        ),
        migrations.RemoveField(
            model_name='relstmagische_ausrüstung',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relstmagische_ausrüstung',
            name='item',
        ),
        migrations.RemoveField(
            model_name='relstwaffen_werkzeuge',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relstwaffen_werkzeuge',
            name='item',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='st_ausrüstungTechnik',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='st_einbauten',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='st_magischeAusrüstung',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='st_waffenWerkzeuge',
        ),
        migrations.DeleteModel(
            name='RelFirmaStAusrüstung_Technik',
        ),
        migrations.DeleteModel(
            name='RelFirmaStEinbauten',
        ),
        migrations.DeleteModel(
            name='RelFirmaStMagische_Ausrüstung',
        ),
        migrations.DeleteModel(
            name='RelFirmaStWaffen_Werkzeuge',
        ),
        migrations.DeleteModel(
            name='RelStAusrüstung_Technik',
        ),
        migrations.DeleteModel(
            name='RelStEinbauten',
        ),
        migrations.DeleteModel(
            name='RelStMagische_Ausrüstung',
        ),
        migrations.DeleteModel(
            name='RelStWaffen_Werkzeuge',
        ),
    ]
