# Generated by Django 2.2.13 on 2020-08-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0043_auto_20200815_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='relalchemie',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relausrüstung_technik',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='releinbauten',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relfahrzeug',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relitem',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relmagazin',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relmagische_ausrüstung',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relpfeil_bolzen',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relrüstung',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relschusswaffen',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reltinker',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relwaffen_werkzeuge',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='relzauber',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relrituale_runen',
            name='stufe',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
