# Generated by Django 2.2.14 on 2020-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0045_talent_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='kategorie',
            field=models.CharField(choices=[('k', 'Kampfkunst'), ('g', 'Geistig'), ('m', 'Magisch'), ('a', 'Kampfmagisch'), ('u', 'Support'), ('o', 'Sozial'), ('w', 'Schwächend'), ('p', 'Gameplay'), ('v', 'Verteidigung')], default='k', max_length=1),
        ),
    ]
