# Generated by Django 2.2.13 on 2020-08-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0046_auto_20200826_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affektivität',
            name='grad',
        ),
        migrations.RemoveField(
            model_name='affektivität',
            name='umgang',
        ),
    ]
