# Generated by Django 3.1.5 on 2021-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0054_auto_20201223_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relnachteil',
            name='notizen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='relvorteil',
            name='notizen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
