# Generated by Django 3.1.7 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0056_auto_20220221_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='konzentration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
