# Generated by Django 3.1.7 on 2022-05-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0057_charakter_konzentration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speziesattribut',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speziesattribut',
            name='attribut',
        ),
        migrations.RemoveField(
            model_name='speziesattribut',
            name='spezies',
        ),
        migrations.AlterUniqueTogether(
            name='stufenplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stufenplan',
            name='vorteile',
        ),
        migrations.RemoveField(
            model_name='stufenplan',
            name='wesen',
        ),
        migrations.RemoveField(
            model_name='stufenplan',
            name='wesenkräfte',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='verwandlungen',
        ),
        migrations.RemoveField(
            model_name='spezies',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='spezies',
            name='beschreibung',
        ),
        migrations.DeleteModel(
            name='SkilltreeEntryWesen',
        ),
        migrations.DeleteModel(
            name='SpeziesAttribut',
        ),
        migrations.DeleteModel(
            name='Stufenplan',
        ),
    ]
