# Generated by Django 3.1.7 on 2022-05-14 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20220514_1539'),
        ('character', '0058_auto_20220503_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelVergessenerZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=None, null=True)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vergessenerzauber')),
            ],
            options={
                'verbose_name': 'vergessener Zauber',
                'verbose_name_plural': 'vergessene Zauber',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaVergessenerZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.firmavergessenerzauber')),
            ],
            options={
                'verbose_name': 'vergessener Zauber Verfügbarkeit',
                'verbose_name_plural': 'vergessener Zauber Verfügbarkeiten',
            },
        ),
    ]
