# Generated by Django 3.1.7 on 2022-05-27 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20220527_1348'),
        ('character', '0059_relfirmavergessenerzauber_relvergessenerzauber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persönlichkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, unique=True)),
                ('positiv', models.TextField()),
                ('negativ', models.TextField()),
            ],
            options={
                'verbose_name': 'Persönlichkeit',
                'verbose_name_plural': 'Persönlichkeiten',
                'ordering': ['titel'],
            },
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='begleiter',
        ),
        migrations.AddField(
            model_name='charakter',
            name='vergessene_zauber',
            field=models.ManyToManyField(blank=True, through='character.RelVergessenerZauber', to='shop.VergessenerZauber'),
        ),
        migrations.CreateModel(
            name='RelFirmaBegleiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.firmabegleiter')),
            ],
            options={
                'verbose_name': 'Begleiter Verfügbarkeit',
                'verbose_name_plural': 'Begleiter Verfügbarkeiten',
            },
        ),
    ]
