# Generated by Django 3.1.7 on 2022-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20220527_1348'),
        ('character', '0061_auto_20220527_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='begleiter',
            field=models.ManyToManyField(blank=True, through='character.RelBegleiter', to='shop.Begleiter'),
        ),
    ]
