# Generated by Django 3.1.7 on 2022-06-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0062_charakter_begleiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelPersönlichkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('persönlichkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.persönlichkeit')),
            ],
            options={
                'verbose_name': 'Persönlichkeit',
                'verbose_name_plural': 'Persönlichkeiten',
                'ordering': ['char', 'persönlichkeit'],
                'unique_together': {('char', 'persönlichkeit')},
            },
        ),
    ]
