# Generated by Django 4.1.7 on 2023-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0069_alter_wesenkraft_manaverbrauch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wesenkraft',
            name='wirkung',
            field=models.TextField(default=''),
        ),
    ]
