# Generated by Django 4.1.7 on 2023-04-04 12:53

from django.db import migrations

def save_gfs_to_populate_md_rendered_field(apps, schema_editor):
    Gfs = apps.get_model('character', 'Gfs')

    for gfs in Gfs.objects.all():
        gfs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0074_gfs_beschreibung_rendered_alter_gfs_beschreibung'),
    ]

    operations = [
        migrations.RunPython(save_gfs_to_populate_md_rendered_field)
    ]
