# Generated by Django 4.1.7 on 2023-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0077_populate_nachteil_max_amount_vorteil_max_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='eco',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='morph',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='useEco',
        ),
    ]
