# Generated by Django 4.1.7 on 2023-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0079_charakter_ep_stufe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfs',
            name='difficulty',
            field=models.CharField(choices=[('e', 'für Einsteiger'), ('f', 'für Fortgeschrittene'), ('p', 'für Profis')], default='e', max_length=1, verbose_name='.. leicht/mittel/schwer zu spielen sein?'),
        ),
        migrations.AlterField(
            model_name='nachteil',
            name='wann_wählbar',
            field=models.CharField(choices=[('i', 'immer'), ('e', 'in Erstellung'), ('n', 'nicht Erstelllung'), ('g', 'gar nicht')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='vorteil',
            name='wann_wählbar',
            field=models.CharField(choices=[('i', 'immer'), ('e', 'in Erstellung'), ('n', 'nicht Erstelllung'), ('g', 'gar nicht')], default='i', max_length=1),
        ),
    ]
