# Generated by Django 4.1.7 on 2023-06-12 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0080_alter_gfs_difficulty_alter_nachteil_wann_wählbar_and_more'),
        ('shop', '0054_engelsroboter_in_engelsroboter_ma_engelsroboter_st_and_more'),
        ('shop', '0053_engelsroboter_firmaengelsroboter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='prestige',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='verzehr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='ep_stufe_in_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='zauberplätze',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='ap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='fg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='fp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relnachteil',
            name='attribut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.attribut'),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='attribut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.attribut'),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='engelsroboter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.engelsroboter'),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='fertigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.fertigkeit'),
        ),
        migrations.CreateModel(
            name='RelFirmaEngelsroboter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.firmaengelsroboter')),
            ],
            options={
                'verbose_name': 'Engelsroboter Verfügbarkeit',
                'verbose_name_plural': 'Engelsroboter Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelEngelsroboter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=None, null=True)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.engelsroboter')),
            ],
            options={
                'verbose_name': 'Engelsroboter',
                'verbose_name_plural': 'Engelsroboter',
            },
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='will_create',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Begleiter',
        ),
        migrations.AddField(
            model_name='charakter',
            name='engelsroboter',
            field=models.ManyToManyField(blank=True, through='character.RelEngelsroboter', to='shop.engelsroboter'),
        ),
    ]
