# Generated by Django 4.1.7 on 2023-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0082_nachteil_needs_attribut_nachteil_needs_engelsroboter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachteil',
            name='is_sellable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vorteil',
            name='is_sellable',
            field=models.BooleanField(default=True),
        ),
    ]
