# Generated by Django 4.1.7 on 2023-06-17 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0083_nachteil_is_sellable_vorteil_is_sellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachteil',
            name='max_ip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='nachteil',
            name='min_ip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='vorteil',
            name='max_ip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='vorteil',
            name='min_ip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
