# Generated by Django 4.1.7 on 2023-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0085_charakter_persönlichkeit_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsstufenplan',
            name='special_ability_description',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Beschreibung'),
        ),
    ]
