# Generated by Django 4.1.7 on 2023-06-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0086_alter_gfsstufenplan_special_ability_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relzauber',
            name='will_create',
        ),
    ]
