# Generated by Django 4.1.7 on 2023-07-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_zauber_will_create'),
        ('character', '0090_alter_nachteil_options_alter_vorteil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='zauberplätze',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='GfsZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('gfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.gfs')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zauber')),
            ],
            options={
                'verbose_name': 'Startzauber',
                'verbose_name_plural': 'Startzauber',
                'ordering': ['gfs', 'item'],
                'unique_together': {('item', 'gfs')},
            },
        ),
    ]
