# Generated by Django 4.1.7 on 2023-07-17 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0092_remove_relzauber_tier_notes_talent_bedingung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relwesenkraft',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
