# Generated by Django 4.1.7 on 2023-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0093_relwesenkraft_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='relnachteil',
            name='will_create',
            field=models.BooleanField(default=False),
        ),
    ]
