# Generated by Django 4.1.7 on 2023-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0094_relnachteil_will_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='processing_notes',
            field=models.JSONField(default=dict),
        ),
    ]
