# Generated by Django 4.1.7 on 2023-07-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0101_alter_talent_bedingung'),
    ]

    operations = [
        migrations.AddField(
            model_name='relwissensfertigkeit',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
