# Generated by Django 4.1.7 on 2023-07-21 10:45

from django.db import migrations

def würfel2_to_stufe(würfel2) -> int:
    w_stufen = [4, 6, 8, 10, 12, 20, 100]
    return w_stufen.index(würfel2)

def populate_wF_stufe(apps, schema_editor):
    RelWissensfertigkeit = apps.get_model('character', 'RelWissensfertigkeit')

    for rel in RelWissensfertigkeit.objects.all():
        rel.stufe = würfel2_to_stufe(rel.würfel2)
        rel.save(update_fields=["stufe"])


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0102_relwissensfertigkeit_stufe'),
    ]

    operations = [
        migrations.RunPython(populate_wF_stufe)
    ]
