# Generated by Django 4.1.7 on 2023-07-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0103_auto_20230721_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relwissensfertigkeit',
            name='würfel2',
        ),
    ]
