# Generated by Django 4.1.7 on 2023-07-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0104_remove_relwissensfertigkeit_würfel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='processing_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='zauberplätze',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
