# Generated by Django 4.1.7 on 2023-07-25 12:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0111_auto_20230725_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinereadableskilltreeentry',
            name='stufe',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinereadableskilltreeentry',
            name='amount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinereadableskilltreeentry',
            name='operation',
            field=models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'zauberslot'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('B', 'Bonus in Fertigkeit'), ('A', '+ Crit-Angriff'), ('V', '+ Crit-Verteidigung'), ('K', '+ körperliche HP'), ('G', '+ geistige HP'), ('R', 'Roleplay-Text')], default='R', max_length=1),
        ),
    ]
