# Generated by Django 4.1.7 on 2023-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0114_alter_gfsskilltreeentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsskilltreeentry',
            name='operation',
            field=models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'zauberslot'), ('v', 'neuer Vorteil'), ('n', 'neuer Nachteil'), ('x', 'Vorteil weg'), ('z', 'Nachteil weg'), ('e', 'neue Wesenkraft'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('B', 'Bonus in Fertigkeit'), ('A', '+ Crit-Angriff'), ('V', '+ Crit-Verteidigung'), ('K', '+ körperliche HP'), ('G', '+ geistige HP'), ('k', 'Schaden waff. Kampf'), ('I', '+ Initiative fix'), ('r', 'Reaktion'), ('N', 'natürlicher Schadenswiderstand'), ('T', 'Astral-Widerstand'), ('h', 'Shop'), ('R', 'Roleplay-Text')], default='R', max_length=1),
        ),
    ]
