# Generated by Django 4.1.7 on 2023-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0116_gfsskilltreeentry_magische_ausrüstung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wesenkraft',
            name='min_rang',
        ),
        migrations.AddField(
            model_name='charakter',
            name='HPplus_geistig',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='astralwiderstand_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='crit_attack',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='crit_defense',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='initiative_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='natürlicher_schadenswiderstand_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='reaktion_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gfsskilltreeentry',
            name='operation',
            field=models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'Zauberslot/s'), ('v', 'neuer Vorteil'), ('n', 'neuer Nachteil'), ('e', 'neue Wesenkraft'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('B', 'Bonus in Fertigkeit'), ('A', 'Crit-Angriff'), ('V', 'Crit-Verteidigung'), ('K', 'körperliche HP'), ('G', 'geistige HP'), ('k', 'HP Schaden waff. Kampf'), ('I', 'Initiative fix'), ('r', 'Reaktion'), ('N', 'natürlicher Schadenswiderstand'), ('T', 'Astral-Widerstand'), ('h', 'magisches Item'), ('R', 'Roleplay-Text')], default='R', max_length=1),
        ),
    ]
