# Generated by Django 4.1.7 on 2023-07-26 12:17

from django.db import migrations

def transferGfsimg(apps, schema_editor):
    Gfs = apps.get_model('character', 'Gfs')
    GfsImage = apps.get_model('character', 'GfsImage')

    for gfs in Gfs.objects.filter(image__isnull=False):
        GfsImage.objects.create(gfs=gfs, img=gfs.image)

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0118_gfsimage_alter_gfsskilltreeentry_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(transferGfsimg),
        migrations.RemoveField(
            model_name='gfs',
            name='image',
        ),
    ]
