# Generated by Django 4.1.7 on 2023-07-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0123_remove_relattribut_maxwert_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gfsnachteil',
            name='anzahl',
        ),
        migrations.RemoveField(
            model_name='gfsvorteil',
            name='anzahl',
        ),
        migrations.RemoveField(
            model_name='wesenkraft',
            name='wesen',
        ),
        migrations.RemoveField(
            model_name='wesenkraft',
            name='zusatz_manifest',
        ),
    ]
