# Generated by Django 4.1.7 on 2023-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0125_remove_wesenkraft_zusatz_gfsspezifisch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wesenkraft',
            name='skilled_gfs',
            field=models.ManyToManyField(blank=True, related_name='skilled_gfs', to='character.gfs'),
        ),
    ]
