# Generated by Django 4.1.7 on 2023-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0128_charakter_larp_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='HPplus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='HPplus_geistig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='larp_rang',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='rang',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
