# Generated by Django 4.1.7 on 2023-08-09 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0129_alter_charakter_hpplus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='alter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='augenfarbe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='geschlecht',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='gewicht',
            field=models.PositiveIntegerField(default=75, verbose_name='Gewicht in kg'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='größe',
            field=models.PositiveIntegerField(default=170, verbose_name='Größe in cm'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='haarfarbe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='hautfarbe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='notizen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='persönlicheZiele',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='präf_arm',
            field=models.CharField(default='', max_length=100, verbose_name='präferierter Arm (rechts/links?)'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='sexualität',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='sonstiger_manifestverlust',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='sonstiger Manifestverlust'),
        ),
    ]
