# Generated by Django 4.1.7 on 2023-09-15 20:46

from django.db import migrations
import django_resized.forms
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0133_alter_nachteil_has_implementation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spezies',
            name='beschreibung',
            field=markdownfield.models.MarkdownField(default='', rendered_field='beschreibung_rendered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spezies',
            name='beschreibung_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='spezies',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to=''),
        ),
    ]
