# Generated by Django 4.1.7 on 2023-09-09 17:44

from django.db import migrations


def remove_non_wesen(apps, schema_editor):
    Wesen = apps.get_model('character', 'Spezies')
    Wesen.objects.filter(komplexität__gt=18).delete()

def remove_all_chars(apps, schema_editor):
    Charakter = apps.get_model('character', 'Charakter')
    Charakter.objects.all().delete()

def remove_all_ferts(apps, schema_editor):
    Fertigkeit = apps.get_model('character', 'Fertigkeit')
    Fertigkeit.objects.all().delete()

def add_some_attrs(apps, schema_editor):
    Attribut = apps.get_model('character', 'Attribut')
    Gfs = apps.get_model('character', 'Gfs')
    GfsAttribut = apps.get_model('character', 'GfsAttribut')

    attrs = [
        ("MG", "Manergetik"),
        ("LB", "Leitungsbahn"),
        ("DM", "Die Macht"),
        ("11", "11"),
    ]

    for titel, beschreibung in attrs:
        attr = Attribut.objects.create(titel=titel, beschreibung=beschreibung)

        for gfs in Gfs.objects.all():
            GfsAttribut.objects.create(gfs=gfs, attribut=attr)



def add_ferts(apps, schema_editor):
    Fertigkeit = apps.get_model('character', 'Fertigkeit')
    Attribut = apps.get_model('character', 'Attribut')
    attrs = {attr.titel: attr for attr in Attribut.objects.all()}


    Fertigkeit.objects.create(titel="Laufen", attribut=attrs["SCH"], limit="k", gruppe="a")
    Fertigkeit.objects.create(titel="Schwimmen", attribut=attrs["SCH"], limit="k", gruppe="a", impro_possible=False)
    Fertigkeit.objects.create(titel="Klettern", attribut=attrs["ST"], limit="k", gruppe="a", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Wahrnehmung", attribut=attrs["IN"], limit="g", gruppe="b")
    Fertigkeit.objects.create(titel="Wissen", attribut=attrs["IN"], limit="g", gruppe="b")
    Fertigkeit.objects.create(titel="Lehren", attribut=attrs["IN"], limit="g", gruppe="b")
    
    Fertigkeit.objects.create(titel="Orientieren", attribut=attrs["IN"], limit="g", gruppe="c")
    Fertigkeit.objects.create(titel="Erinnern", attribut=attrs["IN"], limit="g", gruppe="c")
    Fertigkeit.objects.create(titel="Lernen", attribut=attrs["IN"], limit="g", gruppe="c")
    
    Fertigkeit.objects.create(titel="Heben", attribut=attrs["SCH"], limit="k", gruppe="d")
    Fertigkeit.objects.create(titel="Werfen", attribut=attrs["SCH"], limit="k", gruppe="d")
    Fertigkeit.objects.create(titel="Fingerfertigkeit", attribut=attrs["SCH"], limit="k", gruppe="d")
    
    Fertigkeit.objects.create(titel="Zähigkeit", attribut=attrs["VER"], limit="k", gruppe="e")
    Fertigkeit.objects.create(titel="Kontern", attribut=attrs["VER"], limit="k", gruppe="e", impro_possible=False)
    Fertigkeit.objects.create(titel="Entschlossenheit", attribut=attrs["WK"], limit="g", gruppe="e")
    
    Fertigkeit.objects.create(titel="Erste Hilfe", attribut=attrs["GES"], limit="k", gruppe="f")
    Fertigkeit.objects.create(titel="Alchemie", attribut=attrs["GES"], limit="k", gruppe="f", impro_possible=False)
    Fertigkeit.objects.create(titel="Beruhigen", attribut=attrs["UM"], limit="g", gruppe="f", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Fahrzeuge", attribut=attrs["SCH"], limit="k", gruppe="g", impro_possible=False)
    Fertigkeit.objects.create(titel="Technik", attribut=attrs["GES"], limit="k", gruppe="g")
    Fertigkeit.objects.create(titel="Schlösser", attribut=attrs["GES"], limit="k", gruppe="g", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Heimlichkeit", attribut=attrs["SCH"], limit="g", gruppe="h")
    Fertigkeit.objects.create(titel="Schauspiel", attribut=attrs["SCH"], limit="k", gruppe="h", impro_possible=False)
    Fertigkeit.objects.create(titel="Täuschen", attribut=attrs["SCH"], limit="g", gruppe="h")
    
    Fertigkeit.objects.create(titel="Verhalten", attribut=attrs["UM"], limit="g", gruppe="i")
    Fertigkeit.objects.create(titel="Verhandeln", attribut=attrs["UM"], limit="g", gruppe="i")
    Fertigkeit.objects.create(titel="Personenkenntnis", attribut=attrs["UM"], limit="g", gruppe="i")
    
    Fertigkeit.objects.create(titel="Spruchzauberei", attribut=attrs["MA"], limit="m", gruppe="j")
    Fertigkeit.objects.create(titel="Rituale", attribut=attrs["MA"], limit="m", gruppe="j", impro_possible=False)
    Fertigkeit.objects.create(titel="Askennen", attribut=attrs["MA"], limit="g", gruppe="j", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Manipulation", attribut=attrs["WK"], limit="m", gruppe="k", impro_possible=False)
    Fertigkeit.objects.create(titel="Dunkelmagie", attribut=attrs["MA"], limit="m", gruppe="k", impro_possible=False)
    Fertigkeit.objects.create(titel="Markovs Augen", attribut=attrs["MA"], limit="m", gruppe="k", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Antimagie", attribut=attrs["MA"], limit="m", gruppe="l", impro_possible=False)
    Fertigkeit.objects.create(titel="Auromantik", attribut=attrs["MA"], limit="m", gruppe="l", impro_possible=False)
    Fertigkeit.objects.create(titel="Göttermagie", attribut=attrs["MA"], limit="m", gruppe="l", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Wesenkräfte", attribut=attrs["ST"], limit="m", gruppe="m")
    Fertigkeit.objects.create(titel="Wesenmagie", attribut=attrs["MA"], limit="-", gruppe="m")
    Fertigkeit.objects.create(titel="Fliegen", attribut=attrs["SCH"], limit="k", gruppe="m", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Zielen", attribut=attrs["GES"], limit="k", gruppe="n", impro_possible=False)
    Fertigkeit.objects.create(titel="Pistolen", attribut=attrs["F"], limit="k", gruppe="n", impro_possible=False)
    Fertigkeit.objects.create(titel="Bögen", attribut=attrs["F"], limit="k", gruppe="n", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Geschütze", attribut=attrs["F"], limit="k", gruppe="o", impro_possible=False)
    Fertigkeit.objects.create(titel="Exotische F.-Waffen", attribut=attrs["F"], limit="k", gruppe="o", impro_possible=False)
    Fertigkeit.objects.create(titel="Gewehre", attribut=attrs["F"], limit="k", gruppe="o", impro_possible=False)
    
    Fertigkeit.objects.create(titel="Einschüchtern", attribut=attrs["UM"], limit="g", gruppe="p")
    Fertigkeit.objects.create(titel="Waffenloser Kampf", attribut=attrs["N"], limit="k", gruppe="p")
    Fertigkeit.objects.create(titel="Impro-Waffen", attribut=attrs["N"], limit="k", gruppe="p")
    
    Fertigkeit.objects.create(titel="Kampfkunst", attribut=attrs["N"], limit="k", gruppe="q", impro_possible=False)
    Fertigkeit.objects.create(titel="Klingen", attribut=attrs["N"], limit="k", gruppe="q", impro_possible=False)
    Fertigkeit.objects.create(titel="N.-Waffen", attribut=attrs["N"], limit="k", gruppe="q", impro_possible=False)



class Migration(migrations.Migration):

    dependencies = [
        ('character', '0134a_remove_fertigkeit_attr1_remove_fertigkeit_attr2_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_non_wesen),
        migrations.RunPython(remove_all_chars),
        migrations.RunPython(remove_all_ferts),
        migrations.RunPython(add_some_attrs),
        migrations.RunPython(add_ferts),
    ]
