# Generated by Django 4.1.7 on 2023-09-10 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0137_remove_charakter_ep_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='alter',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='geschlecht',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='gewicht',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewicht in kg'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='größe',
            field=models.PositiveIntegerField(null=True, verbose_name='Größe in cm'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='präf_arm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='präferierter Arm (rechts/links?)'),
        ),
    ]
