# Generated by Django 4.1.7 on 2023-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0139_rename_spezies_wesen_delete_relspezies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='ep_stufe',
            field=models.PositiveIntegerField(default=0, verbose_name='aktuelle Stufe des Charakters'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='ep_stufe_in_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Stufe des Charakters, die noch verteilt werden muss'),
        ),
    ]
