# Generated by Django 4.1.7 on 2023-10-14 15:55

from django.db import migrations


def flatten_concatenation(matrix):
    flat_list = []
    for row in matrix:
        flat_list += row
    return flat_list

def add_auth_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group, _ = Group.objects.get_or_create(name="trägt seine chars ein")

    models = [
        "relpersönlichkeit",
        "relwesenkraft",
        "relattribut",
        "relgruppe",
        "relfertigkeit",
        "relspezialfertigkeit",
        "relwissensfertigkeit",
        "relvorteil",
        "relnachteil",
        "reltalent",
        "affektivität",
        "relgfsability",

        "relitem",
        "relwaffen_werkzeuge",
        "relmagazin",
        "relpfeil_bolzen",
        "relschusswaffen",
        "relmagische_ausrüstung",
        "relrituale_runen",
        "relrüstung",
        "relausrüstung_technik",
        "relfahrzeug",
        "releinbauten",
        "relzauber",
        "relvergessenerzauber",
        "relalchemie",
        "reltinker",
        "relbegleiter",
        "relengelsroboter",
        "charakter"
    ]
    permission_codenames = flatten_concatenation([[f"view_{m}", f"add_{m}", f"change_{m}", f"delete_{m}"] for m in models])
    permissions = Permission.objects.filter(codename__in=permission_codenames)
    group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0140_alter_charakter_ep_stufe_and_more'),
    ]

    operations = [
        migrations.RunPython(add_auth_group),
    ]
