# Generated by Django 4.2.8 on 2024-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0146_remove_nachteil_needs_implementation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsability',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
    ]
