# Generated by Django 4.2.8 on 2024-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0151_charakter_rüstung_haltbarkeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='astralwiderstand_pro_erfolg_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
