# Generated by Django 4.2.8 on 2024-10-28 13:37

import django.core.validators
from django.db import migrations, models

def character_stufe_min_1(apps, schema_editor):
    Charakter = apps.get_model('character', 'Charakter')
    Charakter.objects.filter(ep_stufe=0).update(ep_stufe=1)
    Charakter.objects.filter(ep_stufe_in_progress=0).update(ep_stufe_in_progress=1)


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0157_klasseability_relklasseability_klassestufenplan'),
    ]

    operations = [
        migrations.RunPython(character_stufe_min_1),
        migrations.AlterField(
            model_name='charakter',
            name='ep_stufe',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='aktuelle Stufe des Charakters'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='ep_stufe_in_progress',
            field=models.PositiveIntegerField(default=1, verbose_name='Stufe des Charakters, die noch verteilt werden muss'),
        ),
    ]
