# Generated by Django 4.2.8 on 2024-10-28 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0158_alter_charakter_ep_stufe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='alter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='augenfarbe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='ep_stufe_in_progress',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stufe des Charakters, die noch verteilt werden muss'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='geschlecht',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='gewicht',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewicht in kg'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='größe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Größe in cm'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='haarfarbe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='hautfarbe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
