# Generated by Django 4.2.8 on 2024-10-28 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0159_alter_charakter_alter_alter_charakter_augenfarbe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gfsstufenplanbase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gfsstufenplanbase',
            name='stufe',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
