# Generated by Django 4.2.8 on 2024-10-30 11:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0161_remove_instance_stufe_1_gfsstufenplanbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to=''),
        ),
    ]
