# Generated by Django 4.2.8 on 2024-10-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0162_klasse_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charakter',
            old_name='persönlichkeit',
            new_name='persönlichkeit_old',
        ),
    ]
