# Generated by Django 4.2.8 on 2024-10-30 16:28

from django.db import migrations, models
import django.db.models.deletion

def copy_persönlichkeit(apps, schema_editor):
    Charakter = apps.get_model('character', 'Charakter')
    chars = []
    for char in Charakter.objects.all():
        char.persönlichkeit = char.persönlichkeit_old.first()
        chars.append(char)
    Charakter.objects.bulk_update(chars, ["persönlichkeit"])


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0163_rename_persönlichkeit_charakter_persönlichkeit_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='persönlichkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.persönlichkeit'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='persönlichkeit_old',
            field=models.ManyToManyField(blank=True, related_name='persönlichkeit_old', to='character.persönlichkeit'),
        ),
        migrations.RunPython(copy_persönlichkeit)
    ]
