# Generated by Django 4.2.8 on 2024-11-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0170_klasse_base_abilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persönlichkeit',
            old_name='positiv',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='persönlichkeit',
            old_name='negativ',
            new_name='charakterbeispiele',
        ),
    ]
