# Generated by Django 4.2.8 on 2024-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0171_rename_positiv_persönlichkeit_beschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persönlichkeit',
            name='titel',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
