# Generated by Django 4.2.8 on 2024-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0172_alter_persönlichkeit_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='gruppen',
            field=models.ManyToManyField(blank=True, to='character.relgruppe'),
        ),
    ]
