# Generated by Django 4.2.8 on 2024-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0173_charakter_gruppen'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='affektivitäten',
            field=models.ManyToManyField(blank=True, to='character.affektivität'),
        ),
    ]
