# Generated by Django 4.2.8 on 2025-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0179_alter_gfswesenkraft_options_tag_charakter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='tags',
            field=models.ManyToManyField(blank=True, to='character.tag'),
        ),
    ]
