# Generated by Django 4.2.8 on 2025-11-15 16:59

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0184_alter_relramsch_anz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to='', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='gfs',
            name='eigenschaften',
            field=models.ManyToManyField(blank=True, to='character.gfseigenschaft'),
        ),
        migrations.CreateModel(
            name='CurrentStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField(blank=True, null=True)),
                ('notes', markdownfield.models.MarkdownField(rendered_field='notes_rendered')),
                ('notes_rendered', markdownfield.models.RenderedMarkdownField(null=True)),
                ('mana', models.SmallIntegerField(blank=True, null=True)),
                ('konz', models.SmallIntegerField(blank=True, null=True)),
                ('gHP', models.SmallIntegerField(blank=True, null=True)),
                ('kHP', models.SmallIntegerField(blank=True, null=True)),
                ('char', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
            ],
            options={
                'ordering': ['char'],
            },
        ),
    ]
