# Generated by Django 4.2.8 on 2025-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0186_remove_currentstory_notes_rendered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
    ]
