# Generated by Django 4.2.8 on 2025-11-16 12:04

from django.db import migrations

def add_cards_for_all_chars(apps, schema_editor):
    Charakter = apps.get_model('character', 'Charakter')
    Card = apps.get_model('cards', 'Card')

    Card.objects.bulk_create(
        [Card(char=char, money=char._geld, active=True) for char in Charakter.objects.all()]
    )
        

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0187_alter_currentstory_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charakter',
            old_name='geld',
            new_name='_geld',
        ),
        migrations.RunPython(add_cards_for_all_chars)
    ]
