# Generated by Django 4.2.8 on 2025-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0189_remove_charakter__geld'),
    ]

    operations = [
        migrations.AddField(
            model_name='relzauber',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
