# Generated by Django 4.2.8 on 2025-11-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0188_rename_geld_charakter__geld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='_geld',
        ),
    ]
