# Generated by Django 4.2.8 on 2025-11-16 13:51

from django.db import migrations

def make_all_relzauber_learned(apps, schema_editor):
    RelZauber = apps.get_model('character', 'RelZauber')
    RelZauber.objects.all().update(learned=True)

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0190_relzauber_learned'),
    ]

    operations = [
        migrations.RunPython(make_all_relzauber_learned)
    ]
