# Generated by Django 4.2.8 on 2025-12-06 11:32

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion

def rm_status_mitarbeiter_from_non_spielleitung(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.exclude(groups__name="Spielleitung").update(is_staff=False)

def assign_user_to_spieler(apps, schema_editor):
    Spieler = apps.get_model('character', 'Spieler')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    instances = []
    for sp in Spieler.objects.all():
        sp.user = User.objects.get(username=sp.name)
        instances.append(sp)
    Spieler.objects.bulk_update(instances, fields=["user"])

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0192_charakter_no_ma_charakter_no_ma_mg'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='no_MA',
            field=models.BooleanField(default=False, verbose_name='Managetik können, aber für immer auf Magie verzichten'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='no_MA_MG',
            field=models.BooleanField(default=False, verbose_name='Für immer auf Magie und Managetik verzichten'),
        ),
        migrations.RunPython(rm_status_mitarbeiter_from_non_spielleitung),
        migrations.RunPython(assign_user_to_spieler),
    ]
