# Generated by Django 4.2.8 on 2025-12-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0194_alter_spieler_options_remove_spieler_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spieler',
            options={'ordering': ['user'], 'permissions': [('is_LARPler', 'nimmt am LARP teil'), ('is_Spielleitung', 'leitet PnP-Runden und übernimmt Admin-Zeugs'), ('copies_chars', 'überträgt alte Charaktere ohne Erstellung'), ('sees_TODOcalendar', "sieht Lilly's Kalender")], 'verbose_name_plural': 'Spieler'},
        ),
    ]
