# Generated by Django 4.2.8 on 2025-12-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0195_alter_spieler_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klasse',
            name='beschreibung',
        ),
        migrations.RemoveField(
            model_name='klasse',
            name='icon',
        ),
    ]
