# Generated by Django 4.2.27 on 2025-12-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_rüstung_remove_rüstungen_firmen_and_more'),
        ('character', '0196_remove_klasse_beschreibung_remove_klasse_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='rüstungen',
            field=models.ManyToManyField(blank=True, through='character.RelRüstung', to='shop.rüstung'),
        ),
        migrations.AlterField(
            model_name='relrüstung',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rüstung'),
        ),
    ]
