# Generated by Django 4.1.7 on 2023-11-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='evolutionPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_pre', related_query_name='evolution_pre', to='dex.monster'),
        ),
        migrations.RemoveField(
            model_name='monster',
            name='evolutionPre',
        ),
        migrations.AddField(
            model_name='monster',
            name='evolutionPre',
            field=models.ManyToManyField(blank=True, related_name='evolution_post', related_query_name='evolution_post', to='dex.monster'),
        ),
    ]
