# Generated by Django 4.1.7 on 2023-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0002_alter_monster_evolutionpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='evolutionPost',
        ),
        migrations.AlterField(
            model_name='monster',
            name='evolutionPre',
            field=models.ManyToManyField(blank=True, related_name='evolution_pre', related_query_name='evolution_pre', to='dex.monster'),
        ),
        migrations.AddField(
            model_name='monster',
            name='evolutionPost',
            field=models.ManyToManyField(blank=True, related_name='evolution_post', related_query_name='evolution_post', to='dex.monster'),
        ),
    ]
