# Generated by Django 4.1.7 on 2023-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0003_fertigkeit_geschöpf_paratier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paratierfertigkeit',
            options={'ordering': ['tier', 'fertigkeit'], 'verbose_name': 'Fertigkeit (Para-Tier)', 'verbose_name_plural': 'Fertigkeiten (Para-Tier)'},
        ),
        migrations.AddField(
            model_name='fertigkeit',
            name='name',
            field=models.CharField(default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
