# Generated by Django 4.1.7 on 2023-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0007_monsterfähigkeit_alter_attacke_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsterfähigkeit',
            options={'ordering': ['name'], 'verbose_name': 'Fähigkeit', 'verbose_name_plural': 'Fähigkeiten'},
        ),
        migrations.AddField(
            model_name='monster',
            name='fähigkeiten',
            field=models.ManyToManyField(to='dex.monsterfähigkeit'),
        ),
    ]
