# Generated by Django 4.1.7 on 2023-12-16 12:50

import colorfield.fields
import dex.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0010_typ_color_typ_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='base_attackbonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='base_reaktionsbonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typ',
            name='color',
            field=colorfield.fields.ColorField(default='#B19071', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='typ',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[256, 256], upload_to=dex.models.upload_and_rename_to_id),
        ),
        migrations.AlterField(
            model_name='typ',
            name='text_color',
            field=colorfield.fields.ColorField(default='#070707', image_field=None, max_length=25, samples=None),
        ),
    ]
