# Generated by Django 4.1.7 on 2023-12-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0142_charakter_manaoverflow_bonus'),
        ('dex', '0015_correct_dice_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpielerMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rang', models.SmallIntegerField()),
                ('attacken', models.ManyToManyField(to='dex.attacke')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.monster')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Spieler-Monster',
                'verbose_name_plural': 'Spieler-Monster',
                'ordering': ['spieler', 'name', 'monster'],
            },
        ),
    ]
