# Generated by Django 4.1.7 on 2023-12-18 20:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0142_charakter_manaoverflow_bonus'),
        ('dex', '0017_alter_spielermonster_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spielermonster',
            options={'ordering': ['spieler', 'monster', 'name'], 'verbose_name': 'Spieler-Monster', 'verbose_name_plural': 'Spieler-Monster'},
        ),
        migrations.CreateModel(
            name='MonsterTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farbe', colorfield.fields.ColorField(blank=True, default='#0000FF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=256)),
                ('monster', models.ManyToManyField(to='dex.monster')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Monster-Team',
                'verbose_name_plural': 'Monster-Teams',
                'ordering': ['spieler', 'name'],
            },
        ),
    ]
