# Generated by Django 4.1.7 on 2023-12-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0018_alter_spielermonster_options_monsterteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterteam',
            name='monster',
            field=models.ManyToManyField(to='dex.spielermonster'),
        ),
    ]
