# Generated by Django 4.1.7 on 2023-12-18 21:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0019_alter_monsterteam_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterteam',
            name='textfarbe',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
