# Generated by Django 4.1.7 on 2023-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0022_remove_monsterteam_gefangen_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterteam',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
