# Generated by Django 4.2.8 on 2023-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0024_remove_monsterrang_hp_monster_base_fernkampf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='base_initiative',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rangstat',
            name='stat',
            field=models.CharField(choices=[('INI', 'Initiative'), ('HP', 'HP'), ('N', 'Nahkampf'), ('F', 'Fernkampf'), ('MA', 'Magie'), ('VER_G', 'Verteidigung geistig'), ('VER_K', 'Verteidigung körperlich')], max_length=5),
        ),
    ]
