# Generated by Django 4.2.8 on 2023-12-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0025_monster_base_initiative_alter_rangstat_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacke',
            name='angriff_fernkampf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacke',
            name='angriff_magie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacke',
            name='angriff_nahkampf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacke',
            name='verteidigung_geistig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacke',
            name='verteidigung_körperlich',
            field=models.BooleanField(default=False),
        ),
    ]
