# Generated by Django 4.2.8 on 2023-12-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0028_monsterrang_attackenpunkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielermonster',
            name='attackenpunkte',
            field=models.SmallIntegerField(default=0),
        ),
    ]
