# Generated by Django 4.2.8 on 2023-12-27 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0030_attacke_author_attacke_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschöpf',
            name='initiative',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attacke',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='attacke',
            name='types',
            field=models.ManyToManyField(to='dex.typ', verbose_name='Typen'),
        ),
    ]
