# Generated by Django 4.2.8 on 2023-12-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0031_geschöpf_initiative_alter_attacke_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geschöpf',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative', to='dex.dice'),
        ),
        migrations.AlterField(
            model_name='geschöpf',
            name='schaWI',
            field=models.ManyToManyField(related_name='schadensWI', to='dex.dice'),
        ),
    ]
