# Generated by Django 4.2.8 on 2023-12-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0032_alter_geschöpf_initiative_alter_geschöpf_schawi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geschöpf',
            name='gefahrenklasse',
            field=models.CharField(choices=[('S', 'sicher'), ('B', 'bedenklich'), ('L', 'lethal'), ('H', 'hortend')], default='B'),
        ),
    ]
