# Generated by Django 4.2.8 on 2023-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0142_charakter_manaoverflow_bonus'),
        ('dex', '0034_rename_schawi_geschöpf_schadenswi_geschöpf_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geschöpf',
            options={'ordering': ['number'], 'verbose_name': 'Geschöpf', 'verbose_name_plural': 'Geschöpfe'},
        ),
        migrations.AlterField(
            model_name='geschöpf',
            name='visible',
            field=models.ManyToManyField(blank=True, to='character.spieler'),
        ),
    ]
