# Generated by Django 4.2.8 on 2023-12-29 15:37
from django.db import migrations


def migrate_spMo_attacks(apps, schema_editor):
    SpielerMonster = apps.get_model('dex', 'SpielerMonster')
    SpielerMonsterAttack = apps.get_model('dex', 'SpielerMonsterAttack')

    for sp_mo in SpielerMonster.objects.prefetch_related("monster__types", "attacken_old__types").all():
        for attack in sp_mo.attacken_old.all():
            SpielerMonsterAttack.objects.create(attacke=attack, spieler_monster=sp_mo, cost=attack.cost)


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0037_alter_spielermonster_attacken_old_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_spMo_attacks)
    ]
