# Generated by Django 4.2.8 on 2024-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0039_remove_spielermonster_attacken_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geschöpf',
            name='gefahrenklasse',
            field=models.CharField(choices=[('S', 'sicher'), ('B', 'bedenklich'), ('L', 'letal'), ('H', 'hortend')], default='B'),
        ),
    ]
