# Generated by Django 4.2.8 on 2024-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0143_charakter_sonstiges_alchemie_and_more'),
        ('dex', '0041_attacke_monster_feddich'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapflanze',
            name='visible',
            field=models.ManyToManyField(blank=True, to='character.spieler'),
        ),
    ]
