# Generated by Django 4.1.7 on 2023-03-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0072_remove_profession_talente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('spieler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ['spieler', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=200, unique=True)),
                ('admins', models.ManyToManyField(related_name='admins', to='httpChat.account')),
                ('basic_users', models.ManyToManyField(related_name='basic_users', to='httpChat.account')),
                ('owners', models.ManyToManyField(related_name='owners', to='httpChat.account')),
            ],
            options={
                'verbose_name': 'Chatroom',
                'verbose_name_plural': 'Chatrooms',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='httpChat.account')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpChat.chatroom')),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
                'ordering': ['chatroom', 'created_at'],
            },
        ),
    ]
