# Generated by Django 4.1.7 on 2023-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(default='te', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='titel',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
