# Generated by Django 4.1.7 on 2023-03-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpChat', '0002_account_slug_chatroom_slug_alter_chatroom_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('m', 'Message'), ('i', 'Info')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
