# Generated by Django 4.1.7 on 2023-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpChat', '0003_message_type_alter_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='titel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
