# Generated by Django 4.1.7 on 2023-04-06 11:09

from django.db import migrations, models
import httpChat.models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('httpChat', '0005_remove_chatroom_admins_remove_chatroom_basic_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroomaccount',
            options={'ordering': ['account', 'chatroom'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chatroomaccount',
            name='latest_access',
            field=models.DateTimeField(default=httpChat.models.ancient_datetime),
        ),
        migrations.AlterUniqueTogether(
            name='chatroomaccount',
            unique_together={('account', 'chatroom')},
        ),
    ]
