# Generated by Django 4.1.7 on 2023-04-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('httpChat', '0004_remove_chatroom_slug_alter_chatroom_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='basic_users',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='owners',
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(to='httpChat.account'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='httpChat.account'),
        ),
        migrations.CreateModel(
            name='ChatroomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_access', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpChat.account')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpChat.chatroom')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='accounts',
            field=models.ManyToManyField(through='httpChat.ChatroomAccount', to='httpChat.account'),
        ),
    ]
