# Generated by Django 2.0.5 on 2018-11-19 18:30

import character.models
import datetime, random, string
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def rand_str():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(10))

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affektivität',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wert', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-200), django.core.validators.MaxValueValidator(200)])),
                ('grad', models.CharField(max_length=60)),
                ('umgang', models.IntegerField(default=0)),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Affektivität',
                'verbose_name_plural': 'Affektivitäten',
                'ordering': ['char', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=3, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attribute',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Begleiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Begleiter',
                'verbose_name_plural': 'Begleiter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Charakter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_erstellung', models.BooleanField(default=True)),
                ('ep_system', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default=rand_str, max_length=200, unique=True)),
                ('manifest', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Startmanifest')),
                ('sonstiger_manifestverlust', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='sonstiger Manifestverlust')),
                ('notizen_sonstiger_manifestverlust', models.CharField(blank=True, default='', max_length=200)),
                ('gewicht', models.PositiveIntegerField(blank=True, default=75)),
                ('größe', models.PositiveIntegerField(blank=True, default=170)),
                ('alter', models.PositiveIntegerField(blank=True, default=0)),
                ('geschlecht', models.CharField(blank=True, max_length=100)),
                ('sexualität', models.CharField(blank=True, max_length=100)),
                ('präf_arm', models.CharField(blank=True, default='', max_length=100)),
                ('hautfarbe', models.CharField(blank=True, default='', max_length=100)),
                ('haarfarbe', models.CharField(blank=True, default='', max_length=100)),
                ('augenfarbe', models.CharField(blank=True, default='', max_length=100)),
                ('nutzt_magie', models.PositiveSmallIntegerField(blank=True, choices=[(20, 'selten'), (30, 'regelmäßig'), (50, 'häufig')], default=20)),
                ('useEco', models.BooleanField(default=True, verbose_name="benutze 'eco':y, benutze 'morph':n")),
                ('eco', models.PositiveIntegerField(blank=True, default=0)),
                ('morph', models.PositiveIntegerField(blank=True, default=0)),
                ('sp', models.PositiveIntegerField(default=0)),
                ('cp', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cp')),
                ('erhaltene_cp', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('geld', models.IntegerField(default=0)),
                ('HPplus', models.IntegerField(blank=True, default=0)),
                ('HPcp', models.PositiveIntegerField(blank=True, default=0, verbose_name='CP in HP gesteckt')),
                ('wesenschaden_waff_kampf', models.IntegerField(default=0)),
                ('rang', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('notizen', models.TextField(blank=True)),
                ('persönlicheZiele', models.TextField(blank=True)),
                ('sonstige_items', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Charakter',
                'verbose_name_plural': 'Charaktere',
                'ordering': ['eigentümer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, unique=True)),
                ('limit', models.CharField(choices=[('-', 'keins'), ('g', 'geistig'), ('k', 'körperlich'), ('m', 'magisch')], default=('-', 'keins'), max_length=20)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
                ('attr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr1', to='character.Attribut')),
                ('attr2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr2', to='character.Attribut')),
            ],
            options={
                'verbose_name': 'Fertigkeit',
                'verbose_name_plural': 'Fertigkeiten',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nachteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=40)),
                ('cp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Nachteil',
                'verbose_name_plural': 'Nachteile',
            },
        ),
        migrations.CreateModel(
            name='RangRankingEntry',
            fields=[
                ('order', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('ranking', models.CharField(default='Z', max_length=3)),
                ('min_rang', models.CharField(default='0', max_length=10)),
                ('max_rang', models.CharField(default='49', max_length=10)),
                ('survival', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('specials', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RelAttribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuellerWert', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('maxWert', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('fg', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('notizen', models.CharField(blank=True, max_length=200)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Attribut')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attribute',
                'ordering': ['char', 'attribut'],
            },
        ),
        migrations.CreateModel(
            name='RelAusrüstung_Technik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('selbst_eingebaut', models.BooleanField(default=False)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Ausrüstung_Technik')),
            ],
            options={
                'verbose_name': 'Ausrüstung & Technik',
                'verbose_name_plural': 'Ausrüstung & Technik',
            },
        ),
        migrations.CreateModel(
            name='RelBegleiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('zahm', 'zahm'), ('rebellisch', 'rebellisch')], max_length=60)),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
                ('begleiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Begleiter')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Begleiter',
                'verbose_name_plural': 'Begleiter',
                'ordering': ['char', 'begleiter'],
            },
        ),
        migrations.CreateModel(
            name='RelEinbauten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Einbauten')),
            ],
            options={
                'verbose_name': 'Einbauten',
                'verbose_name_plural': 'Einbauten',
            },
        ),
        migrations.CreateModel(
            name='RelFahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
            },
        ),
        migrations.CreateModel(
            name='RelFertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('pool', models.PositiveIntegerField(default=0)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('fertigkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Fertigkeit')),
            ],
            options={
                'verbose_name': 'Fertigkeit',
                'verbose_name_plural': 'Fertigkeiten',
                'ordering': ['char', 'fertigkeit'],
            },
        ),
        migrations.CreateModel(
            name='RelFirmaAusrüstung_Technik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaAusrüstung_Technik')),
            ],
            options={
                'verbose_name': 'Ausrüstung & Technik Verfügbarkeit',
                'verbose_name_plural': 'Ausrüstung & Technik Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaEinbauten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaEinbauten')),
            ],
            options={
                'verbose_name': 'Einbauten Verfügbarkeit',
                'verbose_name_plural': 'Einbauten Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaFahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaFahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug Verfügbarkeit',
                'verbose_name_plural': 'Fahrzeuge Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaItem')),
            ],
            options={
                'verbose_name': 'Item Verfügbarkeit',
                'verbose_name_plural': 'Items Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaMagazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaMagazin')),
            ],
            options={
                'verbose_name': 'Magazin Verfügbarkeit',
                'verbose_name_plural': 'Magazine Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaMagische_Ausrüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaMagische_Ausrüstung')),
            ],
            options={
                'verbose_name': 'magische Ausrüstung Verfügbarkeit',
                'verbose_name_plural': 'magische Ausrüstung Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaPfeil_Bolzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaPfeil_Bolzen')),
            ],
            options={
                'verbose_name': 'Pfeil/Bolzen Verfügbarkeit',
                'verbose_name_plural': 'Pfeile & Bolzen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaRituale_Runen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaRituale_Runen')),
            ],
            options={
                'verbose_name': 'Ritual/Rune Verfügbarkeit',
                'verbose_name_plural': 'Rituale & Runen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaRüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaRüstungen')),
            ],
            options={
                'verbose_name': 'Rüstung Verfügbarkeit',
                'verbose_name_plural': 'Rüstungen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaSchusswaffen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaSchusswaffen')),
            ],
            options={
                'verbose_name': 'Schusswaffe Verfügbarkeit',
                'verbose_name_plural': 'Schusswaffen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStAusrüstung_Technik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStAusrüstung_Technik')),
            ],
            options={
                'verbose_name': 'Ausrüstung/Technik (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Ausrüstung & Technik (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStEinbauten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStEinbauten')),
            ],
            options={
                'verbose_name': 'Einbauten (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Einbauten (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStFahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStFahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Fahrzeuge (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStItem')),
            ],
            options={
                'verbose_name': 'Item (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Items (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStMagazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStMagazin')),
            ],
            options={
                'verbose_name': 'Magazin (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Magazine (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStMagische_Ausrüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStMagische_Ausrüstung')),
            ],
            options={
                'verbose_name': 'magische Ausrüstung (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'magische Ausrüstung (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStPfeil_Bolzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStPfeil_Bolzen')),
            ],
            options={
                'verbose_name': 'Pfeil/Bolzen (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Pfeile & Bolzen (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStRüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStRüstungen')),
            ],
            options={
                'verbose_name': 'Rüstung (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Rüstungen (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStSchusswaffen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStSchusswaffen')),
            ],
            options={
                'verbose_name': 'Schusswaffe (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Schusswaffen (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStWaffen_Werkzeuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStWaffen_Werkzeuge')),
            ],
            options={
                'verbose_name': 'Waffe/Werkzeug (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Waffen & Werkzeuge (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaStZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaStZauber')),
            ],
            options={
                'verbose_name': 'Zauber (stufenabh) Verfügbarkeit',
                'verbose_name_plural': 'Zauber (stufenabh) Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaWaffen_Werkzeuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaWaffen_Werkzeuge')),
            ],
            options={
                'verbose_name': 'Waffe/Werkzeug Verfügbarkeit',
                'verbose_name_plural': 'Waffen & Werkzeuge Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFirmaZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('firma_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FirmaZauber')),
            ],
            options={
                'verbose_name': 'Zauber Verfügbarkeit',
                'verbose_name_plural': 'Zauber Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religionen',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='RelItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='RelMagazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Magazin')),
            ],
            options={
                'verbose_name': 'Magazin',
                'verbose_name_plural': 'Magazine',
            },
        ),
        migrations.CreateModel(
            name='RelMagische_Ausrüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Magische_Ausrüstung')),
            ],
            options={
                'verbose_name': 'magische Ausrüstung',
                'verbose_name_plural': 'magische Ausrüstung',
            },
        ),
        migrations.CreateModel(
            name='RelNachteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, max_length=100, null=True)),
                ('extra', models.CharField(blank=True, max_length=30, null=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('teil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Nachteil')),
            ],
            options={
                'verbose_name': 'Nachteil',
                'verbose_name_plural': 'Nachteile',
            },
        ),
        migrations.CreateModel(
            name='RelPfeil_Bolzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pfeil_Bolzen')),
            ],
            options={
                'verbose_name': 'Pfeil/Bolzen',
                'verbose_name_plural': 'Pfeile & Bolzen',
            },
        ),
        migrations.CreateModel(
            name='RelRituale_Runen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Rituale_Runen')),
            ],
            options={
                'verbose_name': 'Ritual/Rune',
                'verbose_name_plural': 'Rituale & Runen',
            },
        ),
        migrations.CreateModel(
            name='RelRüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Rüstungen')),
            ],
            options={
                'verbose_name': 'Rüstung',
                'verbose_name_plural': 'Rüstungen',
            },
        ),
        migrations.CreateModel(
            name='RelSchusswaffen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Schusswaffen')),
            ],
            options={
                'verbose_name': 'Schusswaffe',
                'verbose_name_plural': 'Schusswaffen',
            },
        ),
        migrations.CreateModel(
            name='RelSpezialfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesamt', models.PositiveIntegerField(default=0)),
                ('korrektur', models.PositiveIntegerField(default=0)),
                ('stufe', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('w20', models.PositiveIntegerField(blank=True, default=0)),
                ('würfelÜbrig', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Spezialfertigkeit',
                'verbose_name_plural': 'Spezialfertigkeiten',
                'ordering': ['char', 'spezialfertigkeit'],
            },
        ),
        migrations.CreateModel(
            name='RelSpezies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Wesen',
                'verbose_name_plural': 'Wesen',
                'ordering': ['char', 'spezies'],
            },
        ),
        migrations.CreateModel(
            name='RelStAusrüstung_Technik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('selbst_eingebaut', models.BooleanField(default=False)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StAusrüstung_Technik')),
            ],
            options={
                'verbose_name': 'Ausrüstung/Technik (stufenabh)',
                'verbose_name_plural': 'Ausrüstung & Technik (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStEinbauten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StEinbauten')),
            ],
            options={
                'verbose_name': 'Einbauten (stufenabh)',
                'verbose_name_plural': 'Einbauten (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStFahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StFahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug (stufenabh)',
                'verbose_name_plural': 'Fahrzeuge (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StItem')),
            ],
            options={
                'verbose_name': 'Item (stufenabh)',
                'verbose_name_plural': 'Items (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStMagazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StMagazin')),
            ],
            options={
                'verbose_name': 'Magazin (stufenabh)',
                'verbose_name_plural': 'Magazine (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStMagische_Ausrüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StMagische_Ausrüstung')),
            ],
            options={
                'verbose_name': 'magische Ausrüstung (stufenabh)',
                'verbose_name_plural': 'magische Ausrüstung (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStPfeil_Bolzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StPfeil_Bolzen')),
            ],
            options={
                'verbose_name': 'Pfeil/Bolzen (stufenabh)',
                'verbose_name_plural': 'Pfeile & Bolzen (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStRüstung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StRüstungen')),
            ],
            options={
                'verbose_name': 'Rüstung (stufenabh)',
                'verbose_name_plural': 'Rüstungen (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStSchusswaffen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StSchusswaffen')),
            ],
            options={
                'verbose_name': 'Schusswaffe (stufenabh)',
                'verbose_name_plural': 'Schusswaffen (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStWaffen_Werkzeuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StWaffen_Werkzeuge')),
            ],
            options={
                'verbose_name': 'Waffe/Werkzeug (stufenabh)',
                'verbose_name_plural': 'Waffen & Werkzeuge (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelStZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StZauber')),
            ],
            options={
                'verbose_name': 'Zauber (stufenabh)',
                'verbose_name_plural': 'Zauber (stufenabh)',
            },
        ),
        migrations.CreateModel(
            name='RelVorteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, max_length=100, null=True)),
                ('extra', models.CharField(blank=True, max_length=30, null=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Vorteil',
                'verbose_name_plural': 'Vorteile',
            },
        ),
        migrations.CreateModel(
            name='RelWaffen_Werkzeuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Waffen_Werkzeuge')),
            ],
            options={
                'verbose_name': 'Waffe/Werkzeug',
                'verbose_name_plural': 'Waffen & Werkzeuge',
            },
        ),
        migrations.CreateModel(
            name='RelWesenkraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Wesenkraft',
                'verbose_name_plural': 'Wesenkräfte',
                'ordering': ['char', 'wesenkraft'],
            },
        ),
        migrations.CreateModel(
            name='RelWissensfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesamt', models.PositiveIntegerField(default=0)),
                ('w100', models.PositiveIntegerField(default=0)),
                ('würfel2', models.SmallIntegerField(choices=[(4, 'W4'), (6, 'W6'), (8, 'W8'), (10, 'W10'), (12, 'W12'), (20, 'W20'), (100, 'W100')], default=4)),
                ('bonus', models.PositiveIntegerField(default=0)),
                ('schwellwert', models.PositiveIntegerField(default=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
            ],
            options={
                'verbose_name': 'Wissensfertigkeit',
                'verbose_name_plural': 'Wissensfertigkeiten',
                'ordering': ['char', 'wissensfertigkeit'],
            },
        ),
        migrations.CreateModel(
            name='RelZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.PositiveIntegerField(default=1)),
                ('notizen', models.CharField(blank=True, default='', max_length=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Zauber')),
            ],
            options={
                'verbose_name': 'Zauber',
                'verbose_name_plural': 'Zauber',
            },
        ),
        migrations.CreateModel(
            name='SkilltreeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('s', 'Schusswaffen'), ('n', 'N.-Waffen'), ('z', 'Zauber'), ('t', 'Technik'), ('r', 'Rüstung'), ('k', 'Wesenkraft'), ('w', 'Wesen')], max_length=1, null=True)),
                ('stufe', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('sp', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SkilltreeEntryKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('ss', 'Schaden'), ('sm', 'Munition'), ('sp', 'Präzision'), ('sd', 'Durchschlagskraft'), ('sr', 'Reichweite'), ('sb', 'BS'), ('sa', 'Astralschaden'), ('zw', 'Wirkdauer'), ('ze', 'Aufrechterhalten'), ('zc', 'Schwellwert'), ('tp', 'Prozession'), ('tw', 'Wifi'), ('tj', 'Projektion'), ('ts', 'Sicherheit'), ('te', 'Speicher'), ('ru', 'Schutz'), ('rt', 'Stärke'), ('kw', 'Wirkdauer'), ('ke', 'Effekt')], max_length=2, null=True)),
                ('text', models.TextField(max_length=100)),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase')),
            ],
        ),
        migrations.CreateModel(
            name='SkilltreeEntryWesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase')),
            ],
        ),
        migrations.CreateModel(
            name='Spezialfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
                ('attr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribut1', to='character.Attribut')),
                ('attr2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribut2', to='character.Attribut')),
                ('ausgleich', models.ManyToManyField(to='character.Fertigkeit')),
            ],
            options={
                'verbose_name': 'Spezialfertigkeit',
                'verbose_name_plural': 'Spezialfertigkeiten',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Spezies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komplexität', models.PositiveIntegerField(default=0)),
                ('titel', models.CharField(max_length=20, unique=True)),
                ('ap', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('wesenschaden_waff_kampf', models.IntegerField(default=0)),
                ('startmanifest', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Startmanifest')),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Wesen',
                'verbose_name_plural': 'Wesen',
                'ordering': ['komplexität', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='SpeziesAttribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuellerWert', models.PositiveIntegerField(default=0)),
                ('maxWert', models.PositiveIntegerField(default=0)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Attribut')),
                ('spezies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezies')),
            ],
            options={
                'verbose_name': 'Startattribut',
                'verbose_name_plural': 'Startattribute',
                'ordering': ['attribut'],
            },
        ),
        migrations.CreateModel(
            name='SpeziesNachteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
                ('spezies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezies')),
                ('teil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Nachteil')),
            ],
            options={
                'verbose_name': 'Startnachteil',
                'verbose_name_plural': 'Startnachteile',
                'ordering': ['teil'],
            },
        ),
        migrations.CreateModel(
            name='SpeziesVorteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=100)),
                ('spezies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezies')),
            ],
            options={
                'verbose_name': 'Startvorteil',
                'verbose_name_plural': 'Startvorteile',
                'ordering': ['teil'],
            },
        ),
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=200)),
                ('geburtstag', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Spieler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vorteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=40)),
                ('cp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Vorteil',
                'verbose_name_plural': 'Vorteile',
            },
        ),
        migrations.CreateModel(
            name='Wesenkraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=30)),
                ('probe', models.CharField(default='', max_length=200)),
                ('wirkung', models.CharField(default='', max_length=300)),
                ('min_rang', models.PositiveIntegerField(default=0)),
                ('wesen', models.CharField(choices=[('a', 'alle'), ('m', 'magisch'), ('w', 'wesenspezifisch'), ('f', 'manifest < ..')], default='a', max_length=1)),
                ('zusatz_manifest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='zusatz_manifest')),
                ('zusatz_wesenspezifisch', models.ManyToManyField(blank=True, to='character.Spezies')),
            ],
            options={
                'verbose_name': 'Wesenkraft',
                'verbose_name_plural': 'Wesenkräfte',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Wissensfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=100)),
                ('attr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a1', to='character.Attribut')),
                ('attr2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a2', to='character.Attribut')),
                ('attr3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3', to='character.Attribut')),
                ('fertigkeit', models.ManyToManyField(to='character.Fertigkeit')),
            ],
            options={
                'verbose_name': 'Wissensfertigkeit',
                'verbose_name_plural': 'Wissensfertigkeiten',
                'ordering': ['titel'],
            },
        ),
        migrations.AddField(
            model_name='speziesvorteil',
            name='teil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Vorteil'),
        ),
        migrations.AddField(
            model_name='spezies',
            name='attribute',
            field=models.ManyToManyField(through='character.SpeziesAttribut', to='character.Attribut'),
        ),
        migrations.AddField(
            model_name='spezies',
            name='nachteile',
            field=models.ManyToManyField(blank=True, through='character.SpeziesNachteil', to='character.Nachteil'),
        ),
        migrations.AddField(
            model_name='spezies',
            name='vorteile',
            field=models.ManyToManyField(blank=True, through='character.SpeziesVorteil', to='character.Vorteil'),
        ),
        migrations.AddField(
            model_name='skilltreeentrywesen',
            name='wesen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spezies'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltreebase',
            unique_together={('kind', 'stufe')},
        ),
        migrations.AddField(
            model_name='relwissensfertigkeit',
            name='wissensfertigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Wissensfertigkeit'),
        ),
        migrations.AddField(
            model_name='relwesenkraft',
            name='wesenkraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Wesenkraft'),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='teil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Vorteil'),
        ),
        migrations.AddField(
            model_name='relspezies',
            name='spezies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wesen', to='character.Spezies'),
        ),
        migrations.AddField(
            model_name='relspezialfertigkeit',
            name='spezialfertigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezialfertigkeit'),
        ),
        migrations.AlterUniqueTogether(
            name='religion',
            unique_together={('titel', 'beschreibung')},
        ),
        migrations.AddField(
            model_name='charakter',
            name='attribute',
            field=models.ManyToManyField(blank=True, through='character.RelAttribut', to='character.Attribut'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='ausrüstungTechnik',
            field=models.ManyToManyField(blank=True, through='character.RelAusrüstung_Technik', to='shop.Ausrüstung_Technik'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='begleiter',
            field=models.ManyToManyField(blank=True, through='character.RelBegleiter', to='character.Begleiter'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='beruf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Beruf'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='eigentümer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spieler'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='einbauten',
            field=models.ManyToManyField(blank=True, through='character.RelEinbauten', to='shop.Einbauten'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='fahrzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelFahrzeug', to='shop.Fahrzeug'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='fertigkeiten',
            field=models.ManyToManyField(blank=True, through='character.RelFertigkeit', to='character.Fertigkeit'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='items',
            field=models.ManyToManyField(blank=True, through='character.RelItem', to='shop.Item'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='magazine',
            field=models.ManyToManyField(blank=True, through='character.RelMagazin', to='shop.Magazin'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='magischeAusrüstung',
            field=models.ManyToManyField(blank=True, through='character.RelMagische_Ausrüstung', to='shop.Magische_Ausrüstung'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='nachteile',
            field=models.ManyToManyField(blank=True, through='character.RelNachteil', to='character.Nachteil'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Religion'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='rituale_runen',
            field=models.ManyToManyField(blank=True, through='character.RelRituale_Runen', to='shop.Rituale_Runen'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='rüstungen',
            field=models.ManyToManyField(blank=True, through='character.RelRüstung', to='shop.Rüstungen'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='schusswaffen',
            field=models.ManyToManyField(blank=True, through='character.RelSchusswaffen', to='shop.Schusswaffen'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='spezialfertigkeiten',
            field=models.ManyToManyField(blank=True, through='character.RelSpezialfertigkeit', to='character.Spezialfertigkeit'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='spezies',
            field=models.ManyToManyField(related_name='wesen', through='character.RelSpezies', to='character.Spezies'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_ausrüstungTechnik',
            field=models.ManyToManyField(blank=True, through='character.RelStAusrüstung_Technik', to='shop.StAusrüstung_Technik'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_einbauten',
            field=models.ManyToManyField(blank=True, through='character.RelStEinbauten', to='shop.StEinbauten'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_fahrzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelStFahrzeug', to='shop.StFahrzeug'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_items',
            field=models.ManyToManyField(blank=True, through='character.RelStItem', to='shop.StItem'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_magazine',
            field=models.ManyToManyField(blank=True, through='character.RelStMagazin', to='shop.StMagazin'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_magischeAusrüstung',
            field=models.ManyToManyField(blank=True, through='character.RelStMagische_Ausrüstung', to='shop.StMagische_Ausrüstung'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_rüstungen',
            field=models.ManyToManyField(blank=True, through='character.RelStRüstung', to='shop.StRüstungen'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_schusswaffen',
            field=models.ManyToManyField(blank=True, through='character.RelStSchusswaffen', to='shop.StSchusswaffen'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_waffenWerkzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelStWaffen_Werkzeuge', to='shop.StWaffen_Werkzeuge'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='st_zauber',
            field=models.ManyToManyField(blank=True, through='character.RelStZauber', to='shop.StZauber'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='verwandlungen',
            field=models.ManyToManyField(blank=True, related_name='verwandlungen', to='character.Spezies'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='vorteile',
            field=models.ManyToManyField(blank=True, through='character.RelVorteil', to='character.Vorteil'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='waffenWerkzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelWaffen_Werkzeuge', to='shop.Waffen_Werkzeuge'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='wesenkräfte',
            field=models.ManyToManyField(blank=True, through='character.RelWesenkraft', to='character.Wesenkraft'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='wissensfertigkeiten',
            field=models.ManyToManyField(blank=True, through='character.RelWissensfertigkeit', to='character.Wissensfertigkeit'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='zauber',
            field=models.ManyToManyField(blank=True, through='character.RelZauber', to='shop.Zauber'),
        ),
        migrations.AddField(
            model_name='affektivität',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter'),
        ),
        migrations.AlterUniqueTogether(
            name='speziesvorteil',
            unique_together={('teil', 'spezies', 'notizen')},
        ),
        migrations.AlterUniqueTogether(
            name='speziesnachteil',
            unique_together={('teil', 'spezies', 'notizen')},
        ),
        migrations.AlterUniqueTogether(
            name='speziesattribut',
            unique_together={('attribut', 'spezies')},
        ),
        migrations.AlterUniqueTogether(
            name='skilltreeentrywesen',
            unique_together={('context', 'wesen')},
        ),
        migrations.AlterUniqueTogether(
            name='skilltreeentrykategorie',
            unique_together={('context', 'kategorie')},
        ),
        migrations.AlterUniqueTogether(
            name='relwissensfertigkeit',
            unique_together={('char', 'wissensfertigkeit')},
        ),
        migrations.AlterUniqueTogether(
            name='relwesenkraft',
            unique_together={('char', 'wesenkraft')},
        ),
        migrations.AlterUniqueTogether(
            name='relspezies',
            unique_together={('char', 'spezies')},
        ),
        migrations.AlterUniqueTogether(
            name='relspezialfertigkeit',
            unique_together={('char', 'spezialfertigkeit')},
        ),
        migrations.AlterUniqueTogether(
            name='relfertigkeit',
            unique_together={('char', 'fertigkeit')},
        ),
        migrations.AlterUniqueTogether(
            name='relbegleiter',
            unique_together={('char', 'begleiter')},
        ),
        migrations.AlterUniqueTogether(
            name='relattribut',
            unique_together={('char', 'attribut')},
        ),
        migrations.AlterUniqueTogether(
            name='affektivität',
            unique_together={('char', 'name')},
        ),
    ]
