# Generated by Django 2.0.5 on 2018-11-20 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20181119_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreebase',
            name='stufe',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='skilltreeentrykategorie',
            name='kategorie',
            field=models.CharField(choices=[('ss', 'Schaden'), ('sm', 'Munition'), ('sp', 'Präzision'), ('sd', 'Durchschlagskraft'), ('sr', 'Reichweite'), ('sb', 'BS'), ('zs', 'Wirkung'), ('sa', 'Astralschaden'), ('zw', 'Wirkdauer'), ('ze', 'Aufrechterhalten'), ('zc', 'Schwellwert'), ('tp', 'Prozession'), ('tw', 'Wifi'), ('tj', 'Projektion'), ('ts', 'Sicherheit'), ('te', 'Speicher'), ('ru', 'Schutz'), ('rt', 'Stärke'), ('kw', 'Wirkdauer'), ('ke', 'Effekt')], max_length=2, null=True),
        ),
    ]
