# Generated by Django 2.0.5 on 2018-12-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20181208_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stufenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveIntegerField(default=0)),
                ('ep', models.PositiveIntegerField(default=0)),
                ('ap', models.PositiveSmallIntegerField(default=0)),
                ('ap_max', models.PositiveSmallIntegerField(default=0)),
                ('fp', models.PositiveSmallIntegerField(default=0)),
                ('fg', models.PositiveSmallIntegerField(default=0)),
                ('zauber', models.PositiveSmallIntegerField(default=0)),
                ('spezial', models.PositiveSmallIntegerField(default=0)),
                ('wissensp', models.PositiveSmallIntegerField(default=0)),
                ('weiteres', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('vorteile', models.ManyToManyField(blank=True, to='character.Vorteil')),
            ],
            options={
                'verbose_name': 'Stufenplan',
                'verbose_name_plural': 'Stufenpläne',
                'ordering': ['wesen', 'stufe'],
            },
        ),
        migrations.AddField(
            model_name='charakter',
            name='wesenschaden_andere_gestalt',
            field=models.IntegerField(blank=True, null=True, verbose_name='BS andere Gestalt'),
        ),
        migrations.AddField(
            model_name='spezies',
            name='wesenschaden_andere_gestalt',
            field=models.IntegerField(blank=True, null=True, verbose_name='BS andere Gestalt'),
        ),
        migrations.AlterField(
            model_name='spezies',
            name='beschreibung',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='spezies',
            name='wesenschaden_waff_kampf',
            field=models.IntegerField(default=0, verbose_name='BS'),
        ),
        migrations.AddField(
            model_name='stufenplan',
            name='wesen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezies'),
        ),
        migrations.AddField(
            model_name='stufenplan',
            name='wesenkräfte',
            field=models.ManyToManyField(blank=True, to='character.Wesenkraft'),
        ),
        migrations.AlterUniqueTogether(
            name='stufenplan',
            unique_together={('wesen', 'stufe')},
        ),
    ]
