# Generated by Django 2.0.5 on 2019-03-11 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_auto_20190126_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='HPplus_fix',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='aktuellerWert_fix',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='maxWert_fix',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='relnachteil',
            name='in_story_erworben',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='in_story_erworben',
            field=models.BooleanField(default=False),
        ),
    ]
