# Generated by Django 2.0.5 on 2019-04-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20190321_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='p_quiz_points_achieved',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
