# Generated by Django 2.0.5 on 2019-04-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_spieler_p_quiz_points_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='quiz_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='quiz_points_achieved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
