# Generated by Django 2.2.13 on 2020-07-30 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_auto_20200730_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nachteil',
            old_name='cp',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='vorteil',
            old_name='cp',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='HPcp',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='erhaltene_cp',
        ),
        migrations.AddField(
            model_name='charakter',
            name='ip',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='tp',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tp'),
        ),
    ]
