# Generated by Django 2.2.13 on 2020-07-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0021_auto_20200731_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionstufenplan',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession'),
        ),
        migrations.CreateModel(
            name='ProfessionFertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.IntegerField(default=0)),
                ('pool', models.IntegerField(default=0)),
                ('fertigkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Fertigkeit')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Profession')),
            ],
            options={
                'unique_together': {('profession', 'fertigkeit')},
                'ordering': ['profession', 'fertigkeit'],
                'verbose_name_plural': 'Fertigkeiten',
                'verbose_name': 'Fertigkeit',
            },
        ),
    ]
