# Generated by Django 2.2.13 on 2020-07-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0023_auto_20200731_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreebase',
            name='kind',
            field=models.CharField(choices=[('s', 'Schusswaffen'), ('n', 'N.-Waffen'), ('z', 'Zauber'), ('t', 'Technik'), ('r', 'Rüstung'), ('k', 'Wesenkraft'), ('w', 'Wesen'), ('g', 'Gfs'), ('p', 'Professionen')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='SkilltreeEntryProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Profession')),
            ],
            options={
                'unique_together': {('context', 'profession')},
            },
        ),
        migrations.CreateModel(
            name='SkilltreeEntryGfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.SkilltreeBase')),
                ('gfs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Gfs')),
            ],
            options={
                'unique_together': {('context', 'gfs')},
            },
        ),
    ]
