# Generated by Django 2.2.14 on 2020-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_auto_20200802_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='tp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
