# Generated by Django 2.2.14 on 2020-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0030_talent_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfs',
            name='titel',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='titel',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
