# Generated by Django 2.2.14 on 2020-08-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0030_auto_20200810_2332'),
        ('character', '0033_auto_20200805_1734'),
    ]

    operations = [
    ]
