# Generated by Django 2.2.13 on 2020-08-11 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0034_merge_20200810_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='ep_rang',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='aktuellerWert_fix',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='maxWert_fix',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='notizen',
        ),
        migrations.RemoveField(
            model_name='relfertigkeit',
            name='notizen',
        ),
        migrations.RemoveField(
            model_name='relfertigkeit',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='relspezies',
            name='notizen',
        ),
        migrations.AddField(
            model_name='charakter',
            name='gfs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Gfs'),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='aktuell_bonus',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='max_bonus',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='relfertigkeit',
            name='fp_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relspezialfertigkeit',
            name='pool',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='ip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='tp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relfertigkeit',
            name='fp',
            field=models.IntegerField(default=0),
        ),
    ]
