# Generated by Django 2.2.13 on 2020-08-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0038_charakter_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relattribut',
            name='aktuell_bonus',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='max_bonus',
        ),
        migrations.AddField(
            model_name='relattribut',
            name='aktuellerWert_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='fg_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relattribut',
            name='maxWert_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relattribut',
            name='aktuellerWert',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relattribut',
            name='fg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relattribut',
            name='maxWert',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
