# Generated by Django 2.2.13 on 2020-08-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0039_auto_20200812_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Talent')),
            ],
            options={
                'verbose_name_plural': 'Talente',
                'ordering': ['char', 'talent'],
                'unique_together': {('char', 'talent')},
                'verbose_name': 'Talent',
            },
        ),
        migrations.AddField(
            model_name='charakter',
            name='talente',
            field=models.ManyToManyField(blank=True, through='character.RelTalent', to='character.Talent'),
        ),
    ]
