# Generated by Django 2.2.13 on 2020-08-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0040_auto_20200813_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relwesenkraft',
            name='notizen',
        ),
    ]
