# Generated by Django 2.2.13 on 2020-08-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0045_talent_kategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relwissensfertigkeit',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='relwissensfertigkeit',
            name='gesamt',
        ),
        migrations.RemoveField(
            model_name='relwissensfertigkeit',
            name='schwellwert',
        ),
        migrations.RemoveField(
            model_name='relwissensfertigkeit',
            name='w100',
        ),
    ]
