# Generated by Django 2.2.14 on 2020-08-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0046_auto_20200827_1601'),
        ('character', '0047_auto_20200826_2252'),
    ]

    operations = [
    ]
