# Generated by Django 2.2.13 on 2020-09-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0049_remove_spieler_p_quiz_points_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spieler',
            name='quiz_points',
        ),
        migrations.RemoveField(
            model_name='spieler',
            name='quiz_points_achieved',
        ),
    ]
