# Generated by Django 2.2.13 on 2020-09-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0051_charakter_larp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Profession'),
        ),
    ]
