# Generated by Django 2.2.13 on 2020-12-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0053_auto_20201130_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relspezialfertigkeit',
            name='gesamt',
        ),
        migrations.RemoveField(
            model_name='relspezialfertigkeit',
            name='korrektur',
        ),
        migrations.RemoveField(
            model_name='relspezialfertigkeit',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='relspezialfertigkeit',
            name='w20',
        ),
        migrations.RemoveField(
            model_name='relspezialfertigkeit',
            name='würfelÜbrig',
        ),
    ]
