# Generated by Django 3.1.7 on 2022-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0063_relpersönlichkeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsstufenplanbase',
            name='tp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
