# Generated by Django 4.1.7 on 2023-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0065_remove_gfsstufenplan_weiteres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsstufenplan',
            name='special_ability',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Fertigkeit'),
        ),
        migrations.AlterField(
            model_name='gfsstufenplan',
            name='special_ability_description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
    ]
