# Generated by Django 4.1.7 on 2023-03-17 18:32

from django.db import migrations

def migrate_to_product_model(apps, schema_editor):
    GfsStufenplan = apps.get_model('character', 'GfsStufenplan')

    for st in GfsStufenplan.objects.all():
        if st.special_ability_description:
            st.special_ability = st.special_ability_description.split(":", 1)[0].strip()
            st.special_ability_description = st.special_ability_description.split(":", 1)[-1].strip()
            st.save()


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0066_gfsstufenplan_special_ability_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_product_model)
    ]
