# Generated by Django 4.1.7 on 2023-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0067_auto_20230317_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='wesenkraft',
            name='manaverbrauch',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wesenkraft',
            name='wirkung',
            field=models.TextField(default='', max_length=300),
        ),
    ]
