# Generated by Django 4.1.7 on 2023-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0068_wesenkraft_manaverbrauch_alter_wesenkraft_wirkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wesenkraft',
            name='manaverbrauch',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
