# Generated by Django 4.1.7 on 2023-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0070_alter_wesenkraft_wirkung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wesenkraft',
            name='zusatz_wesenspezifisch',
        ),
        migrations.AddField(
            model_name='wesenkraft',
            name='zusatz_gfsspezifisch',
            field=models.ManyToManyField(blank=True, related_name='zusatz_gfsspezifisch', to='character.gfs'),
        ),
    ]
