# Generated by Django 4.1.7 on 2023-03-26 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0071_remove_wesenkraft_zusatz_wesenspezifisch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='talente',
        ),
        migrations.RemoveField(
            model_name='professionattribut',
            name='maxWert',
        ),
        migrations.AlterField(
            model_name='gfs',
            name='ap',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='AP-Kosten'),
        ),
        migrations.DeleteModel(
            name='ProfessionTalent',
        ),
    ]
