# Generated by Django 4.1.7 on 2023-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0072_remove_profession_talente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfs',
            name='difficulty',
            field=models.CharField(choices=[('e', 'für Einsteiger'), ('f', 'für Fortgeschrittene'), ('p', 'für Profis')], default='e', max_length=1),
        ),
    ]
