# Generated by Django 4.1.7 on 2023-04-04 12:53

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0073_gfs_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfs',
            name='beschreibung_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='gfs',
            name='beschreibung',
            field=markdownfield.models.MarkdownField(rendered_field='beschreibung_rendered'),
        ),
    ]
