# Generated by Django 4.1.7 on 2023-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0075_populate_gfs_beschreibung_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachteil',
            name='max_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Leer lassen für keine Beschränkung', null=True),
        ),
        migrations.AddField(
            model_name='vorteil',
            name='max_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Leer lassen für keine Beschränkung', null=True),
        ),
    ]
