# Generated by Django 4.1.7 on 2023-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0087_remove_relzauber_will_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
        migrations.AlterField(
            model_name='vorteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
        migrations.AlterUniqueTogether(
            name='gfsnachteil',
            unique_together={('teil', 'gfs', 'notizen')},
        ),
    ]
