# Generated by Django 4.1.7 on 2023-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0088_alter_nachteil_is_sellable_alter_vorteil_is_sellable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsnachteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
        migrations.AddField(
            model_name='gfsvorteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
        migrations.AddField(
            model_name='relnachteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
        migrations.AddField(
            model_name='relvorteil',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='ist verkaufbar?'),
        ),
    ]
