# Generated by Django 4.1.7 on 2023-07-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0089_gfsnachteil_is_sellable_gfsvorteil_is_sellable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nachteil',
            options={'ordering': ['titel', 'ip'], 'verbose_name': 'Nachteil', 'verbose_name_plural': 'Nachteile'},
        ),
        migrations.AlterModelOptions(
            name='vorteil',
            options={'ordering': ['titel', 'ip'], 'verbose_name': 'Vorteil', 'verbose_name_plural': 'Vorteile'},
        ),
        migrations.AlterUniqueTogether(
            name='nachteil',
            unique_together={('titel', 'ip', 'beschreibung')},
        ),
        migrations.AlterUniqueTogether(
            name='vorteil',
            unique_together={('titel', 'ip', 'beschreibung')},
        ),
    ]
