# Generated by Django 4.1.7 on 2023-07-19 12:19

from django.db import migrations

def migrate_to_product_model(apps, schema_editor):
    GfsStufenplan = apps.get_model('character', 'GfsStufenplan')
    GfsAbility = apps.get_model('character', 'GfsAbility')

    for st in GfsStufenplan.objects.filter(special_ability__isnull=False):
        ability = GfsAbility.objects.create(name=st.special_ability, beschreibung=st.special_ability_description)
        st.ability = ability
        st.save(update_fields=["ability"])

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0096_gfsability_gfsstufenplan_ability'),
    ]

    operations = [
        migrations.RunPython(migrate_to_product_model)
    ]
