# Generated by Django 4.1.7 on 2023-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0097_auto_20230719_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsstufenplan',
            name='ability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.gfsability'),
        ),
    ]
