# Generated by Django 4.1.7 on 2023-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0098_alter_gfsstufenplan_ability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gfsability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gfsability',
            name='beschreibung',
            field=models.TextField(max_length=2000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='gfsability',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Fähigkeit'),
        ),
    ]
