# Generated by Django 4.1.7 on 2023-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0100_remove_gfsstufenplan_special_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='bedingung',
            field=models.ManyToManyField(blank=True, to='character.talent'),
        ),
    ]
