# Generated by Django 4.1.7 on 2023-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0105_alter_charakter_processing_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='tp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
