# Generated by Django 4.1.7 on 2023-07-25 10:13

from django.db import migrations

def deleteSkilltreeBasesExceptGfs(apps, schema_editor):
    SkilltreeBase = apps.get_model('character', 'SkilltreeBase')
    SkilltreeBase.objects.exclude(kind="g").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('character', '0108_remove_profession_attribute_and_more'),
    ]

    operations = [
        migrations.RunPython(deleteSkilltreeBasesExceptGfs)
    ]
