# Generated by Django 4.1.7 on 2023-07-25 11:46
import re

from django.db import migrations, models


def fill_skilltree(apps, schema_editor):
    Skilltree = apps.get_model('character', 'SkilltreeEntryGfs')
    MachineSkilltree = apps.get_model('character', 'MachinereadableSkilltreeEntry')

    entries = list(Skilltree.objects.all())
    for s in entries:
        for part in s.text.split(","):
            matches = re.match(r"^[+](?P<amount>\d+)\W+(?P<kind>\w+)$", part)

            if matches:
                amount = int(matches.group("amount"))
                kind = matches.group("kind")

                operation = ""
                if kind == "AP": operation = "a"
                if kind == "FP": operation = "f"
                if kind == "FG": operation = "F"
                if kind == "SP": operation = "p"
                if kind == "IP": operation = "i"
                if kind == "TP": operation = "t"
                if "auber" in kind: operation = "z"

                if operation:
                    MachineSkilltree.objects.create(skilltree_entry=s, amount=amount, operation=operation)
                    continue

            MachineSkilltree.objects.create(skilltree_entry=s, amount=0, operation="", text=part)


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0110_alter_skilltreebase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinereadableskilltreeentry',
            name='operation',
            field=models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'zauberslot'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('', 'Roleplay-Text')], default='', max_length=1),
        ),
        migrations.RunPython(fill_skilltree)
    ]
