# Generated by Django 4.1.7 on 2023-07-25 17:16
import re
from django.db import migrations, models
import django.db.models.deletion


def fill_skilltree(apps, schema_editor):
    GfsSkilltreeEntry = apps.get_model('character', 'GfsSkilltreeEntry')
    SkilltreeEntryGfs = apps.get_model('character', 'SkilltreeEntryGfs')

    entries = list(SkilltreeEntryGfs.objects.all())
    for s in entries:
        matches = re.match("^\+?(?P<amount>\d+)\W+(?P<kind>[\w-]+)$", s.text)

        if matches:
            amount = int(matches.group("amount"))
            kind = matches.group("kind")

            operation = ""
            if kind == "AP": operation = "a"
            if kind == "FP": operation = "f"
            if kind == "FG": operation = "F"
            if kind == "SP": operation = "p"
            if kind == "IP": operation = "i"
            if kind == "TP": operation = "t"

            if "auber" in kind: operation = "z"
            if "ngriff" in kind: operation = "A"
            if "erteidigung" in kind: operation = "V"

            if operation:
                GfsSkilltreeEntry.objects.create(gfs=s.gfs, base=s.context, amount=amount, operation=operation)
                continue

        GfsSkilltreeEntry.objects.create(gfs=s.gfs, base=s.context, operation="R", text=s.text)

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0112_machinereadableskilltreeentry_stufe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfsSkilltreeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'zauberslot'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('B', 'Bonus in Fertigkeit'), ('A', '+ Crit-Angriff'), ('V', '+ Crit-Verteidigung'), ('K', '+ körperliche HP'), ('G', '+ geistige HP'), ('h', 'Shop'), ('R', 'Roleplay-Text')], default='R', max_length=1)),
                ('amount', models.SmallIntegerField(blank=True, help_text='für AP, FP, FG, SP, IP, TP und Anz. Zauber-slots, WP Speizis/Wissis, Fertigkeitsbonus, Crit und HP', null=True)),
                ('stufe', models.SmallIntegerField(blank=True, help_text='für Zauber-slots', null=True)),
                ('text', models.TextField(blank=True, help_text='für alles nicht-implementierbare, z. B. Bonuseffekte bei Angriffen', null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.skilltreebase')),
                ('fertigkeit', models.ForeignKey(blank=True, help_text='für Bonus in Fertigkeit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.fertigkeit')),
                ('gfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.gfs')),
                ('nachteil', models.ForeignKey(blank=True, help_text='für neuen Nachteil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.nachteil')),
                ('spezialfertigkeit', models.ForeignKey(blank=True, help_text='Für neue Spezi und WP in einer Spezi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.spezialfertigkeit')),
                ('vorteil', models.ForeignKey(blank=True, help_text='für neuen Vorteil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.vorteil')),
                ('wissensfertigkeit', models.ForeignKey(blank=True, help_text='Für neue Wissi und WP in einer Wissi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.wissensfertigkeit')),
            ],
        ),
        migrations.DeleteModel(
            name='MachinereadableSkilltreeEntry',
        ),
        migrations.RunPython(fill_skilltree)
    ]
