# Generated by Django 4.1.7 on 2023-07-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0119_auto_20230726_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relnachteil',
            name='anzahl',
        ),
        migrations.RemoveField(
            model_name='relvorteil',
            name='anzahl',
        ),
    ]
