# Generated by Django 4.1.7 on 2023-07-29 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0120_remove_relnachteil_anzahl_remove_relvorteil_anzahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relspezialfertigkeit',
            name='stufe',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='relwissensfertigkeit',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
