# Generated by Django 4.1.7 on 2023-07-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0121_alter_relspezialfertigkeit_stufe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relattribut',
            name='fg_bonus',
        ),
    ]
