# Generated by Django 4.1.7 on 2023-08-09 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0127_charakter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='larp_rang',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
