# Generated by Django 4.1.7 on 2023-08-10 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0130_alter_charakter_alter_alter_charakter_augenfarbe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='gewicht',
            field=models.FloatField(default=75, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewicht in kg'),
        ),
    ]
