# Generated by Django 4.1.7 on 2023-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0132_nachteil_has_implementation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachteil',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AlterField(
            model_name='nachteil',
            name='needs_implementation',
            field=models.BooleanField(default=False, verbose_name='muss implementiert werden'),
        ),
        migrations.AlterField(
            model_name='vorteil',
            name='has_implementation',
            field=models.BooleanField(default=False, verbose_name='ist implementiert'),
        ),
        migrations.AlterField(
            model_name='vorteil',
            name='needs_implementation',
            field=models.BooleanField(default=False, verbose_name='muss implementiert werden'),
        ),
    ]
