# Generated by Django 4.1.7 on 2023-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0134_spezies_beschreibung_spezies_beschreibung_rendered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertigkeit',
            name='attr1',
        ),
        migrations.RemoveField(
            model_name='fertigkeit',
            name='attr2',
        ),
        migrations.RemoveField(
            model_name='gfsfertigkeit',
            name='pool',
        ),
        migrations.AddField(
            model_name='fertigkeit',
            name='attribut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.attribut'),
        ),
        migrations.AddField(
            model_name='fertigkeit',
            name='gruppe',
            field=models.CharField(choices=[('a', 'Athletiker'), ('b', 'Gelehrter'), ('c', 'Weiser'), ('d', 'Akrobat'), ('e', 'Tank'), ('f', 'Heiler'), ('g', 'Techniker'), ('h', 'Dieb'), ('i', 'Händler'), ('j', 'Zauberer'), ('k', 'Hexer'), ('l', 'Metamagier'), ('m', 'Selbstkenner'), ('n', 'Schütze'), ('o', 'Artillerist'), ('p', 'Barbar'), ('q', 'Ritter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fertigkeit',
            name='impro_possible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RelGruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(choices=[('a', 'Athletiker'), ('b', 'Gelehrter'), ('c', 'Weiser'), ('d', 'Akrobat'), ('e', 'Tank'), ('f', 'Heiler'), ('g', 'Techniker'), ('h', 'Dieb'), ('i', 'Händler'), ('j', 'Zauberer'), ('k', 'Hexer'), ('l', 'Metamagier'), ('m', 'Selbstkenner'), ('n', 'Schütze'), ('o', 'Artillerist'), ('p', 'Barbar'), ('q', 'Ritter')], max_length=1)),
                ('fg', models.SmallIntegerField(default=0)),
                ('fg_temp', models.SmallIntegerField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
            ],
            options={
                'verbose_name': 'Fertigkeitsgruppe',
                'verbose_name_plural': 'Fertigkeitsgruppen',
                'ordering': ['char', 'gruppe'],
                'unique_together': {('char', 'gruppe')},
            },
        ),
    ]
