# Generated by Django 4.1.7 on 2023-09-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0135_auto_20230909_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='spezies',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='fg',
        ),
        migrations.RemoveField(
            model_name='relattribut',
            name='fg_temp',
        ),
    ]
