# Generated by Django 4.1.7 on 2023-09-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0138_alter_charakter_alter_alter_charakter_geschlecht_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spezies',
            new_name='Wesen',
        ),
        migrations.DeleteModel(
            name='RelSpezies',
        ),
    ]
