# Generated by Django 4.1.7 on 2023-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0141_auto_20231014_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='manaoverflow_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
