# Generated by Django 4.2.8 on 2024-05-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0144_remove_charakter_sonstiges_alchemie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='language_daemonisch',
            field=models.BooleanField(default=False),
        ),
    ]
