# Generated by Django 4.2.8 on 2024-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0147_gfsability_has_implementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='glück',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='charakter',
            name='immunsystem_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='konzentration_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='konzentration_fix',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='limit_g_fix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='limit_k_fix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='limit_m_fix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='manifest_fix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='charakter',
            name='natSchaWi_pro_erfolg_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='nat_regeneration_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='sanität',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='charakter',
            name='sp_fix',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
