# Generated by Django 4.2.8 on 2024-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0148_charakter_glück_charakter_immunsystem_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='konzentration_bonus',
        ),
    ]
