# Generated by Django 4.2.8 on 2024-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0149_remove_charakter_konzentration_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='natSchaWi_pro_erfolg_rüstung',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='natürlicher_schadenswiderstand_rüstung',
            field=models.SmallIntegerField(default=0),
        ),
    ]
