# Generated by Django 4.2.8 on 2024-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0150_charakter_natschawi_pro_erfolg_rüstung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='rüstung_haltbarkeit',
            field=models.SmallIntegerField(default=0),
        ),
    ]
