# Generated by Django 4.2.8 on 2024-09-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0154_spieler_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spieler',
            name='language_daemonisch',
        ),
    ]
