# Generated by Django 4.2.8 on 2024-10-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0156_klasse_alter_gfs_options_relklasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasseAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fähigkeit')),
                ('beschreibung', models.TextField(max_length=2000, verbose_name='Beschreibung')),
                ('notizen', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Klassen-Fähigkeit',
                'verbose_name_plural': 'Klassen-Fähigkeiten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelKlasseAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.TextField(blank=True, null=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.klasseability')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
            ],
            options={
                'verbose_name': 'Klassen-Fähigkeit',
                'verbose_name_plural': 'Klassen-Fähigkeiten',
                'ordering': ['char', 'ability'],
                'unique_together': {('char', 'ability')},
            },
        ),
        migrations.CreateModel(
            name='KlasseStufenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveSmallIntegerField()),
                ('ap', models.PositiveSmallIntegerField(default=0)),
                ('fp', models.PositiveSmallIntegerField(default=0)),
                ('fg', models.PositiveSmallIntegerField(default=0)),
                ('tp', models.PositiveSmallIntegerField(default=0)),
                ('ip', models.PositiveSmallIntegerField(default=0)),
                ('zauber', models.PositiveSmallIntegerField(default=0)),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.klasseability')),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.klasse')),
            ],
            options={
                'verbose_name': 'Klasse-Stufenplan',
                'verbose_name_plural': 'Klasse-Stufenpläne',
                'ordering': ['klasse', 'stufe'],
                'unique_together': {('klasse', 'stufe')},
            },
        ),
    ]
