# Generated by Django 4.2.8 on 2024-10-28 13:56

import django.core.validators
from django.db import migrations, models

def gfsstufenplanbase_rm_stufe_1(apps, schema_editor):
    GfsStufenplanBase = apps.get_model('character', 'GfsStufenplanBase')
    GfsStufenplanBase.objects.filter(stufe__lt=2).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0160_alter_gfsstufenplanbase_unique_together_and_more copy'),
    ]

    operations = [
        migrations.RunPython(gfsstufenplanbase_rm_stufe_1)
    ]
