# Generated by Django 4.2.8 on 2024-10-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0164_charakter_persönlichkeit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='persönlichkeit_old',
        ),
    ]
