# Generated by Django 4.2.8 on 2024-11-04 12:29

from django.db import migrations, models


def klasse_beschreibung_to_abilities(apps, schema_editor):
    Klasse = apps.get_model('character', 'Klasse')
    KlasseAbility = apps.get_model('character', 'KlasseAbility')

    for klasse in Klasse.objects.all():
        abilities = [KlasseAbility(name=a.split(": ")[0].strip(), beschreibung=a.split(": ")[1].strip()) for a in klasse.beschreibung.split("\n\r")]
        
        klasse.base_abilities.set(
            KlasseAbility.objects.bulk_create(abilities)
        )

    Klasse.objects.update(beschreibung="")

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0169_init_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='base_abilities',
            field=models.ManyToManyField(to='character.klasseability'),
        ),
        migrations.RunPython(klasse_beschreibung_to_abilities),
    ]
