# Generated by Django 4.2.8 on 2024-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_pfeil_bolzen_schadensart_and_more'),
        ('character', '0174_charakter_affektivitäten'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='pfeile_bolzen',
            field=models.ManyToManyField(blank=True, through='character.RelPfeil_Bolzen', to='shop.pfeil_bolzen'),
        ),
    ]
