# Generated by Django 4.2.8 on 2024-12-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0177_alter_charakter_ep_stufe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfsEigenschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gfs-Eigenschaft',
                'verbose_name_plural': 'Gfs-Eigenschaften',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='gfs',
            name='eigenschaften_rendered',
        ),
        migrations.RemoveField(
            model_name='gfs',
            name='eigenschaften',
        ),
        migrations.AddField(
            model_name='gfs',
            name='eigenschaften',
            field=models.ManyToManyField(to='character.gfseigenschaft'),
        ),
    ]
