# Generated by Django 4.2.8 on 2025-02-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0178_gfseigenschaft_remove_gfs_eigenschaften_rendered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gfswesenkraft',
            options={'ordering': ['gfs', 'wesenkraft'], 'verbose_name': 'Start-Wesenkraft von Gfs', 'verbose_name_plural': 'Start-Wesenkräfte von Gfs'},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['spieler', 'name'],
                'unique_together': {('spieler', 'name')},
            },
        ),
        migrations.AddField(
            model_name='charakter',
            name='tags',
            field=models.ManyToManyField(to='character.tag'),
        ),
    ]
