# Generated by Django 4.2.8 on 2025-04-03 11:00

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0180_alter_charakter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wesen',
            name='beschreibung',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='beschreibung_rendered'),
        ),
    ]
