# Generated by Django 4.2.8 on 2025-09-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0181_alter_wesen_beschreibung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReilRamsch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=128)),
                ('anz', models.PositiveIntegerField(default=1)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
            ],
            options={
                'ordering': ['char', 'item'],
                'unique_together': {('char', 'item')},
            },
        ),
    ]
