# Generated by Django 4.2.8 on 2025-09-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0182_reilramsch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReilRamsch',
            new_name='RelRamsch',
        ),
    ]
