# Generated by Django 4.2.8 on 2025-09-02 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0183_rename_reilramsch_relramsch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relramsch',
            name='anz',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
