# Generated by Django 4.2.8 on 2025-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0185_alter_charakter_image_alter_gfs_eigenschaften_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstory',
            name='notes_rendered',
        ),
        migrations.AlterField(
            model_name='currentstory',
            name='gHP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='geistige HP'),
        ),
        migrations.AlterField(
            model_name='currentstory',
            name='kHP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='körperliche HP'),
        ),
        migrations.AlterField(
            model_name='currentstory',
            name='konz',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Konzentration'),
        ),
        migrations.AlterField(
            model_name='currentstory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
