# Generated by Django 4.2.8 on 2025-11-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0190_auto_20251116_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='geld',
        ),
    ]
