# Generated by Django 4.2.8 on 2025-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0191_remove_charakter_geld'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter',
            name='no_MA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charakter',
            name='no_MA_MG',
            field=models.BooleanField(default=False),
        ),
    ]
