# Generated by Django 4.2.8 on 2025-12-06 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0193_spieler_user_alter_charakter_no_ma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spieler',
            options={'ordering': ['user'], 'verbose_name_plural': 'Spieler'},
        ),
        migrations.RemoveField(
            model_name='spieler',
            name='name',
        ),
        migrations.AlterField(
            model_name='spieler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
