# Generated by Django 5.2.9 on 2026-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0197_alter_charakter_rüstungen_alter_relrüstung_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='limit_g_fix',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='limit_k_fix',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='limit_m_fix',
        ),
        migrations.RemoveField(
            model_name='fertigkeit',
            name='limit',
        ),
        migrations.AddField(
            model_name='charakter',
            name='speed_astral_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='speed_fliegen_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='speed_laufen_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='charakter',
            name='speed_schwimmen_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gfs',
            name='base_movement_speed',
            field=models.FloatField(blank=True, default=3, verbose_name='Grundbewegungsrate'),
        ),
    ]
