# Generated by Django 5.2.9 on 2026-02-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0198_remove_charakter_limit_g_fix_and_more'),
        ('effect', '0023_auto_20260214_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='astralwiderstand_pro_erfolg_bonus',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='natSchaWi_pro_erfolg_bonus',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='natSchaWi_pro_erfolg_rüstung',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='rüstung_haltbarkeit',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='natürlicher_schadenswiderstand_rüstung',
        ),
        migrations.AddField(
            model_name='charakter',
            name='astralwiderstand_bonus_str',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='charakter',
            name='natürlicher_schadenswiderstand_bonus_str',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
