# Generated by Django 5.2.9 on 2026-02-15 12:13

from django.db import migrations


def add_initial_transactions_for_chars(apps, schema_editor):
    Klasse = apps.get_model('character', 'Klasse')
    
    Klasse.objects.filter(requirement="Reaktion 12").update(requirement="physische Reaktion 12")
    Klasse.objects.filter(requirement="nat. Schadenswiderstand 14").update(requirement="physischer Widerstand 14")
    Klasse.objects.filter(requirement="Astral-Widerstand 14").update(requirement="astrale Reaktion 14")
    Klasse.objects.filter(requirement="Intuition 12").update(requirement="Wahrnehmung 12")

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0199_remove_charakter_astralwiderstand_pro_erfolg_bonus_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_transactions_for_chars)
    ]
