# Generated by Django 5.2.9 on 2026-02-16 12:14

from django.apps import apps as a
from django.db import migrations

from effect.signals import apply_hp_effect_of_haustierfels


def kHP_changed_apply_Haustierfels(apps, schema_editor):
    Charakter = a.get_model('character', 'Charakter')
    for char in Charakter.objects.filter(in_erstellung=False): apply_hp_effect_of_haustierfels(Charakter, char)


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0200_auto_20260215_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charakter',
            name='rang',
        ),
        migrations.RunPython(kHP_changed_apply_Haustierfels)
    ]
