# Generated by Django 5.2.9 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0202_rename_astralwiderstand_bonus_charakter_astraler_widerstand_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charakter',
            old_name='reaktion_bonus',
            new_name='physische_reaktion_bonus',
        ),
        migrations.AlterField(
            model_name='gfsskilltreeentry',
            name='operation',
            field=models.CharField(choices=[('a', 'AP'), ('f', 'FP'), ('F', 'FG'), ('p', 'SP'), ('i', 'IP'), ('t', 'TP'), ('z', 'Zauberslot/s'), ('v', 'neuer Vorteil'), ('n', 'neuer Nachteil'), ('e', 'neue Wesenkraft'), ('s', 'neue Spezialfertigkeit'), ('w', 'neue Wissensfertigkeit'), ('S', 'WP in Spezialfertigkeit'), ('W', 'WP in Wissensfertigkeit'), ('B', 'Bonus in Fertigkeit'), ('A', 'Crit-Angriff'), ('V', 'Crit-Verteidigung'), ('K', 'körperliche HP'), ('G', 'geistige HP'), ('k', 'HP Schaden waff. Kampf'), ('I', 'Initiative fix'), ('r', 'physische Reaktion'), ('N', 'physischer Widerstand'), ('T', 'astraler Widerstand'), ('h', 'magisches Item'), ('R', 'Roleplay-Text')], default='R', help_text='wichtigstes Feld, bestimmt die Art des Eintrags und welche anderen Felder benötigt werden.', max_length=1),
        ),
    ]
