# Generated by Django 5.2.9 on 2026-02-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0204_rename_astraler_widerstand_bonus_charakter_astrale_reaktion_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relvergessenerzauber',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relvergessenerzauber',
            name='item',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='vergessene_zauber',
        ),
        migrations.RemoveField(
            model_name='wesenkraft',
            name='skilled_gfs',
        ),
        migrations.DeleteModel(
            name='RelFirmaVergessenerZauber',
        ),
        migrations.DeleteModel(
            name='RelVergessenerZauber',
        ),
    ]
