# Generated by Django 5.2.9 on 2026-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0205_remove_relvergessenerzauber_char_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relramsch',
            options={'verbose_name': 'Ramsch', 'verbose_name_plural': 'Ramsch'},
        ),
        migrations.AlterUniqueTogether(
            name='relramsch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relramsch',
            name='notizen',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='relramsch',
            name='stufe',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relramsch',
            name='anz',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
