# Generated by Django 5.2.9 on 2026-09-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0206_alter_relramsch_options_and_more'),
        ('shop', '0073_remove_schusswaffen_fertigkeit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelSchusswaffen',
            new_name='RelFernkampfwaffe',
        ),
        migrations.RenameModel(
            old_name='RelFirmaSchusswaffen',
            new_name='RelFirmaFernkampfwaffe',
        ),
        migrations.AlterModelOptions(
            name='relfernkampfwaffe',
            options={'verbose_name': 'Fernkampfwaffe', 'verbose_name_plural': 'Fernkampfwaffen'},
        ),
        migrations.AlterModelOptions(
            name='relfirmafernkampfwaffe',
            options={'verbose_name': 'Fernkampfwaffe Verfügbarkeit', 'verbose_name_plural': 'Fernkampfwaffen Verfügbarkeiten'},
        ),
        migrations.RenameField(
            model_name='charakter',
            old_name='schusswaffen',
            new_name='fernkampfwaffen',
        ),
        migrations.AlterField(
            model_name='relfernkampfwaffe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fernkampfwaffe'),
        ),
    ]
