# Generated by Django 5.2.9 on 2026-09-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0207_rename_relschusswaffen_relfernkampfwaffe_and_more'),
        ('shop', '0074_auto_20260919_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relpfeil_bolzen',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relpfeil_bolzen',
            name='item',
        ),
        migrations.RemoveField(
            model_name='charakter',
            name='pfeile_bolzen',
        ),
        migrations.DeleteModel(
            name='RelFirmaPfeil_Bolzen',
        ),
        migrations.DeleteModel(
            name='RelPfeil_Bolzen',
        ),
    ]
