# Generated by Django 5.2.9 on 2026-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0208_remove_relpfeil_bolzen_char_and_more'),
        ('shop', '0075_remove_pfeil_bolzen_firmen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelFirmaMagazin',
            new_name='RelFirmaMunition',
        ),
        migrations.RenameModel(
            old_name='RelMagazin',
            new_name='RelMunition',
        ),
        migrations.AlterModelOptions(
            name='relfirmamunition',
            options={'verbose_name': 'Munition Verfügbarkeit', 'verbose_name_plural': 'Munition Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='relmunition',
            options={'verbose_name': 'Munition', 'verbose_name_plural': 'Munition'},
        ),
        migrations.RenameField(
            model_name='charakter',
            old_name='magazine',
            new_name='munition',
        ),
    ]
