# Generated by Django 5.2.9 on 2026-09-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0209_rename_relfirmamagazin_relfirmamunition'),
        ('effect', '0032_rename_source_shopeinbauten_releffect_source_shopeinbaute_and_more'),
        ('shop', '0077_remove_rituale_runen_firmen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelEinbauten',
            new_name='RelEinbaute',
        ),
        migrations.RenameModel(
            old_name='RelFirmaEinbauten',
            new_name='RelFirmaEinbaute',
        ),
        migrations.RenameModel(
            old_name='RelFirmaRituale_Runen',
            new_name='RelFirmaRitual_Rune',
        ),
        migrations.RenameModel(
            old_name='RelFirmaWaffen_Werkzeuge',
            new_name='RelFirmaWaffe_Werkzeug',
        ),
        migrations.RenameModel(
            old_name='RelRituale_Runen',
            new_name='RelRitual_Rune',
        ),
        migrations.RenameModel(
            old_name='RelWaffen_Werkzeuge',
            new_name='RelWaffe_Werkzeug',
        ),
        migrations.AlterModelOptions(
            name='releinbaute',
            options={'verbose_name': 'Einbaute', 'verbose_name_plural': 'Einbauten'},
        ),
        migrations.AlterModelOptions(
            name='relfirmaeinbaute',
            options={'verbose_name': 'Einbaute Verfügbarkeit', 'verbose_name_plural': 'Einbaute Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='relfirmaritual_rune',
            options={'verbose_name': 'Ritual/Rune Verfügbarkeit', 'verbose_name_plural': 'Ritual/Rune Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='relfirmawaffe_werkzeug',
            options={'verbose_name': 'Waffe/Werkzeug Verfügbarkeit', 'verbose_name_plural': 'Waffe/Werkzeug Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='relritual_rune',
            options={'verbose_name': 'Ritual/Rune', 'verbose_name_plural': 'Rituale/Runen'},
        ),
        migrations.AlterModelOptions(
            name='relwaffe_werkzeug',
            options={'verbose_name': 'Waffe/Werkzeug', 'verbose_name_plural': 'Waffen/Werkzeuge'},
        ),
        migrations.AlterField(
            model_name='charakter',
            name='einbauten',
            field=models.ManyToManyField(blank=True, through='character.RelEinbaute', to='shop.einbaute'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='rituale_runen',
            field=models.ManyToManyField(blank=True, through='character.RelRitual_Rune', to='shop.ritual_rune'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='waffenWerkzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelWaffe_Werkzeug', to='shop.waffe_werkzeug'),
        ),
        migrations.AlterField(
            model_name='releinbaute',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.einbaute'),
        ),
        migrations.AlterField(
            model_name='relritual_rune',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ritual_rune'),
        ),
        migrations.AlterField(
            model_name='relwaffe_werkzeug',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.waffe_werkzeug'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='einbauten',
            field=models.ManyToManyField(blank=True, through='character.RelEinbaute', to='shop.einbaute'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='rituale_runen',
            field=models.ManyToManyField(blank=True, through='character.RelRitual_Rune', to='shop.ritual_rune'),
        ),
        migrations.AlterField(
            model_name='charakter',
            name='waffenWerkzeuge',
            field=models.ManyToManyField(blank=True, through='character.RelWaffe_Werkzeug', to='shop.waffe_werkzeug'),
        ),
    ]
