# Generated by Django 5.2.9 on 2026-09-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0210_rename_releinbauten_releinbaute_and_more'),
        ('shop', '0079_remove_alchemie_illegal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelFirmaWaffe_Werkzeug',
            new_name='RelFirmaNahkampfwaffe',
        ),
        migrations.RenameModel(
            old_name='RelWaffe_Werkzeug',
            new_name='RelNahkampfwaffe',
        ),
        migrations.AlterModelOptions(
            name='relfirmanahkampfwaffe',
            options={'verbose_name': 'Nahkampf-/Wurfwaffe Verfügbarkeit', 'verbose_name_plural': 'Nahkampf-/Wurfwaffe Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='relnahkampfwaffe',
            options={'verbose_name': 'Nahkampf-/Wurfwaffe', 'verbose_name_plural': 'Nahkampf-/Wurfwaffen'},
        ),
        migrations.RenameField(
            model_name='charakter',
            old_name='waffenWerkzeuge',
            new_name='nahkampfwaffen',
        ),
    ]
