# Generated by Django 5.2.9 on 2026-09-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0211_rename_relfirmawaffe_werkzeug_relfirmanahkampfwaffe'),
        ('shop', '0097_alter_upgrade_influenced_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelFirmaAusrüstung_Technik',
            new_name='RelFirmaTechnik',
        ),
        migrations.RenameModel(
            old_name='RelAusrüstung_Technik',
            new_name='RelTechnik',
        ),
        migrations.RenameField(
            model_name='charakter',
            old_name='ausrüstungTechnik',
            new_name='technik',
        ),
        migrations.AlterModelOptions(
            name='relfirmatechnik',
            options={'verbose_name': 'Technik Verfügbarkeit', 'verbose_name_plural': 'Technik Verfügbarkeiten'},
        ),
        migrations.AlterModelOptions(
            name='reltechnik',
            options={'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
    ]
