# Generated by Django 5.2.9 on 2026-10-03 15:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0212_rename_relfirmaausrüstung_technik_relfirmatechnik'),
        ('shop', '0103_alter_modifier_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relfirmabegleiter',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmabegleiter',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmaeinbaute',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmaeinbaute',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmaengelsroboter',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmaengelsroboter',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmafahrzeug',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmafahrzeug',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmafernkampfwaffe',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmafernkampfwaffe',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmaitem',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmaitem',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmamagische_ausrüstung',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmamagische_ausrüstung',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmamunition',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmamunition',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmanahkampfwaffe',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmanahkampfwaffe',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmaritual_rune',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmaritual_rune',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmarüstung',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmarüstung',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmatechnik',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmatechnik',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmatinker',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmatinker',
            name='firma_shop',
        ),
        migrations.RemoveField(
            model_name='relfirmazauber',
            name='char',
        ),
        migrations.RemoveField(
            model_name='relfirmazauber',
            name='firma_shop',
        ),
        migrations.CreateModel(
            name='RelAlchemieAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.alchemie')),
            ],
            options={
                'verbose_name': 'Alchemie Verfügbarkeit',
                'verbose_name_plural': 'Alchemie Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelBegleiterAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.begleiter')),
            ],
            options={
                'verbose_name': 'Begleiter Verfügbarkeit',
                'verbose_name_plural': 'Begleiter Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelEinbauteAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.einbaute')),
            ],
            options={
                'verbose_name': 'Einbaute Verfügbarkeit',
                'verbose_name_plural': 'Einbaute Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelEngelsroboterAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.engelsroboter')),
            ],
            options={
                'verbose_name': 'Engelsroboter Verfügbarkeit',
                'verbose_name_plural': 'Engelsroboter Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFahrzeugAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug Verfügbarkeit',
                'verbose_name_plural': 'Fahrzeuge Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelFernkampfwaffeAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fernkampfwaffe')),
            ],
            options={
                'verbose_name': 'Fernkampfwaffe Verfügbarkeit',
                'verbose_name_plural': 'Fernkampfwaffen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelItemAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
            options={
                'verbose_name': 'Item Verfügbarkeit',
                'verbose_name_plural': 'Items Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelMagische_AusrüstungAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.magische_ausrüstung')),
            ],
            options={
                'verbose_name': 'magische Ausrüstung Verfügbarkeit',
                'verbose_name_plural': 'magische Ausrüstung Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelMunitionAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.munition')),
            ],
            options={
                'verbose_name': 'Munition Verfügbarkeit',
                'verbose_name_plural': 'Munition Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelNahkampfwaffeAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.nahkampfwaffe')),
            ],
            options={
                'verbose_name': 'Nahkampf-/Wurfwaffe Verfügbarkeit',
                'verbose_name_plural': 'Nahkampf-/Wurfwaffe Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelRitual_RuneAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ritual_rune')),
            ],
            options={
                'verbose_name': 'Ritual/Rune Verfügbarkeit',
                'verbose_name_plural': 'Ritual/Rune Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelRüstungAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rüstung')),
            ],
            options={
                'verbose_name': 'Rüstung Verfügbarkeit',
                'verbose_name_plural': 'Rüstungen Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelTechnikAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.technik')),
            ],
            options={
                'verbose_name': 'Technik Verfügbarkeit',
                'verbose_name_plural': 'Technik Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelTinkerAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
            ],
            options={
                'verbose_name': 'Für Selbstständige Verfügbarkeit',
                'verbose_name_plural': 'Für Selbstständige Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='RelZauberAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried', models.DateField(default=datetime.date.today)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zauber')),
            ],
            options={
                'verbose_name': 'Zauber Verfügbarkeit',
                'verbose_name_plural': 'Zauber Verfügbarkeiten',
            },
        ),
        migrations.DeleteModel(
            name='RelFirmaAlchemie',
        ),
        migrations.DeleteModel(
            name='RelFirmaBegleiter',
        ),
        migrations.DeleteModel(
            name='RelFirmaEinbaute',
        ),
        migrations.DeleteModel(
            name='RelFirmaEngelsroboter',
        ),
        migrations.DeleteModel(
            name='RelFirmaFahrzeug',
        ),
        migrations.DeleteModel(
            name='RelFirmaFernkampfwaffe',
        ),
        migrations.DeleteModel(
            name='RelFirmaItem',
        ),
        migrations.DeleteModel(
            name='RelFirmaMagische_Ausrüstung',
        ),
        migrations.DeleteModel(
            name='RelFirmaMunition',
        ),
        migrations.DeleteModel(
            name='RelFirmaNahkampfwaffe',
        ),
        migrations.DeleteModel(
            name='RelFirmaRitual_Rune',
        ),
        migrations.DeleteModel(
            name='RelFirmaRüstung',
        ),
        migrations.DeleteModel(
            name='RelFirmaTechnik',
        ),
        migrations.DeleteModel(
            name='RelFirmaTinker',
        ),
        migrations.DeleteModel(
            name='RelFirmaZauber',
        ),
    ]
