# Generated by Django 2.0.5 on 2018-11-19 18:30

import character.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCharakter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_system', models.BooleanField(default=True)),
                ('zauber', models.PositiveIntegerField(blank=True, null=True)),
                ('ap', models.PositiveIntegerField(blank=True, null=True)),
                ('sp', models.PositiveIntegerField(blank=True, null=True)),
                ('spezial', models.PositiveIntegerField(blank=True, null=True)),
                ('fp', models.PositiveIntegerField(blank=True, null=True)),
                ('fg', models.PositiveIntegerField(blank=True, null=True)),
                ('wk', models.PositiveIntegerField(blank=True, null=True)),
                ('geld', models.PositiveIntegerField(blank=True, null=True)),
                ('cp', models.IntegerField(blank=True, default=0)),
                ('magie', models.CharField(choices=[('r', 'reinmagisch'), ('t', 'teilmagisch'), ('m', 'mundan')], default='m', max_length=1)),
                ('manifest', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Startmanifest')),
                ('wesenschaden_waff_kampf', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewCharakterAttribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg', models.PositiveIntegerField(default=0)),
                ('fg_cp', models.PositiveIntegerField(default=0)),
                ('aktuellerWert', models.PositiveIntegerField(default=0)),
                ('aktuellerWert_ap', models.PositiveIntegerField(default=0)),
                ('aktuellerWert_cp', models.PositiveIntegerField(default=0)),
                ('maxWert', models.PositiveIntegerField(default=0)),
                ('maxWert_ap', models.PositiveIntegerField(default=0)),
                ('maxWert_cp', models.PositiveIntegerField(default=0)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Attribut')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
            ],
            options={
                'verbose_name': 'Startattribut',
                'verbose_name_plural': 'Startattribute',
                'ordering': ['attribut'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterFertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.PositiveIntegerField(default=0)),
                ('cp', models.PositiveIntegerField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('fertigkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Fertigkeit')),
            ],
            options={
                'verbose_name': 'Startfertigkeit',
                'verbose_name_plural': 'Startfertigkeiten',
                'ordering': ['fertigkeit'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterNachteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=200)),
                ('extra', models.CharField(blank=True, max_length=30, null=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('teil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Nachteil')),
            ],
            options={
                'verbose_name': 'Nachteil',
                'verbose_name_plural': 'Nachteile',
            },
        ),
        migrations.CreateModel(
            name='NewCharakterSpezialfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveIntegerField(blank=True, default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('spezialfertigkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezialfertigkeit')),
            ],
            options={
                'verbose_name': 'Spezialfertigkeit',
                'verbose_name_plural': 'Spezialfertigkeiten',
                'ordering': ['spezialfertigkeit'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterSpezies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('spezies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spezies')),
            ],
            options={
                'verbose_name': 'Spezies',
                'verbose_name_plural': 'Spezies',
                'ordering': ['spezies'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterStZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StZauber')),
            ],
            options={
                'verbose_name': 'Gratiszauber (st)',
                'verbose_name_plural': 'Gratiszauber (st)',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterVorteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.CharField(blank=True, default='', max_length=200)),
                ('extra', models.CharField(blank=True, max_length=30, null=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('teil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Vorteil')),
            ],
            options={
                'verbose_name': 'Vorteil',
                'verbose_name_plural': 'Vorteile',
            },
        ),
        migrations.CreateModel(
            name='NewCharakterWesenkraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('wesenkraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Wesenkraft')),
            ],
            options={
                'verbose_name': 'Startwesenkraft',
                'verbose_name_plural': 'Startwesenkräfte',
                'ordering': ['wesenkraft'],
            },
        ),
        migrations.CreateModel(
            name='NewCharakterZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Zauber')),
            ],
            options={
                'verbose_name': 'Gratiszauber',
                'verbose_name_plural': 'Gratiszauber',
                'ordering': ['item'],
            },
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='attribute',
            field=models.ManyToManyField(through='create.NewCharakterAttribut', to='character.Attribut'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='eigentümer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spieler'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='fertigkeiten',
            field=models.ManyToManyField(through='create.NewCharakterFertigkeit', to='character.Fertigkeit'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='gratis_st_zauber',
            field=models.ManyToManyField(through='create.NewCharakterStZauber', to='shop.StZauber'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='gratis_zauber',
            field=models.ManyToManyField(through='create.NewCharakterZauber', to='shop.Zauber'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='nachteile',
            field=models.ManyToManyField(through='create.NewCharakterNachteil', to='character.Nachteil'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='spezialfertigkeiten',
            field=models.ManyToManyField(through='create.NewCharakterSpezialfertigkeit', to='character.Spezialfertigkeit'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='spezies',
            field=models.ManyToManyField(through='create.NewCharakterSpezies', to='character.Spezies'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='vorteile',
            field=models.ManyToManyField(through='create.NewCharakterVorteil', to='character.Vorteil'),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='wesenkräfte',
            field=models.ManyToManyField(through='create.NewCharakterWesenkraft', to='character.Wesenkraft'),
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterzauber',
            unique_together={('item', 'char')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterwesenkraft',
            unique_together={('wesenkraft', 'char')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterstzauber',
            unique_together={('item', 'char')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterspezies',
            unique_together={('char', 'spezies')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterspezialfertigkeit',
            unique_together={('spezialfertigkeit', 'char')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterfertigkeit',
            unique_together={('fertigkeit', 'char')},
        ),
        migrations.AlterUniqueTogether(
            name='newcharakterattribut',
            unique_together={('attribut', 'char')},
        ),
    ]
