# Generated by Django 2.0.5 on 2018-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20181119_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcharakter',
            name='wk',
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='wesenschaden_andere_gestalt',
            field=models.IntegerField(blank=True, null=True, verbose_name='BS andere Gestalt'),
        ),
    ]
