# Generated by Django 2.2.13 on 2020-07-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20190311_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcharakter',
            old_name='cp',
            new_name='ip',
        ),
    ]
