# Generated by Django 2.2.13 on 2020-07-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_auto_20200730_1534'),
    ]

    operations = []
