# Generated by Django 2.2.14 on 2020-08-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20200806_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcharakterfertigkeit',
            options={'ordering': ['char', 'fertigkeit'], 'verbose_name': 'Startfertigkeit', 'verbose_name_plural': 'Startfertigkeiten'},
        ),
    ]
