# Generated by Django 2.2.13 on 2020-08-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_auto_20200810_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcharakter',
            name='spezial',
        ),
    ]
