# Generated by Django 2.2.13 on 2020-08-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_auto_20200812_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakterattribut',
            name='aktuellerWert_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcharakterattribut',
            name='fg_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcharakterattribut',
            name='maxWert_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
