# Generated by Django 2.2.13 on 2020-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0017_auto_20200815_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='larp',
            field=models.BooleanField(default=False),
        ),
    ]
