# Generated by Django 3.1.5 on 2021-06-01 14:37

from django.db import migrations, models

def populate_priotable(apps, schema_editor):
    rows = [
        ['A', 7, 15, 10, 20, 5, 5, 100000],
        ['B', 5, 13,  7, 17, 4, 4,  80000],
        ["C", 3, 11,  4, 14, 3, 3,  60000],
        ["D", 2,  9,  2, 11, 2, 2,  40000],
        ["E", 1,  7,  1,  8, 1, 1,  20000],
        ["F", 0,  5,  0,  5, 0, 0,  10000]
    ]
    # We can't import  models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Priotable = apps.get_model('create', 'Priotable')
    for row in rows:
        Priotable.objects.create(
            priority=row[0],
            ip=row[1],
            ap=row[2],
            sp=row[3],
            fp=row[4],
            fg=row[5],
            zauber=row[6],
            drachmen=row[7]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('create', '0021_auto_20210601_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priotable',
            name='drachmen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_priotable)
    ]
