# Generated by Django 3.1.5 on 2021-06-01 15:06

from django.db import migrations, models
import django.db.models.deletion

def populate_gfsCharacterization(apps, schema_editor):
    # We can't import  models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Gfs = apps.get_model('character', 'Gfs')
    GfsCharacterization = apps.get_model('create', 'GfsCharacterization')
    for gfs in Gfs.objects.all():
        GfsCharacterization.objects.get_or_create(gfs=gfs)

class Migration(migrations.Migration):

    dependencies = [
        ('character', '0054_auto_20201223_1709'),
        ('create', '0022_auto_20210601_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfsCharacterization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('l', 'lebend'), ('t', 'tot oder untot')], help_text='.. lebend oder (un)tot sein?', max_length=1, null=True)),
                ('social', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. sozial/umgänglich sein?', max_length=1, null=True)),
                ('magical', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. magisch sein?', max_length=1, null=True)),
                ('can_punch', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. Nahkampf haben?', max_length=1, null=True)),
                ('can_shoot', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. Fernkampf haben?', max_length=1, null=True)),
                ('has_pricy_skills', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. krasse (dafür teure) Fähigkeiten bekommen?', max_length=1, null=True)),
                ('flying', models.CharField(choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. fliegen können?', max_length=1, null=True)),
                ('attitude', models.CharField(choices=[('g', 'gut'), ('n', 'neutral'), ('e', 'böse')], help_text='.. gut/neutral/böse gesinnt sein?', max_length=1, null=True)),
                ('gfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.gfs')),
            ],
        ),
        migrations.RunPython(populate_gfsCharacterization)
    ]
