# Generated by Django 4.1.7 on 2023-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0033_auto_20220601_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfscharacterization',
            name='attitude',
            field=models.CharField(blank=True, choices=[('g', 'gut'), ('n', 'neutral'), ('e', 'böse')], max_length=1, null=True, verbose_name='.. gut/neutral/böse gesinnt sein?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_fly',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. fliegen können?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_punch',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. Nahkampf haben?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_shoot',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. Fernkampf haben?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='gets_pricy_skills',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. krasse (dafür teure) Fähigkeiten bekommen?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='magical',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. magisch sein?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='social',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], max_length=1, null=True, verbose_name='.. sozial/umgänglich sein?'),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='state',
            field=models.CharField(blank=True, choices=[('l', 'lebend'), ('t', 'tot oder untot')], max_length=1, null=True, verbose_name='.. lebend oder (un)tot sein?'),
        ),
    ]
