# Generated by Django 3.1.5 on 2021-04-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_decoration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('field', models.TextField(default='[[]]')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ['region', 'index'],
            },
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regionen'},
        ),
        migrations.AddField(
            model_name='layer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.region'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('region', 'index')},
        ),
    ]
