# Generated by Django 3.1.5 on 2021-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_auto_20210426_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='field',
        ),
        migrations.AddField(
            model_name='layer',
            name='is_collidable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_mineable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='field',
            field=models.JSONField(default=[[]]),
        ),
    ]
