# Generated by Django 3.1.5 on 2021-04-28 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mining.models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_auto_20210426_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='field',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='layer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.region', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100), mining.models.validate_not_zero]),
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('materials', models.ManyToManyField(to='mining.Material')),
            ],
            options={
                'verbose_name': 'Materialgruppe',
                'verbose_name_plural': 'Materialgruppen',
                'ordering': ['name'],
            },
        ),
    ]
