# Generated by Django 3.1.5 on 2021-04-28 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mining.models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_auto_20210428_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100), mining.models.validate_not_zero]),
        ),
        migrations.AlterField(
            model_name='layer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.region'),
        ),
    ]
