# Generated by Django 3.1.5 on 2021-04-28 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_auto_20210428_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='index',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
