# Generated by Django 3.1.5 on 2021-04-29 14:31

import django.core.validators
from django.db import migrations, models
import mining.models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_auto_20210428_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='bg_color_rgb',
            field=models.CharField(default='#b9fefd', max_length=7, validators=[mining.models.is_rgb_color]),
        ),
        migrations.AddField(
            model_name='region',
            name='layer_index_of_char',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
