# Generated by Django 3.1.5 on 2021-05-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_auto_20210429_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='is_mineable',
            new_name='is_breakable',
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('h', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.layer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.material')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['layer', 'x', 'y'],
            },
        ),
    ]
