# Generated by Django 3.1.5 on 2021-05-11 12:12

import django.core.validators
from django.db import migrations, models
import mining.models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0009_auto_20210511_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='h',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='w',
        ),
        migrations.AddField(
            model_name='entity',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='rotation_angle',
            field=models.PositiveSmallIntegerField(default=0, validators=[mining.models.validate_angle_multiple_90, django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='entity',
            name='scale',
            field=models.FloatField(default=1),
        ),
    ]
