# Generated by Django 3.1.5 on 2021-05-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0010_auto_20210511_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='field',
        ),
    ]
