# Generated by Django 3.1.5 on 2021-05-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0011_remove_layer_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materialien'},
        ),
    ]
