# Generated by Django 3.1.5 on 2021-05-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('crafting', '0017_auto_20210425_1400'),
        ('mining', '0012_auto_20210522_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingOriginatedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collidable', models.BooleanField(default=True)),
                ('is_breakable', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafting_originated_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.craftingoriginatedentity')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.entity')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.profile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.region')),
            ],
        ),
    ]
