# Generated by Django 3.1.5 on 2021-05-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('mining', '0013_craftingoriginatedentity_profileentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingOriginatedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collidable', models.BooleanField(default=True)),
                ('is_breakable', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.material')),
            ],
            options={
                'unique_together': {('item', 'material')},
            },
        ),
        migrations.RemoveField(
            model_name='profileentity',
            name='crafting_originated_entity',
        ),
        migrations.AddField(
            model_name='profileentity',
            name='x',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileentity',
            name='y',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CraftingOriginatedEntity',
        ),
        migrations.AddField(
            model_name='profileentity',
            name='crafting_originated_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.craftingoriginatedmaterial'),
        ),
    ]
