# Generated by Django 3.1.5 on 2021-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0014_auto_20210530_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='last_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileentity',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
