# Generated by Django 3.1.5 on 2021-06-29 20:17

from django.db import migrations

def populate_items(apps, schema_editor):

    # We can't import  models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Tinker = apps.get_model('shop', 'Tinker')
    Item = apps.get_model('mining', 'Item')
    for tinker in Tinker.objects.all():
        Item.objects.create(crafting_item=tinker)


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0017_auto_20210629_2208'),
    ]

    operations = [
        migrations.RunPython(populate_items)
    ]




