# Generated by Django 3.1.5 on 2021-07-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0054_auto_20201223_1709'),
        ('mining', '0019_auto_20210701_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relprofile',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.inventory'),
        ),
        migrations.AlterField(
            model_name='relprofile',
            name='spieler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler'),
        ),
    ]
