# Generated by Django 3.1.5 on 2021-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0020_auto_20210701_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='height',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='width',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
