# Generated by Django 4.1.7 on 2023-04-07 19:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0021_auto_20210702_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1024, 1024], upload_to=''),
        ),
    ]
