# Generated by Django 2.2.13 on 2020-10-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20201012_1121'),
        ('crafting', '0002_relcrafting'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Crafter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tinker')),
            ],
        ),
        migrations.DeleteModel(
            name='inventory_item',
        ),
    ]
