# Generated by Django 2.2.13 on 2020-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0004_auto_20201012_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
