# Generated by Django 2.2.13 on 2020-10-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('crafting', '0005_auto_20201012_2103'),
    ]

    operations = [
            migrations.RenameModel('Crafter', 'Profile')
    ]
