# Generated by Django 2.2.13 on 2020-10-18 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0006_auto_20201017_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['char', 'item'], 'verbose_name': 'Inventar Item', 'verbose_name_plural': 'Inventar Items'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='relcrafting',
            options={'ordering': ['spieler'], 'verbose_name': 'Crafting von Spieler', 'verbose_name_plural': 'Crafting von Spielern'},
        ),
        migrations.AddField(
            model_name='profile',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='craftingTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
