# Generated by Django 2.2.13 on 2020-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0007_auto_20201018_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tableOrdering',
            field=models.TextField(default='[]'),
        ),
    ]
