# Generated by Django 2.2.13 on 2020-10-19 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0008_profile_tableordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='electricity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='thermic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='num',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
