# Generated by Django 2.2.13 on 2020-10-20 15:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0052_auto_20200923_1257'),
        ('shop', '0038_auto_20201019_1837'),
        ('crafting', '0009_auto_20201019_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='num',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='herstellungsdauer (dd:hh:mm)')),
                ('spezial', models.ManyToManyField(blank=True, to='character.Spezialfertigkeit')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tinker')),
                ('wissen', models.ManyToManyField(blank=True, to='character.Wissensfertigkeit')),
            ],
            options={
                'verbose_name': 'Rezept',
                'verbose_name_plural': 'Rezepte',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='product', to='shop.Tinker')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Recipe')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', related_query_name='ingredient', to='shop.Tinker')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Recipe')),
            ],
            options={
                'verbose_name': 'Zutat',
                'verbose_name_plural': 'Zutaten',
            },
        ),
    ]
