# Generated by Django 2.2.13 on 2020-10-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0010_auto_20201020_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', related_query_name='prod', to='shop.Tinker'),
        ),
    ]
