# Generated by Django 3.1.7 on 2021-04-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('crafting', '0014_auto_20210407_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialDrops',
            new_name='MaterialDrop',
        ),
    ]
