# Generated by Django 4.2.8 on 2025-03-27 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_remove_zauber_astralsch_is_direct_and_more'),
        ('crafting', '0017_auto_20210425_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[64, 64], upload_to='')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('hardness', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blöcke',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[64, 64], upload_to='')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regionen',
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.block')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
            ],
        ),
        migrations.CreateModel(
            name='BlockChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.PositiveSmallIntegerField(default=1, help_text='Higher is less rare', validators=[django.core.validators.MinValueValidator(1)])),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.block')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.region')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='chance',
            field=models.ManyToManyField(through='crafting.BlockChance', to='crafting.region'),
        ),
        migrations.AddField(
            model_name='block',
            name='drops',
            field=models.ManyToManyField(through='crafting.Drop', to='shop.tinker'),
        ),
    ]
