# Generated by Django 4.2.8 on 2025-03-27 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0018_block_region_drop_blockchance_block_chance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchance',
            options={'ordering': ['-chance'], 'verbose_name': 'Block Chance', 'verbose_name_plural': 'Block Chances'},
        ),
        migrations.AlterModelOptions(
            name='drop',
            options={'ordering': ['-chance'], 'verbose_name': 'Block Drop', 'verbose_name_plural': 'Block Drops'},
        ),
        migrations.AddField(
            model_name='block',
            name='effective_axe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='effective_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='effective_shovel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blockchance',
            name='chance',
            field=models.PositiveSmallIntegerField(default=1, help_text='Higher is appears more often. # copies goes into a pool to randomly select the next block.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
