# Generated by Django 4.2.8 on 2025-03-29 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0023_profile_miningtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='craftingTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='crafting time (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='miningTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='mining time (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='herstellungsdauer (hh:mm:ss)'),
        ),
    ]
