# Generated by Django 4.2.8 on 2025-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0027_alter_miningperk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningperk',
            name='effect',
            field=models.CharField(choices=[('speed', 'Speed'), ('multidrop', 'Multidrop'), ('block_count', 'Block Count'), ('spread', 'Spread')], default='speed', max_length=32),
        ),
    ]
