# Generated by Django 4.2.8 on 2025-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_tinker_wooble_buy_price_tinker_wooble_sell_price'),
        ('crafting', '0028_alter_miningperk_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='permanently_needs',
            field=models.ManyToManyField(blank=True, to='shop.tinker'),
        ),
    ]
