# Generated by Django 4.2.8 on 2025-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0030_alter_tool_options_block_effective_oildrill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Tool Type',
                'verbose_name_plural': 'Tool Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-speed', 'item'], 'verbose_name': 'Werkzeug', 'verbose_name_plural': 'Werkzeuge'},
        ),
        migrations.AddField(
            model_name='block',
            name='effektive_tool',
            field=models.ManyToManyField(to='crafting.tooltype'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_type',
            field=models.ManyToManyField(to='crafting.tooltype'),
        ),
    ]
