# Generated by Django 4.2.8 on 2025-04-06 08:08

from django.db import migrations, models

def migrate_toolType(apps, schema_editor):
    ToolType = apps.get_model('crafting', 'ToolType')

    Block = apps.get_model('crafting', 'Block') # effektive_tool
    Tool = apps.get_model('crafting', 'Tool') # is_type
    MiningPerk = apps.get_model('crafting', 'MiningPerk') # tool_type

    all_types = ToolType.objects.bulk_create([ToolType(name=type) for type in ["pick", "axe", "shovel", "oildrill"]])

    for block in Block.objects.all():
        types = []
        if block.effective_pick: types.append("pick")
        if block.effective_axe: types.append("axe")
        if block.effective_shovel: types.append("shovel")
        if block.effective_oildrill: types.append("oildrill")
        block.effektive_tool.add(*[type for type in all_types if type.name in types])

    for tool in Tool.objects.all():
        types = []
        if tool.is_pick: types.append("pick")
        if tool.is_axe: types.append("axe")
        if tool.is_shovel: types.append("shovel")
        if tool.is_oildrill: types.append("oildrill")
        tool.is_type.add(*[type for type in all_types if type.name in types])

    for perk in MiningPerk.objects.all():
        types = []
        types.append(perk.get_tool_type_display())
        perk.new_tool_type.add(*[type for type in all_types if type.name in types])


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0031_tooltype_alter_tool_options_block_effektive_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningperk',
            name='new_tool_type',
            field=models.ManyToManyField(blank=True, to='crafting.tooltype'),
        ),
        migrations.RunPython(migrate_toolType)
    ]
