# Generated by Django 4.2.8 on 2025-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0034_remove_block_effektive_tool_block_effective_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='effective_tool',
            field=models.ManyToManyField(blank=True, to='crafting.tooltype'),
        ),
    ]
