# Generated by Django 4.2.8 on 2025-07-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0035_alter_block_effective_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['wooble_cost', 'name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regionen'},
        ),
    ]
