# Generated by Django 4.2.8 on 2025-07-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0181_alter_wesen_beschreibung'),
        ('crafting', '0036_alter_region_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcrafting',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.charakter'),
        ),
    ]
