# Generated by Django 4.2.8 on 2025-09-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0041_rename_new_table_recipe_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='duration',
            new_name='durability',
        ),
    ]
