# Generated by Django 4.2.8 on 2025-09-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0042_rename_duration_table_durability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileTableDuration',
            new_name='ProfileTableDurability',
        ),
    ]
