# Generated by Django 4.2.8 on 2025-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0043_rename_profiletableduration_profiletabledurability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tableOrdering',
            field=models.JSONField(default=list),
        ),
    ]
