# Generated by Django 4.2.8 on 2025-09-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_rename_stärke_rüstungen_härte'),
        ('crafting', '0044_alter_profile_tableordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('item', 'part'), 'verbose_name': 'Werkstätte', 'verbose_name_plural': 'Werkstätten'},
        ),
        migrations.AlterField(
            model_name='table',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='shop.tinker'),
        ),
    ]
