# Generated by Django 4.2.8 on 2025-09-10 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0047_alter_runningrealtimerecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningrealtimerecipe',
            options={'ordering': ['profil', 'finishes_at', 'recipe', 'num']},
        ),
        migrations.RenameField(
            model_name='runningrealtimerecipe',
            old_name='finished_at',
            new_name='finishes_at',
        ),
        migrations.RenameField(
            model_name='runningrealtimerecipe',
            old_name='started_at',
            new_name='starts_at',
        ),
        migrations.AddField(
            model_name='runningrealtimerecipe',
            name='begins_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 16, 22, 36, 605451)),
            preserve_default=False,
        ),
    ]
