# Generated by Django 4.1.7 on 2023-12-05 17:41

import dex.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0004_alter_paratierfertigkeit_options_fertigkeit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertigkeit',
            options={'ordering': ['name'], 'verbose_name': 'Fertigkeit', 'verbose_name_plural': 'Fertigkeiten'},
        ),
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1024, 1024], upload_to=dex.models.upload_and_rename_to_id),
        ),
    ]
