# Generated by Django 4.1.7 on 2023-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0005_alter_fertigkeit_options_alter_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='base_schadensWI',
            field=models.ManyToManyField(blank=True, to='dex.dice'),
        ),
    ]
