# Generated by Django 4.1.7 on 2023-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0006_alter_monster_base_schadenswi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterFähigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Fähigkeit',
                'verbose_name_plural': 'Fähigkeiten',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='attacke',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='paratier',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
    ]
