# Generated by Django 4.1.7 on 2023-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0008_alter_monsterfähigkeit_options_monster_fähigkeiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='fähigkeiten',
            field=models.ManyToManyField(blank=True, to='dex.monsterfähigkeit'),
        ),
    ]
