# Generated by Django 4.1.7 on 2023-12-15 16:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0009_alter_monster_fähigkeiten'),
    ]

    operations = [
        migrations.AddField(
            model_name='typ',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='typ',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
