# Generated by Django 4.1.7 on 2023-12-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0013_populate_monsterrang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='type',
            field=models.CharField(choices=[('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W6', 'W6'), ('W8', 'W8'), ('W10', 'W10'), ('W12', 'W12'), ('W20', 'W20'), ('W100', 'W100')], max_length=4),
        ),
    ]
