# Generated by Django 4.2.8 on 2023-12-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0023_alter_monsterteam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterrang',
            name='hp',
        ),
        migrations.AddField(
            model_name='monster',
            name='base_fernkampf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='base_magie',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='base_nahkampf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='base_verteidigung_geistig',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='base_verteidigung_körperlich',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_hp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RangStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('HP', 'HP'), ('N', 'Nahkampf'), ('F', 'Fernkampf'), ('MA', 'Magie'), ('VER_G', 'Verteidigung geistig'), ('VER_K', 'Verteidigung körperlich')], max_length=5)),
                ('wert', models.PositiveSmallIntegerField(default=0)),
                ('skilled', models.BooleanField(default=False)),
                ('trained', models.BooleanField(default=False)),
                ('spielermonster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.spielermonster')),
            ],
            options={
                'verbose_name': 'Rang Stat',
                'verbose_name_plural': 'Rang Stats',
                'ordering': ['spielermonster', 'stat'],
            },
        ),
    ]
