# Generated by Django 4.2.8 on 2023-12-21 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0026_attacke_angriff_fernkampf_attacke_angriff_magie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacke',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
