# Generated by Django 4.2.8 on 2023-12-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0142_charakter_manaoverflow_bonus'),
        ('dex', '0029_spielermonster_attackenpunkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacke',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.spieler'),
        ),
        migrations.AddField(
            model_name='attacke',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
