# Generated by Django 4.2.8 on 2023-12-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0142_charakter_manaoverflow_bonus'),
        ('dex', '0033_alter_geschöpf_gefahrenklasse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geschöpf',
            old_name='schaWI',
            new_name='schadensWI',
        ),
        migrations.AddField(
            model_name='geschöpf',
            name='visible',
            field=models.ManyToManyField(to='character.spieler'),
        ),
    ]
