# Generated by Django 4.2.8 on 2023-12-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0035_alter_geschöpf_options_alter_geschöpf_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spielermonster',
            old_name='attacken',
            new_name='attacken_old',
        ),
    ]
