# Generated by Django 4.2.8 on 2023-12-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0038_auto_20231229_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spielermonster',
            name='attacken_old',
        ),
    ]
