# Generated by Django 4.2.8 on 2024-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0040_alter_geschöpf_gefahrenklasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacke',
            name='monster_feddich',
            field=models.BooleanField(default=False),
        ),
    ]
