# Generated by Django 4.2.8 on 2024-01-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0042_parapflanze_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaPflanzeÖkologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(choices=[('p', 'pH'), ('t', 'Temperatur'), ('l', 'Licht'), ('w', 'Wasser')], max_length=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.parapflanze')),
            ],
            options={
                'verbose_name': 'Para-Pflanzenbild',
                'verbose_name_plural': 'Para-Pflanzenbilder',
                'ordering': ['plant', 'factor'],
                'unique_together': {('plant', 'factor', 'x')},
            },
        ),
    ]
