# Generated by Django 4.2.8 on 2024-01-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0043_parapflanzeökologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parapflanze',
            name='licht',
        ),
        migrations.RemoveField(
            model_name='parapflanze',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='parapflanze',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='parapflanze',
            name='wasser',
        ),
    ]
