# Generated by Django 4.2.8 on 2024-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0143_charakter_sonstiges_alchemie_and_more'),
        ('dex', '0044_remove_parapflanze_licht_remove_parapflanze_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paratier',
            name='visible',
            field=models.ManyToManyField(blank=True, to='character.spieler'),
        ),
        migrations.AlterField(
            model_name='paratier',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
