# Generated by Django 4.2.8 on 2025-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0045_paratier_visible_alter_paratier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacke',
            name='damage',
            field=models.ManyToManyField(blank=True, to='dex.dice', verbose_name='Schaden'),
        ),
    ]
