# Generated by Django 2.0.5 on 2018-11-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('s', 'Shop'), ('o', 'Sonderangebot'), ('a', 'Attribute'), ('f', 'Fertigkeiten'), ('h', 'HPcp'), ('g', 'mehr Geld'), ('c', 'mehr CP'), ('p', 'mehr SP'), ('r', 'mehr Rang'), ('e', 'weniger Geld'), ('k', 'weniger SP'), ('n', 'neuer Nachteil'), ('x', 'Nachteil weg'), ('y', 'neuer Vorteil'), ('z', 'Vorteil weg'), ('t', 'Skilltree'), ('m', 'Manaverbrauch abgezogen'), ('v', 'Magie verloren')], max_length=1)),
                ('kosten', models.TextField()),
                ('notizen', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Charakter')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spieler')),
            ],
        ),
    ]
