# Generated by Django 4.2.8 on 2025-09-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_alter_log_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='art',
            field=models.CharField(choices=[('s', 'Shop'), ('u', 'Auswertung'), ('i', 'Stufenaufstieg'), ('l', 'Klasse verteilt'), ('o', 'Sonderangebot'), ('a', 'Attribute'), ('f', 'Fertigkeiten'), ('h', 'HPcp'), ('g', 'mehr Geld'), ('c', 'mehr CP'), ('b', 'mehr EP'), ('p', 'mehr SP'), ('r', 'mehr Rang'), ('e', 'weniger Geld'), ('k', 'weniger SP'), ('n', 'neuer Nachteil'), ('x', 'Nachteil weg'), ('y', 'neuer Vorteil'), ('z', 'Vorteil weg'), ('t', 'Skilltree'), ('m', 'Manaverbrauch abgezogen'), ('v', 'Magie verloren'), ('d', 'Quiz-Punkte für SP'), ('j', 'Inventar-Item verbraucht'), ('q', 'Inventar-Item angelegt')], max_length=1),
        ),
    ]
