# Generated by Django 5.2.9 on 2026-02-16 12:14

from django.db import migrations, models


def delete_deprecated(apps, schema_editor):
    Log = apps.get_model('log', 'Log')

    Log.objects.filter(art='r').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_alter_log_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='art',
            field=models.CharField(choices=[('s', 'Shop'), ('u', 'Auswertung'), ('i', 'Stufenaufstieg'), ('l', 'Klasse verteilt'), ('o', 'Sonderangebot'), ('a', 'Attribute'), ('f', 'Fertigkeiten'), ('h', 'HPcp'), ('g', 'mehr Geld'), ('c', 'mehr CP'), ('b', 'mehr EP'), ('p', 'mehr SP'), ('e', 'weniger Geld'), ('k', 'weniger SP'), ('n', 'neuer Nachteil'), ('x', 'Nachteil weg'), ('y', 'neuer Vorteil'), ('z', 'Vorteil weg'), ('t', 'Skilltree'), ('m', 'Manaverbrauch abgezogen'), ('v', 'Magie verloren'), ('d', 'Quiz-Punkte für SP'), ('j', 'Inventar-Item verbraucht'), ('q', 'Inventar-Item angelegt'), ('w', 'Inventar-Item verkauft')], max_length=1),
        ),
        migrations.RunPython(delete_deprecated)
    ]
