# Generated by Django 4.1.4 on 2023-02-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0064_gfsstufenplanbase_tp'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='money',
            field=models.BigIntegerField(default=0, verbose_name='Guthaben'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='spieler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.spieler'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Betrag in Dr.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.TextField(max_length=200, verbose_name='Verwendungszweck'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', related_query_name='receiver', to='cards.card', verbose_name='Empfänger'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', related_query_name='sender', to='cards.card', verbose_name='Sender'),
        ),
    ]
