# Generated by Django 4.2.8 on 2025-11-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0187_alter_currentstory_notes'),
        ('cards', '0003_delete_relcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_distributed_to_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.charakter'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', None), models.Q(('char', None), _negated=True)), models.Q(models.Q(('name', None), _negated=True), ('char', None)), _connector='OR'), name='either name or char set', violation_error_message='Entweder Name oder Charakter muss angegeben sein'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', None), ('spieler', None)), models.Q(models.Q(('name', None), _negated=True), models.Q(('spieler', None), _negated=True)), _connector='OR'), name='spieler set exactly when name is set', violation_error_message='Entweder Charakter oder Name mit Spieler muss angegeben sein'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('char', None), ('active', True), _connector='OR'), name="char's account needs to stay active", violation_error_message='Bankaccount eines Charakters muss aktiv sein'),
        ),
    ]
