# Generated by Django 4.2.8 on 2025-11-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', related_query_name='receiver', to='cards.card', verbose_name='Empfänger'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', related_query_name='sender', to='cards.card', verbose_name='Sender'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender', None), _negated=True), models.Q(('receiver', None), _negated=True), _connector='OR'), name='at least one of sender or receiver set', violation_error_message='Mindestens einer von Sender und Empfänger muss gesetzt sein'),
        ),
    ]
