# Generated by Django 2.0.5 on 2018-11-19 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacking',
            fields=[
                ('stufe', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prozession', models.CharField(max_length=5)),
                ('sicherheit', models.CharField(max_length=5)),
                ('speicher', models.CharField(max_length=5)),
                ('projektion', models.CharField(max_length=5)),
                ('wifi', models.CharField(max_length=5)),
                ('upgrades', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'hacking',
                'verbose_name_plural': 'Hacking',
                'ordering': ['stufe'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, null=True)),
                ('beschreibung', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Spieler')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=100, unique=True)),
                ('größe', models.PositiveIntegerField(default=150)),
                ('gewicht', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='gewicht')),
                ('vorkommen', models.TextField(default='', max_length=1000)),
                ('beschreibung', models.TextField(default='', max_length=3000)),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monster',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('magisch', models.BooleanField(default=False)),
                ('größe', models.PositiveIntegerField(default=150)),
                ('gewicht', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='gewicht')),
                ('beschreibung', models.TextField(max_length=3000)),
                ('wesen', models.ManyToManyField(to='character.Spezies')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ['name', 'wesen__titel'],
            },
        ),
        migrations.CreateModel(
            name='Umfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('url', models.URLField(unique_for_date='created')),
            ],
            options={
                'verbose_name': 'Umfrage',
                'verbose_name_plural': 'Umfragen',
                'ordering': ['-created'],
            },
        ),
    ]
