# Generated by Django 2.0.5 on 2018-12-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monster',
        ),
    ]
