# Generated by Django 2.0.4 on 2020-06-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_delete_monster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hacking',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wesen',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
