# Generated by Django 4.2.8 on 2024-01-22 11:04

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0004_delete_umfrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveIntegerField(default=0)),
                ('titel', models.CharField(max_length=256, unique=True)),
                ('text', markdownfield.models.MarkdownField(rendered_field='text_rendered')),
                ('text_rendered', markdownfield.models.RenderedMarkdownField()),
            ],
            options={
                'verbose_name': 'Regel',
                'verbose_name_plural': 'Regeln',
                'ordering': ['nr', 'titel'],
            },
        ),
    ]
