# Generated by Django 4.2.8 on 2024-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_ghost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghost',
            name='schnelligkeit',
        ),
        migrations.AddField(
            model_name='ghost',
            name='eigenschaft',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ghost',
            name='sch',
            field=models.CharField(default='', max_length=64, verbose_name='Schnelligkeit'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='angriff',
            field=models.CharField(default='', max_length=64, verbose_name='Angriff'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='astralschaden',
            field=models.CharField(default='', max_length=64, verbose_name='Astralschaden'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='initiative',
            field=models.CharField(default='', max_length=64, verbose_name='Initiative'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='ma',
            field=models.CharField(default='', max_length=64, verbose_name='Magie'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='reaktion',
            field=models.CharField(default='', max_length=64, verbose_name='Reaktion'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='schaWI',
            field=models.CharField(default='', max_length=64, verbose_name='Schadenswiderstand'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='schaden_pro_erfolg',
            field=models.CharField(default='', max_length=64, verbose_name='Schaden / Erfolg'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='st',
            field=models.CharField(default='', max_length=64, verbose_name='Stärke'),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='wk',
            field=models.CharField(default='', max_length=64, verbose_name='Willenskraft'),
        ),
    ]
