# Generated by Django 4.2.8 on 2024-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_ruletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='text_rendered',
        ),
        migrations.AlterField(
            model_name='rule',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
