# Generated by Django 4.2.8 on 2024-02-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_remove_rule_text_rendered_alter_rule_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ghost',
        ),
        migrations.DeleteModel(
            name='RuleTable',
        ),
    ]
