# Generated by Django 4.2.8 on 2024-01-29 16:09

from django.db import migrations, models
import lerneinheiten.models


class Migration(migrations.Migration):

    dependencies = [
        ('lerneinheiten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einheit',
            name='number',
            field=models.PositiveIntegerField(default=lerneinheiten.models.next_einheit_number),
        ),
    ]
