# Generated by Django 4.2.8 on 2024-02-04 15:33

from django.db import migrations, models
import django.db.models.deletion
import lerneinheiten.models


class Migration(migrations.Migration):

    dependencies = [
        ('lerneinheiten', '0003_alter_page_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='page',
            name='solution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lerneinheiten.models.pageimage_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerneinheiten.page')),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
