# Generated by Django 4.2.8 on 2024-02-05 12:36

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerneinheiten', '0004_alter_page_content_alter_page_solution_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='page',
            name='solution',
            field=models.JSONField(blank=True, default=dict, verbose_name='Musterlösung'),
        ),
    ]
