# Generated by Django 4.2.8 on 2024-04-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerneinheiten', '0007_alter_inquiry_question_alter_inquiry_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='spielerPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lerneinheiten.spielerpage'),
        ),
    ]
