# Generated by Django 4.2.8 on 2025-07-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0181_alter_wesen_beschreibung'),
        ('crafting', '0036_alter_region_options'),
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.SmallIntegerField(default=200, help_text='100 ^= 1 Feld')),
                ('hp', models.SmallIntegerField(default=10)),
                ('defense', models.SmallIntegerField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.profile')),
            ],
            options={
                'ordering': ['char', 'profil'],
            },
        ),
    ]
