# Generated by Django 4.2.8 on 2025-08-10 14:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Farbe')),
                ('textColor', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Textfarbe')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeinterval',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', models.F('end'))), name='ends_not_earlier_than_start'),
        ),
    ]
