# Generated by Django 4.2.8 on 2025-08-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timeinterval',
            options={'ordering': ['start', 'end', 'category']},
        ),
    ]
