# Generated by Django 3.1.7 on 2022-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0005_auto_20210103_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Duplikator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Linearriss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liniendeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manabomb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManaDegenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Splinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timedelayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timelagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='[]')),
                ('next', models.TextField(default='[]')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
