# Generated by Django 3.1.7 on 2022-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_space', '0007_auto_20220407_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='looper',
            name='outputs',
            field=models.JSONField(default=list),
        ),
    ]
