# Generated by Django 2.0.5 on 2019-03-13 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic', 'grade'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'grade', 'topic')},
        ),
    ]
