# Generated by Django 2.0.5 on 2019-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190318_0201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'grade', 'topic', 'picture')},
        ),
    ]
