# Generated by Django 2.0.5 on 2019-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190319_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='message_on_wrong_answered',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
