# Generated by Django 2.0.5 on 2019-04-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190328_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielerquestion',
            name='num_correctly',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
