# Generated by Django 2.0.5 on 2019-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190416_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='release',
            field=models.BooleanField(default=True),
        ),
    ]
