# Generated by Django 2.0.5 on 2019-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_question_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
