# Generated by Django 2.2.13 on 2020-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200601_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
