# Generated by Django 2.2.13 on 2020-09-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200730_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('reward', models.TextField()),
                ('description', models.TextField()),
                ('prerequisite_modules', models.ManyToManyField(to='quiz.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='release',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Module')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='questions',
            field=models.ManyToManyField(through='quiz.ModuleQuestion', to='quiz.Question'),
        ),
    ]
