# Generated by Django 2.2.13 on 2020-09-07 13:25

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20200907_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='num',
            field=models.FloatField(default=quiz.models.next_id, unique=True),
        ),
    ]
