# Generated by Django 2.2.13 on 2020-09-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0049_remove_spieler_p_quiz_points_achieved'),
        ('quiz', '0025_auto_20200910_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.Question')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Module')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spieler')),
            ],
            options={
                'ordering': ['spieler'],
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'unique_together': {('spieler',)},
            },
        ),
        migrations.CreateModel(
            name='SpielerModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'locked'), (1, 'unlocked'), (2, 'opened'), (3, 'answered'), (4, 'corrected'), (5, 'seen'), (6, 'passed')], default=0)),
                ('achieved_points', models.FloatField(default=0.0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Module')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spieler')),
            ],
            options={
                'ordering': ['spieler', 'module'],
                'verbose_name': "Spieler's Module",
                'verbose_name_plural': "Spieler's Module",
                'unique_together': {('spieler', 'module')},
            },
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='MultipleChoiceField',
        ),
        migrations.RemoveField(
            model_name='deleteablem2m_spielerquestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='deleteablem2m_spielerquestion',
            name='spielerQuestion',
        ),
        migrations.AlterUniqueTogether(
            name='questionsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionsession',
            name='actual_question',
        ),
        migrations.RemoveField(
            model_name='questionsession',
            name='questions_to_answer',
        ),
        migrations.RemoveField(
            model_name='questionsession',
            name='results',
        ),
        migrations.RemoveField(
            model_name='questionsession',
            name='spieler',
        ),
        migrations.AlterUniqueTogether(
            name='spielerquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='spielerquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='spielerquestion',
            name='spieler',
        ),
        migrations.DeleteModel(
            name='DeleteableM2M_Question',
        ),
        migrations.DeleteModel(
            name='DeleteableM2M_SpielerQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionSession',
        ),
        migrations.DeleteModel(
            name='SpielerQuestion',
        ),
    ]
