# Generated by Django 2.2.13 on 2020-09-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20200910_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicefield',
            old_name='img',
            new_name='picture',
        ),
    ]
