# Generated by Django 2.2.13 on 2020-09-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20200910_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicefield',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Image'),
        ),
    ]
