# Generated by Django 2.2.13 on 2020-09-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0049_remove_spieler_p_quiz_points_achieved'),
        ('quiz', '0038_auto_20200912_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='relquiz',
            name='spieler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spieler'),
        ),
    ]
