# Generated by Django 2.2.13 on 2020-09-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20200912_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relquiz',
            options={'ordering': ['spieler'], 'verbose_name': 'Spieler Stats', 'verbose_name_plural': 'Spieler Stats'},
        ),
        migrations.AlterField(
            model_name='question',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.File'),
        ),
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Image'),
        ),
        migrations.AlterField(
            model_name='relquiz',
            name='spieler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spieler', unique=True),
        ),
    ]
