# Generated by Django 2.2.13 on 2020-09-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20200913_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'Datei', 'verbose_name_plural': 'Dateien'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name'], 'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['num'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.AlterModelOptions(
            name='modulequestion',
            options={'verbose_name': 'Frage eines Moduls', 'verbose_name_plural': 'Fragen eines Moduls'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicefield',
            options={'ordering': ['to_question', 'text'], 'verbose_name': 'Multiple Choice Möglichkeit', 'verbose_name_plural': 'Multiple Choice Möglichkeiten'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic', 'grade'], 'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={'ordering': ['spielerModule', '-started'], 'verbose_name': 'Moduldurchlauf eines Spielers', 'verbose_name_plural': 'Moduldurchläufe eines Spielers'},
        ),
        migrations.AlterModelOptions(
            name='spielermodule',
            options={'ordering': ['spieler', 'state', 'module'], 'verbose_name': 'Modulstatus eines Spielers', 'verbose_name_plural': 'Modulstati eines Spielers'},
        ),
        migrations.AlterModelOptions(
            name='spielerquestion',
            options={'verbose_name': 'Fragendurchlauf eines Spielers', 'verbose_name_plural': 'Fragendurchläufe eines Spielers'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['titel'], 'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'titel'], 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
    ]
