# Generated by Django 2.2.14 on 2020-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_auto_20200923_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielersession',
            name='current_question',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
