# Generated by Django 2.2.13 on 2020-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_spielerquestion_achieved_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielermodule',
            name='achieved_points',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='achieved_points',
            field=models.FloatField(default=0),
        ),
    ]
