# Generated by Django 2.2.13 on 2020-12-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_auto_20201004_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielerquestion',
            name='correct_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_file', to='quiz.File'),
        ),
        migrations.AddField(
            model_name='spielerquestion',
            name='correct_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_img', to='quiz.Image'),
        ),
        migrations.AddField(
            model_name='spielerquestion',
            name='correct_mc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spielerquestion',
            name='correct_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='achieved_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='answer_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_file', to='quiz.File'),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='answer_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_img', to='quiz.Image'),
        ),
    ]
