# Generated by Django 2.2.13 on 2020-12-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20201206_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
