# Generated by Django 2.2.13 on 2020-12-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_remove_question_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spielermodule',
            options={'ordering': ['spieler', 'module'], 'verbose_name': 'Modulstatus eines Spielers', 'verbose_name_plural': 'Modulstati eines Spielers'},
        ),
        migrations.RemoveField(
            model_name='relquiz',
            name='quiz_points',
        ),
    ]
