# Generated by Django 2.2.13 on 2020-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0057_auto_20201207_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulequestion',
            options={'ordering': ['module'], 'verbose_name': 'Frage eines Moduls', 'verbose_name_plural': 'Fragen eines Moduls'},
        ),
        migrations.AlterModelOptions(
            name='spielerquestion',
            options={'ordering': ['spieler', 'module__set', 'question'], 'verbose_name': 'Fragendurchlauf eines Spielers', 'verbose_name_plural': 'Fragendurchläufe eines Spielers'},
        ),
        migrations.AddField(
            model_name='spielermodule',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
