# Generated by Django 2.2.13 on 2020-12-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0058_auto_20201212_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spielerquestion',
            options={'ordering': ['spieler', 'question'], 'verbose_name': 'Fragendurchlauf eines Spielers', 'verbose_name_plural': 'Fragendurchläufe eines Spielers'},
        ),
    ]
