# Generated by Django 3.1.4 on 2020-12-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_auto_20201216_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulequestion',
            options={'ordering': ['module', 'id'], 'verbose_name': 'Frage eines Moduls', 'verbose_name_plural': 'Fragen eines Moduls'},
        ),
        migrations.AlterModelOptions(
            name='spielerquestion',
            options={'ordering': ['spieler', 'id'], 'verbose_name': 'Fragendurchlauf eines Spielers', 'verbose_name_plural': 'Fragendurchläufe eines Spielers'},
        ),
    ]
