# Generated by Django 3.1.4 on 2021-01-02 16:00

from django.db import migrations, models


def set_to_default(apps, schema_editor):
    # We can't import  models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SpielerQuestion = apps.get_model('quiz', 'SpielerQuestion')
    for spq in SpielerQuestion.objects.all():
        if spq.answer_mc is None: spq.answer_mc = '[]'
        if spq.correct_mc is None: spq.correct_mc = '[]'
        spq.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20210102_1340'),
    ]

    operations = [
        migrations.RunPython(set_to_default),
        migrations.AlterField(
            model_name='spielerquestion',
            name='answer_mc',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='spielerquestion',
            name='correct_mc',
            field=models.TextField(default='[]'),
        ),
    ]
