# Generated by Django 3.1.4 on 2021-01-02 16:00

from quiz.models import ModuleQuestion
from django.db import migrations, models


def set_asc_num_on_questions(apps, schema_editor):
    # We can't import  models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Module = apps.get_model('quiz', 'Module')
    ModuleQuestion = apps.get_model('quiz', 'ModuleQuestion')
    for module in Module.objects.all():
        num = 0

        for module_question in ModuleQuestion.objects.filter(module=module):
            module_question.num = num

            num += 1
            module_question.save()



class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0064_auto_20210102_1700'),
    ]

    operations = [
        migrations.RunPython(set_asc_num_on_questions)
    ]
