# Generated by Django 3.1.4 on 2021-01-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0065_ordering_questions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulequestion',
            unique_together={('module', 'num'), ('module', 'question')},
        ),
    ]
