# Generated by Django 2.2.13 on 2020-10-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20201012_1121'),
        ('crafting', '0003_auto_20201012_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crafter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['char', 'item']},
        ),
        migrations.AlterModelOptions(
            name='relcrafting',
            options={'ordering': ['spieler']},
        ),
        migrations.AlterField(
            model_name='crafter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='relcrafting',
            name='spieler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.Spieler'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('char', 'item')},
        ),
    ]
