# Generated by Django 3.1.7 on 2021-04-07 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('crafting', '0011_auto_20201022_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('rigidity', models.PositiveIntegerField(default=10)),
                ('spawn_chance', models.FloatField(default=0.0)),
                ('second_spawn_chance', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('tier', models.PositiveIntegerField(default=0)),
                ('tools', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materialien',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regionen',
            },
        ),
        migrations.CreateModel(
            name='MaterialDrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField(default='[1]')),
                ('item', models.ManyToManyField(to='shop.Tinker')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.region'),
        ),
    ]
