# Generated by Django 3.1.7 on 2021-04-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0012_auto_20210407_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='img',
            new_name='icon',
        ),
    ]
