# Generated by Django 3.1.7 on 2021-04-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('crafting', '0013_auto_20210407_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdrops',
            name='item',
        ),
        migrations.AddField(
            model_name='materialdrops',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.tinker'),
        ),
    ]
