# Generated by Django 3.1.7 on 2021-04-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201111_2045'),
        ('crafting', '0015_auto_20210407_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdrop',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tinker'),
        ),
    ]
