# Generated by Django 4.2.8 on 2025-03-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_remove_zauber_astralsch_is_direct_and_more'),
        ('crafting', '0019_alter_blockchance_options_alter_drop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField(default=1)),
                ('is_pick', models.BooleanField(default=False)),
                ('is_axe', models.BooleanField(default=False)),
                ('is_shovel', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
            ],
            options={
                'verbose_name': 'Werkzeug',
                'verbose_name_plural': 'Werkzeuge',
                'ordering': ['speed'],
            },
        ),
    ]
