# Generated by Django 4.2.8 on 2025-03-27 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0020_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, to='crafting.profile'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='chance',
            field=models.FloatField(default=50, help_text='Probabiliy of (0%, 100%]', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
