# Generated by Django 4.2.8 on 2025-03-28 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0022_alter_tool_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='miningTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
