# Generated by Django 4.2.8 on 2025-03-29 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0024_alter_profile_craftingtime_alter_profile_miningtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='woobles',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
