# Generated by Django 4.2.8 on 2025-03-29 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0025_profile_woobles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('beschreibung', models.TextField()),
                ('wooble_price', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Mining-Perk',
                'verbose_name_plural': 'Mining-Perks',
                'ordering': ['region', 'name', 'wooble_price'],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='wooble_cost',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='RelMiningPerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutfe', models.PositiveSmallIntegerField(default=1)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.miningperk')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.profile')),
            ],
        ),
        migrations.AddField(
            model_name='miningperk',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='miningPerks',
            field=models.ManyToManyField(blank=True, through='crafting.RelMiningPerk', to='crafting.miningperk'),
        ),
        migrations.AlterUniqueTogether(
            name='miningperk',
            unique_together={('region', 'name')},
        ),
    ]
