# Generated by Django 4.2.8 on 2025-03-30 09:14

import crafting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_tinker_wooble_buy_price_tinker_wooble_sell_price'),
        ('crafting', '0026_miningperk_region_wooble_cost_relminingperk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningperk',
            options={'ordering': ['region', 'effect', 'item__name', 'tool_type'], 'verbose_name': 'Mining-Perk', 'verbose_name_plural': 'Mining-Perks'},
        ),
        migrations.AlterUniqueTogether(
            name='miningperk',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='miningPerks',
        ),
        migrations.AddField(
            model_name='miningperk',
            name='effect',
            field=models.CharField(choices=[('speed', 'Speed'), ('multidrop', 'Multidrop'), ('block', 'Block'), ('count', 'Count'), ('spread', 'Spread')], default='speed', max_length=32),
        ),
        migrations.AddField(
            model_name='miningperk',
            name='effect_increment',
            field=models.JSONField(default=crafting.models.MiningPerk.default_perk_dict),
        ),
        migrations.AddField(
            model_name='miningperk',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tinker'),
        ),
        migrations.AddField(
            model_name='miningperk',
            name='stufe_wooble_price',
            field=models.JSONField(default=crafting.models.MiningPerk.default_perk_dict),
        ),
        migrations.AddField(
            model_name='miningperk',
            name='tool_type',
            field=models.CharField(blank=True, choices=[('pick', 'Pick'), ('axe', 'Axe'), ('shovel', 'Shovel')], max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='miningperk',
            unique_together={('effect', 'tool_type', 'region')},
        ),
        migrations.DeleteModel(
            name='RelMiningPerk',
        ),
        migrations.RemoveField(
            model_name='miningperk',
            name='name',
        ),
        migrations.RemoveField(
            model_name='miningperk',
            name='wooble_price',
        ),
    ]
