# Generated by Django 4.2.8 on 2025-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0029_region_permanently_needs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-speed', '-is_pick', '-is_axe', '-is_shovel', '-is_oildrill'], 'verbose_name': 'Werkzeug', 'verbose_name_plural': 'Werkzeuge'},
        ),
        migrations.AddField(
            model_name='block',
            name='effective_oildrill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_oildrill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='miningperk',
            name='tool_type',
            field=models.CharField(blank=True, choices=[('pick', 'Pick'), ('axe', 'Axe'), ('shovel', 'Shovel'), ('oildrill', 'Oildrill')], max_length=32, null=True),
        ),
    ]
