# Generated by Django 4.2.8 on 2025-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0032_auto_20250406_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningperk',
            options={'ordering': ['region', 'effect', 'item__name', 'tool_type__name'], 'verbose_name': 'Mining-Perk', 'verbose_name_plural': 'Mining-Perks'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-speed', 'is_type__name', 'item'], 'verbose_name': 'Werkzeug', 'verbose_name_plural': 'Werkzeuge'},
        ),
        migrations.AlterUniqueTogether(
            name='miningperk',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='block',
            name='effective_axe',
        ),
        migrations.RemoveField(
            model_name='block',
            name='effective_oildrill',
        ),
        migrations.RemoveField(
            model_name='block',
            name='effective_pick',
        ),
        migrations.RemoveField(
            model_name='block',
            name='effective_shovel',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_axe',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_oildrill',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_pick',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_shovel',
        ),
        migrations.RemoveField(
            model_name='miningperk',
            name='new_tool_type',
        ),
        migrations.RemoveField(
            model_name='miningperk',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='miningperk',
            name='tool_type',
            field=models.ManyToManyField(blank=True, to='crafting.tooltype'),
        ),
    ]
