# Generated by Django 4.2.8 on 2025-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0037_relcrafting_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='relcrafting',
            name='favorite_recipes',
            field=models.ManyToManyField(to='crafting.recipe'),
        ),
    ]
