# Generated by Django 4.2.8 on 2025-09-05 08:14

from django.db import migrations, models
import django.db.models.deletion

def migrate_tables(apps, schema_editor):
    Recipe = apps.get_model('crafting', 'Recipe')
    Table = apps.get_model('crafting', 'Table')

    for recipe in Recipe.objects.prefetch_related("table").exclude(table=None):
        table, _ = Table.objects.get_or_create(item=recipe.table)
        recipe.new_table = table

        recipe.save(update_fields=["new_table"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_rename_stärke_rüstungen_härte'),
        ('crafting', '0038_relcrafting_favorite_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='in #Rezepte')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tinker')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='shop.tinker')),
            ],
            options={
                'verbose_name': 'Werkstätte',
                'verbose_name_plural': 'Werkstätten',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='new_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.table'),
        ),
        migrations.CreateModel(
            name='ProfileTableDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes_crafted', models.PositiveIntegerField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.profile')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.table')),
            ],
            options={
                'ordering': ['char', 'table'],
                'unique_together': {('char', 'table')},
            },
        ),
        migrations.RunPython(migrate_tables),
    ]
