# Generated by Django 4.2.8 on 2025-09-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0039_table_recipe_new_table_profiletableduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='table',
        ),
    ]
