# Generated by Django 4.2.8 on 2025-09-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0040_remove_recipe_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='new_table',
            new_name='table',
        ),
    ]
