# Generated by Django 4.2.8 on 2025-09-08 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0045_alter_table_options_alter_table_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningRealtimeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('finished_at', models.DateTimeField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.recipe')),
            ],
        ),
    ]
