# Generated by Django 4.2.8 on 2025-09-08 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0046_runningrealtimerecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningrealtimerecipe',
            options={'ordering': ['profil', 'finished_at', 'recipe', 'num']},
        ),
        migrations.AddField(
            model_name='runningrealtimerecipe',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 8, 13, 7, 21, 936246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
