# Generated by Django 4.2.8 on 2025-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0048_alter_runningrealtimerecipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningrealtimerecipe',
            name='lock',
            field=models.TextField(blank=True, null=True),
        ),
    ]
