# Generated by Django 4.2.8 on 2024-09-09 18:50

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightwing_tendency', models.FloatField(default=0, unique=True)),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('name', models.TextField()),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partei',
                'verbose_name_plural': 'Parteien',
                'ordering': ['rightwing_tendency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to='')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('is_party_lead', models.BooleanField(default=False)),
                ('genere', models.CharField(blank=True, max_length=64, null=True)),
                ('birthyear', models.BigIntegerField(blank=True, null=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='politics.party')),
            ],
            options={
                'verbose_name': 'Politiker*in',
                'verbose_name_plural': 'Politiker*innen',
                'ordering': ['name', '-birthyear'],
            },
        ),
    ]
