# Generated by Django 4.2.8 on 2024-09-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0003_legalact_politicianvote_legalact_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='member_of_parliament',
            field=models.BooleanField(default=True),
        ),
    ]
