# Generated by Django 4.2.8 on 2024-09-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0004_politician_member_of_parliament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalact',
            name='voting_deadline',
        ),
    ]
