# Generated by Django 2.0.5 on 2019-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190313_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsession',
            old_name='achieved',
            new_name='achieved_points',
        ),
        migrations.RenameField(
            model_name='questionsession',
            old_name='max',
            new_name='max_points',
        ),
        migrations.AddField(
            model_name='questionsession',
            name='questions_to_answer',
            field=models.ManyToManyField(related_name='questions_to_answer', related_query_name='questions_to_answer', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='start_num_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
