# Generated by Django 2.0.5 on 2019-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190315_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsession',
            name='questions_to_answer',
            field=models.ManyToManyField(related_name='questions_to_answer', related_query_name='questions_to_answer', through='quiz.DeleteableM2M_Question', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='results',
            field=models.ManyToManyField(related_name='results', related_query_name='results', through='quiz.DeleteableM2M_SpielerQuestion', to='quiz.SpielerQuestion'),
        ),
    ]
