# Generated by Django 2.0.5 on 2019-03-15 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_deleteablem2m_spielerquestion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
