# Generated by Django 2.0.5 on 2019-03-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190315_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
