# Generated by Django 2.0.5 on 2019-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20190416_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielerquestion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
