# Generated by Django 2.2.13 on 2020-09-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200907_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='notizen_nie_angezeigt',
            new_name='answer_note',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='beantwortet_von',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
    ]
