# Generated by Django 2.2.13 on 2020-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20200910_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='picture',
            new_name='img',
        ),
        migrations.AddField(
            model_name='question',
            name='allow_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='message_on_wrong_answered',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='notizen_nie_angezeigt',
        ),
    ]
