# Generated by Django 2.2.13 on 2020-09-10 14:08

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_module_max_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=quiz.models.upload_and_rename_picture)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=quiz.models.upload_and_rename_picture)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.ManyToManyField(to='quiz.File'),
        ),
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(to='quiz.Image'),
        ),
    ]
