# Generated by Django 2.2.13 on 2020-09-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0049_remove_spieler_p_quiz_points_achieved'),
        ('quiz', '0037_auto_20200910_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsession',
            options={'ordering': ['spielerModule', '-started'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RenameField(
            model_name='quizsession',
            old_name='actual_question',
            new_name='current_question',
        ),
        migrations.RemoveField(
            model_name='spielermodule',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='spielerModule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SpielerModule'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spielermodule',
            name='sessions',
            field=models.ManyToManyField(to='quiz.QuizSession'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsession',
            unique_together={('spielerModule', 'started')},
        ),
        migrations.CreateModel(
            name='SpielerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spieler')),
            ],
        ),
        migrations.CreateModel(
            name='RelQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_points', models.IntegerField(blank=True, default=0)),
                ('quiz_points_achieved', models.IntegerField(blank=True, default=0)),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.QuizSession')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='module',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='spieler',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(to='quiz.SpielerQuestion'),
        ),
    ]
