# Generated by Django 2.2.13 on 2020-09-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_relquiz_spieler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='current_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_question', to='quiz.SpielerQuestion'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='quiz.SpielerQuestion'),
        ),
    ]
