# Generated by Django 2.2.13 on 2020-09-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_auto_20200912_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicefield',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='question',
            name='picture',
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisite_modules',
            field=models.ManyToManyField(blank=True, to='quiz.Module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='files',
            field=models.ManyToManyField(blank=True, to='quiz.File'),
        ),
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, to='quiz.Image'),
        ),
        migrations.AlterField(
            model_name='relquiz',
            name='spieler',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Spieler'),
        ),
    ]
