# Generated by Django 2.2.13 on 2020-09-13 10:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('quiz', '0043_auto_20200913_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSession',
            new_name='SpielerSession',
        ),
    ]
