# Generated by Django 2.2.13 on 2020-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_auto_20200913_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielersession',
            name='current_question',
            field=models.SmallIntegerField(blank=True, default=-1),
        ),
    ]
