# Generated by Django 2.2.13 on 2020-09-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20200923_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='icon',
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', related_query_name='icon', to='quiz.Image'),
        ),
    ]
