# Generated by Django 2.2.13 on 2020-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_auto_20200928_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielerquestion',
            name='achieved_points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
