# Generated by Django 2.2.13 on 2020-10-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20201004_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielersession',
            name='current_question',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
