# Generated by Django 2.2.13 on 2020-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_auto_20201203_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
