# Generated by Django 2.2.13 on 2020-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0059_auto_20201212_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielermodule',
            name='spent_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spielermodule',
            name='spent_reward_larp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spielermodule',
            name='spent_reward_on',
            field=models.TextField(blank=True, null=True),
        ),
    ]
