# Generated by Django 4.1.7 on 2023-04-07 19:33

from django.db import migrations
import django_resized.forms
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0066_auto_20210102_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[512, 512], upload_to=quiz.models.upload_and_rename_picture),
        ),
    ]
