# Generated by Django 4.2.8 on 2024-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0004_alter_effect_options_releffect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releffect',
            options={'verbose_name': 'Charakter-Effekt', 'verbose_name_plural': 'Charakter-Effekte'},
        ),
        migrations.AlterField(
            model_name='releffect',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
