# Generated by Django 4.2.8 on 2024-05-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0147_gfsability_has_implementation'),
        ('effect', '0006_effect_source_talent_releffect_source_talent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='source_gfsAbility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.gfsability'),
        ),
        migrations.AddField(
            model_name='releffect',
            name='source_gfsAbility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.relgfsability'),
        ),
    ]
