# Generated by Django 4.2.8 on 2024-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0009_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ['target_fieldname'], 'verbose_name': 'Effekt', 'verbose_name_plural': 'Effekte'},
        ),
        migrations.AlterModelOptions(
            name='releffect',
            options={'ordering': ['target_fieldname'], 'verbose_name': 'Charakter-Effekt', 'verbose_name_plural': 'Charakter-Effekte'},
        ),
        migrations.AddField(
            model_name='effect',
            name='has_custom_implementation',
            field=models.BooleanField(default=False),
        ),
    ]
