# Generated by Django 4.2.8 on 2024-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0014_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='wertaenderung',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='releffect',
            name='wertaenderung',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
