# Generated by Django 4.2.27 on 2025-12-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_rüstung_remove_rüstungen_firmen_and_more'),
        ('effect', '0020_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='source_shopRüstung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.rüstung'),
        ),
    ]
