# Generated by Django 5.2.9 on 2026-02-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0025_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='wertaenderung',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Wertänderung'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='wertaenderung_str',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Wertänderung (str)'),
        ),
        migrations.AlterField(
            model_name='releffect',
            name='wertaenderung',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Wertänderung'),
        ),
        migrations.AlterField(
            model_name='releffect',
            name='wertaenderung_str',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Wertänderung (str)'),
        ),
    ]
