# Generated by Django 5.2.9 on 2026-02-19 12:43

from django.db import migrations, models


def delete_deprecated(apps, schema_editor):
    Effect = apps.get_model('effect', 'Effect')
    RelEffect = apps.get_model('effect', 'RelEffect')

    changes = [
        ("character.Charakter.natürlicher_schadenswiderstand_bonus", "character.Charakter.physischer_widerstand_bonus"),
        ("character.Charakter.natürlicher_schadenswiderstand_bonus_str", "character.Charakter.physischer_widerstand_bonus_str"),
        ("character.Charakter.astralwiderstand_bonus", "character.Charakter.astraler_widerstand_bonus"),
        ("character.Charakter.astralwiderstand_bonus_str", "character.Charakter.astraler_widerstand_bonus_str"),
    ]

    for old, new in changes:
        Effect.objects.filter(target_fieldname=old).update(target_fieldname=new)
        RelEffect.objects.filter(target_fieldname=old).update(target_fieldname=new)



class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0026_alter_effect_wertaenderung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='target_fieldname',
            field=models.CharField(choices=[('character.RelAttribut.aktuellerWert', 'Attribut: Wert'), ('character.RelAttribut.aktuellerWert_fix', 'Attribut: Wert fix'), ('character.RelAttribut.aktuellerWert_bonus', 'Attribut: Bonus'), ('character.RelAttribut.maxWert', 'Attribut: Maximum'), ('character.RelAttribut.maxWert_fix', 'Attribut: Maximum fix'), ('character.RelFertigkeit.fp', 'Fertigkeit: FP'), ('character.RelFertigkeit.fp_bonus', 'Fertigkeit: Bonus'), ('character.Charakter.ap', 'Charakter: AP'), ('character.Charakter.ip', 'Charakter: IP'), ('character.Charakter.fp', 'Charakter: FP'), ('character.Charakter.fg', 'Charakter: FG'), ('character.Charakter.tp', 'Charakter: TP'), ('character.Charakter.sp', 'Charakter: SP'), ('character.Charakter.sp_fix', 'Charakter: SP fix'), ('cards.Card.money', 'Charakter: Geld'), ('character.Charakter. Konto', 'Charakter: neuer Kontostand (-> Geld)'), ('character.Charakter.prestige', 'Charakter: Prestige'), ('character.Charakter.verzehr', 'Charakter: Verzehr'), ('character.Charakter.sanität', 'Charakter: Sanität'), ('character.Charakter.glück', 'Charakter: Glück'), ('character.Charakter.sonstiger_manifestverlust', 'Charakter: Manifestverlust'), ('character.Charakter.manifest_fix', 'Charakter: Manifest fix'), ('character.Charakter.speed_laufen_bonus', 'Charakter: Bewegung Laufen Bonus'), ('character.Charakter.speed_schwimmen_bonus', 'Charakter: Bewegung Schwimmen Bonus'), ('character.Charakter.speed_fliegen_bonus', 'Charakter: Bewegung Fliegen Bonus'), ('character.Charakter.speed_astral_bonus', 'Charakter: Bewegung Astral Bonus'), ('character.Charakter.HPplus', 'Charakter: kHP plus'), ('character.Charakter.HPplus_fix', 'Charakter: kHP plus fix'), ('character.Charakter.HPplus_geistig', 'Charakter: gHP plus'), ('character.Charakter.crit_attack', 'Charakter: Crit-Angriff'), ('character.Charakter.crit_defense', 'Charakter: Crit-Verteidigung'), ('character.Charakter.wesenschaden_waff_kampf', 'Charakter: Schaden waffenloser Kampf'), ('character.Charakter.wesenschaden_andere_gestalt', 'Charakter: Schaden waffenloser Kampf (andere Form)'), ('character.Charakter.konzentration', 'Charakter: Konzentration'), ('character.Charakter.konzentration_fix', 'Charakter: Konzentration fix'), ('character.Charakter.initiative_bonus', 'Charakter: Initiative-Bonus'), ('character.Charakter.reaktion_bonus', 'Charakter: physische Reaktion-Bonus'), ('character.Charakter.physischer_widerstand_bonus', 'Charakter: physischer Widerstand-Bonus'), ('character.Charakter.physischer_widerstand_bonus_str', 'Charakter: physischer Widerstand-Bonus Text'), ('character.Charakter.astraler_widerstand_bonus', 'Charakter: astraler Widerstand-Bonus'), ('character.Charakter.astraler_widerstand_bonus_str', 'Charakter: astraler Widerstand-Bonus Text'), ('character.Charakter.manaoverflow_bonus', 'Charakter: Manaoverflow-Bonus'), ('character.Charakter.nat_regeneration_bonus', 'Charakter: nat. Regeneration-Bonus'), ('character.Charakter.immunsystem_bonus', 'Charakter: Immunsystem-Bonus')]),
        ),
        migrations.AlterField(
            model_name='releffect',
            name='target_fieldname',
            field=models.CharField(choices=[('character.RelAttribut.aktuellerWert', 'Attribut: Wert'), ('character.RelAttribut.aktuellerWert_fix', 'Attribut: Wert fix'), ('character.RelAttribut.aktuellerWert_bonus', 'Attribut: Bonus'), ('character.RelAttribut.maxWert', 'Attribut: Maximum'), ('character.RelAttribut.maxWert_fix', 'Attribut: Maximum fix'), ('character.RelFertigkeit.fp', 'Fertigkeit: FP'), ('character.RelFertigkeit.fp_bonus', 'Fertigkeit: Bonus'), ('character.Charakter.ap', 'Charakter: AP'), ('character.Charakter.ip', 'Charakter: IP'), ('character.Charakter.fp', 'Charakter: FP'), ('character.Charakter.fg', 'Charakter: FG'), ('character.Charakter.tp', 'Charakter: TP'), ('character.Charakter.sp', 'Charakter: SP'), ('character.Charakter.sp_fix', 'Charakter: SP fix'), ('cards.Card.money', 'Charakter: Geld'), ('character.Charakter. Konto', 'Charakter: neuer Kontostand (-> Geld)'), ('character.Charakter.prestige', 'Charakter: Prestige'), ('character.Charakter.verzehr', 'Charakter: Verzehr'), ('character.Charakter.sanität', 'Charakter: Sanität'), ('character.Charakter.glück', 'Charakter: Glück'), ('character.Charakter.sonstiger_manifestverlust', 'Charakter: Manifestverlust'), ('character.Charakter.manifest_fix', 'Charakter: Manifest fix'), ('character.Charakter.speed_laufen_bonus', 'Charakter: Bewegung Laufen Bonus'), ('character.Charakter.speed_schwimmen_bonus', 'Charakter: Bewegung Schwimmen Bonus'), ('character.Charakter.speed_fliegen_bonus', 'Charakter: Bewegung Fliegen Bonus'), ('character.Charakter.speed_astral_bonus', 'Charakter: Bewegung Astral Bonus'), ('character.Charakter.HPplus', 'Charakter: kHP plus'), ('character.Charakter.HPplus_fix', 'Charakter: kHP plus fix'), ('character.Charakter.HPplus_geistig', 'Charakter: gHP plus'), ('character.Charakter.crit_attack', 'Charakter: Crit-Angriff'), ('character.Charakter.crit_defense', 'Charakter: Crit-Verteidigung'), ('character.Charakter.wesenschaden_waff_kampf', 'Charakter: Schaden waffenloser Kampf'), ('character.Charakter.wesenschaden_andere_gestalt', 'Charakter: Schaden waffenloser Kampf (andere Form)'), ('character.Charakter.konzentration', 'Charakter: Konzentration'), ('character.Charakter.konzentration_fix', 'Charakter: Konzentration fix'), ('character.Charakter.initiative_bonus', 'Charakter: Initiative-Bonus'), ('character.Charakter.reaktion_bonus', 'Charakter: physische Reaktion-Bonus'), ('character.Charakter.physischer_widerstand_bonus', 'Charakter: physischer Widerstand-Bonus'), ('character.Charakter.physischer_widerstand_bonus_str', 'Charakter: physischer Widerstand-Bonus Text'), ('character.Charakter.astraler_widerstand_bonus', 'Charakter: astraler Widerstand-Bonus'), ('character.Charakter.astraler_widerstand_bonus_str', 'Charakter: astraler Widerstand-Bonus Text'), ('character.Charakter.manaoverflow_bonus', 'Charakter: Manaoverflow-Bonus'), ('character.Charakter.nat_regeneration_bonus', 'Charakter: nat. Regeneration-Bonus'), ('character.Charakter.immunsystem_bonus', 'Charakter: Immunsystem-Bonus')]),
        ),
        migrations.RunPython(delete_deprecated)
    ]
