# Generated by Django 5.2.9 on 2026-02-19 13:13

from django.db import migrations


def delete_deprecated(apps, schema_editor):
    Effect = apps.get_model('effect', 'Effect')
    RelEffect = apps.get_model('effect', 'RelEffect')

    Effect.objects.filter(target_fieldname='character.Charakter.astraler_widerstand_bonus').exclude(source_shopRüstung=None).delete()

    # trigger .deactivate() before deletion in signal
    for e in RelEffect.objects.filter(target_fieldname='character.Charakter.astraler_widerstand_bonus').exclude(source_shopRüstung=None):
        e.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0028_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_deprecated)
    ]
