# Generated by Django 5.2.9 on 2026-02-19 13:48

from django.db import migrations

from effect.signals import apply_effect_on_rel_relation


def create_releffects_for_rüstung_widerstand(apps, schema_editor):
    RelRüstung = apps.get_model('character', 'RelRüstung')
    RelEffect = apps.get_model('effect', 'RelEffect')

    # trigger every r.deactivate()
    for r in RelEffect.objects.exclude(source_shopRüstung=None): r.delete()

    # recreate RelEffects für all RelRüstung
    for rel_rüstung in RelRüstung.objects.all():
        apply_effect_on_rel_relation(RelRüstung, rel_rüstung, created=True)


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0029_auto_20260219_1413'),
    ]

    operations = [
        migrations.RunPython(create_releffects_for_rüstung_widerstand)
    ]
