# Generated by Django 5.2.9 on 2026-09-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0031_alter_effect_target_fieldname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releffect',
            old_name='source_shopEinbauten',
            new_name='source_shopEinbaute',
        ),
        migrations.RenameField(
            model_name='effect',
            old_name='source_shopEinbauten',
            new_name='source_shopEinbaute',
        ),
    ]
