# Generated by Django 5.2.9 on 2026-09-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0032_rename_source_shopeinbauten_releffect_source_shopeinbaute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='source_shopAusrüstungTechnik',
        ),
        migrations.RemoveField(
            model_name='releffect',
            name='source_shopAusrüstungTechnik',
        ),
    ]
