# Generated by Django 3.1.7 on 2021-04-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Nachricht', 'verbose_name_plural': 'Nachrichten'},
        ),
    ]
