# Generated by Django 2.0.5 on 2020-06-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200602_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttinker',
            options={'ordering': ['kategorie', 'name'], 'verbose_name': 'Für Selbstständige (stufenabh)', 'verbose_name_plural': 'Für Selbstständige (stufenabh)'},
        ),
    ]
