# Generated by Django 2.0.5 on 2020-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200607_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttinker',
            old_name='beschaffung',
            new_name='herstellung_via',
        ),
        migrations.RenameField(
            model_name='tinker',
            old_name='beschaffung',
            new_name='herstellung_via',
        ),
        migrations.AddField(
            model_name='sttinker',
            name='herstellungsdauer',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tinker',
            name='herstellungsdauer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
