# Generated by Django 2.0.4 on 2020-06-08 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200607_1526'),
    ]

    operations = []