# Generated by Django 2.0.5 on 2020-06-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200615_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alchemie',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Alchemie', 'verbose_name_plural': 'Alchemie'},
        ),
        migrations.AlterModelOptions(
            name='ausrüstung_technik',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Ausrüstung/Technik', 'verbose_name_plural': 'Ausrüstung & Technik'},
        ),
        migrations.AlterModelOptions(
            name='einbauten',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Einbauten', 'verbose_name_plural': 'Einbauten'},
        ),
        migrations.AlterModelOptions(
            name='fahrzeug',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Fahrzeug', 'verbose_name_plural': 'Fahrzeuge'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='magische_ausrüstung',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'magische Ausrüstung', 'verbose_name_plural': 'magische Ausrüstung'},
        ),
        migrations.AlterModelOptions(
            name='pfeil_bolzen',
            options={'ordering': ['name', 'bs', 'zs'], 'verbose_name': 'Pfeil/Bolzen', 'verbose_name_plural': 'Pfeile & Bolzen'},
        ),
        migrations.AlterModelOptions(
            name='rituale_runen',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Ritual/Rune', 'verbose_name_plural': 'Rituale & Runen'},
        ),
        migrations.AlterModelOptions(
            name='schusswaffen',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Schusswaffe', 'verbose_name_plural': 'Schusswaffen'},
        ),
        migrations.AlterModelOptions(
            name='stalchemie',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Alchemie (stufenabh)', 'verbose_name_plural': 'Alchemie (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stausrüstung_technik',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Ausrüstung/Technik (stufenabh)', 'verbose_name_plural': 'Ausrüstung & Technik (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='steinbauten',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Einbauten (stufenabh)', 'verbose_name_plural': 'Einbauten (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stfahrzeug',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Fahrzeug (stufenabh)', 'verbose_name_plural': 'Fahrzeuge (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stitem',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Item (stufenabh)', 'verbose_name_plural': 'Items (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stmagische_ausrüstung',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'magische Ausrüstung (stufenabh)', 'verbose_name_plural': 'magische Ausrüstung (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stpfeil_bolzen',
            options={'ordering': ['name', 'bs', 'zs'], 'verbose_name': 'Pfeil/Bolzen (stufenabh)', 'verbose_name_plural': 'Pfeile & Bolzen (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stschusswaffen',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Schusswaffe (stufenabh)', 'verbose_name_plural': 'Schusswaffen (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stwaffen_werkzeuge',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Waffe/Werkzeug (stufenabh)', 'verbose_name_plural': 'Waffen & Werkzeuge (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stzauber',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Zauber (stufenabh)', 'verbose_name_plural': 'Zauber (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='waffen_werkzeuge',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Waffe/Werkzeug', 'verbose_name_plural': 'Waffen & Werkzeuge'},
        ),
        migrations.AlterModelOptions(
            name='zauber',
            options={'ordering': ['name', 'kategorie'], 'verbose_name': 'Zauber', 'verbose_name_plural': 'Zauber'},
        ),
    ]
