# Generated by Django 2.2.13 on 2020-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200624_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalchemie',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stausrüstung_technik',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='steinbauten',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stfahrzeug',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stitem',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stmagazin',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stmagische_ausrüstung',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stpfeil_bolzen',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='strüstungen',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stschusswaffen',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stwaffen_werkzeuge',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stzauber',
            name='frei_editierbar',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
