# Generated by Django 2.2.13 on 2020-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200815_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemie',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ausrüstung_technik',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='einbauten',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazin',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magische_ausrüstung',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pfeil_bolzen',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rituale_runen',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rüstungen',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schusswaffen',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sttinker',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tinker',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waffen_werkzeuge',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zauber',
            name='stufenabhängig',
            field=models.BooleanField(default=False),
        ),
    ]
