# Generated by Django 2.2.13 on 2020-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0042_auto_20200815_1712'),
        ('create', '0017_auto_20200815_1712'),
        ('shop', '0021_auto_20200815_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmastfahrzeug',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastfahrzeug',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastitem',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastmagazin',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastmagazin',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastpfeil_bolzen',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastpfeil_bolzen',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastrüstungen',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastrüstungen',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastschusswaffen',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastschusswaffen',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmasttinker',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmasttinker',
            name='item',
        ),
        migrations.RemoveField(
            model_name='firmastzauber',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='firmastzauber',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stalchemie',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stfahrzeug',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stitem',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stmagazin',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stpfeil_bolzen',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='strüstungen',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stschusswaffen',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='stschusswaffen',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='stschusswaffen',
            name='pfeile_bolzen',
        ),
        migrations.RemoveField(
            model_name='stschusswaffen',
            name='st_magazine',
        ),
        migrations.RemoveField(
            model_name='stschusswaffen',
            name='st_pfeile_bolzen',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='benötigt',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='firmen',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='herstellung_via',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='nebenprodukte',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='probe_spezial',
        ),
        migrations.RemoveField(
            model_name='sttinker',
            name='probe_wissen',
        ),
        migrations.RemoveField(
            model_name='sttinkerneeds',
            name='part',
        ),
        migrations.RemoveField(
            model_name='sttinkerneeds',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sttinkerwaste',
            name='neben',
        ),
        migrations.RemoveField(
            model_name='sttinkerwaste',
            name='rezept',
        ),
        migrations.RemoveField(
            model_name='stzauber',
            name='firmen',
        ),
        migrations.AlterModelOptions(
            name='alchemie',
            options={'verbose_name': 'Alchemie', 'verbose_name_plural': 'Alchemie'},
        ),
        migrations.AlterModelOptions(
            name='ausrüstung_technik',
            options={'verbose_name': 'Ausrüstung/Technik', 'verbose_name_plural': 'Ausrüstung & Technik'},
        ),
        migrations.AlterModelOptions(
            name='einbauten',
            options={'verbose_name': 'Einbauten', 'verbose_name_plural': 'Einbauten'},
        ),
        migrations.AlterModelOptions(
            name='fahrzeug',
            options={'verbose_name': 'Fahrzeug', 'verbose_name_plural': 'Fahrzeuge'},
        ),
        migrations.AlterModelOptions(
            name='firmarituale_runen',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='firmastausrüstung_technik',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='firmasteinbauten',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='firmastmagische_ausrüstung',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='firmastwaffen_werkzeuge',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='magazin',
            options={'verbose_name': 'Magazin', 'verbose_name_plural': 'Magazine'},
        ),
        migrations.AlterModelOptions(
            name='magische_ausrüstung',
            options={'verbose_name': 'magische Ausrüstung', 'verbose_name_plural': 'magische Ausrüstung'},
        ),
        migrations.AlterModelOptions(
            name='pfeil_bolzen',
            options={'verbose_name': 'Pfeil/Bolzen', 'verbose_name_plural': 'Pfeile & Bolzen'},
        ),
        migrations.AlterModelOptions(
            name='rituale_runen',
            options={'verbose_name': 'Ritual/Rune', 'verbose_name_plural': 'Rituale & Runen'},
        ),
        migrations.AlterModelOptions(
            name='rüstungen',
            options={'verbose_name': 'Rüstung', 'verbose_name_plural': 'Rüstung'},
        ),
        migrations.AlterModelOptions(
            name='schusswaffen',
            options={'verbose_name': 'Schusswaffe', 'verbose_name_plural': 'Schusswaffen'},
        ),
        migrations.AlterModelOptions(
            name='stausrüstung_technik',
            options={'verbose_name': 'Ausrüstung/Technik (stufenabh)', 'verbose_name_plural': 'Ausrüstung & Technik (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='steinbauten',
            options={'verbose_name': 'Einbauten (stufenabh)', 'verbose_name_plural': 'Einbauten (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stmagische_ausrüstung',
            options={'verbose_name': 'magische Ausrüstung (stufenabh)', 'verbose_name_plural': 'magische Ausrüstung (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='stwaffen_werkzeuge',
            options={'verbose_name': 'Waffe/Werkzeug (stufenabh)', 'verbose_name_plural': 'Waffen & Werkzeuge (stufenabh)'},
        ),
        migrations.AlterModelOptions(
            name='tinker',
            options={'verbose_name': 'Für Selbstständige', 'verbose_name_plural': 'Für Selbstständige'},
        ),
        migrations.AlterModelOptions(
            name='waffen_werkzeuge',
            options={'verbose_name': 'Waffe/Werkzeug', 'verbose_name_plural': 'Waffen & Werkzeuge'},
        ),
        migrations.AlterModelOptions(
            name='zauber',
            options={'verbose_name': 'Zauber', 'verbose_name_plural': 'Zauber'},
        ),
        migrations.RemoveField(
            model_name='schusswaffen',
            name='st_magazine',
        ),
        migrations.RemoveField(
            model_name='schusswaffen',
            name='st_pfeile_bolzen',
        ),
        migrations.DeleteModel(
            name='FirmaStAlchemie',
        ),
        migrations.DeleteModel(
            name='FirmaStFahrzeug',
        ),
        migrations.DeleteModel(
            name='FirmaStItem',
        ),
        migrations.DeleteModel(
            name='FirmaStMagazin',
        ),
        migrations.DeleteModel(
            name='FirmaStPfeil_Bolzen',
        ),
        migrations.DeleteModel(
            name='FirmaStRüstungen',
        ),
        migrations.DeleteModel(
            name='FirmaStSchusswaffen',
        ),
        migrations.DeleteModel(
            name='FirmaStTinker',
        ),
        migrations.DeleteModel(
            name='FirmaStZauber',
        ),
        migrations.DeleteModel(
            name='StAlchemie',
        ),
        migrations.DeleteModel(
            name='StFahrzeug',
        ),
        migrations.DeleteModel(
            name='StItem',
        ),
        migrations.DeleteModel(
            name='StMagazin',
        ),
        migrations.DeleteModel(
            name='StPfeil_Bolzen',
        ),
        migrations.DeleteModel(
            name='StRüstungen',
        ),
        migrations.DeleteModel(
            name='StSchusswaffen',
        ),
        migrations.DeleteModel(
            name='StTinker',
        ),
        migrations.DeleteModel(
            name='StTinkerNeeds',
        ),
        migrations.DeleteModel(
            name='StTinkerWaste',
        ),
        migrations.DeleteModel(
            name='StZauber',
        ),
    ]
