# Generated by Django 2.2.13 on 2020-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200815_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmaalchemie',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmaausrüstung_technik',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmaeinbauten',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmafahrzeug',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmaitem',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmamagazin',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmamagische_ausrüstung',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmapfeil_bolzen',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmarüstungen',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmaschusswaffen',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmatinker',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmawaffen_werkzeuge',
            name='verfügbarkeit_int',
        ),
        migrations.RemoveField(
            model_name='firmazauber',
            name='verfügbarkeit_int',
        ),
        migrations.AddField(
            model_name='firmarituale_runen',
            name='stufe_1_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmarituale_runen',
            name='stufe_2_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmarituale_runen',
            name='stufe_3_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmarituale_runen',
            name='stufe_4_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='firmarituale_runen',
            name='stufe_5_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmaalchemie',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmaausrüstung_technik',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmaeinbauten',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmafahrzeug',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmaitem',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmamagazin',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmamagische_ausrüstung',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmapfeil_bolzen',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmarituale_runen',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmarüstungen',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmaschusswaffen',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmatinker',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmawaffen_werkzeuge',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firmazauber',
            name='verfügbarkeit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
