# Generated by Django 2.2.13 on 2020-08-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200815_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmarituale_runen',
            name='stufe_1',
        ),
        migrations.RemoveField(
            model_name='firmarituale_runen',
            name='stufe_2',
        ),
        migrations.RemoveField(
            model_name='firmarituale_runen',
            name='stufe_3',
        ),
        migrations.RemoveField(
            model_name='firmarituale_runen',
            name='stufe_4',
        ),
        migrations.RemoveField(
            model_name='firmarituale_runen',
            name='stufe_5',
        ),
    ]
