# Generated by Django 2.2.13 on 2020-08-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200815_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmarituale_runen',
            old_name='stufe_1_int',
            new_name='stufe_1',
        ),
        migrations.RenameField(
            model_name='firmarituale_runen',
            old_name='stufe_2_int',
            new_name='stufe_2',
        ),
        migrations.RenameField(
            model_name='firmarituale_runen',
            old_name='stufe_3_int',
            new_name='stufe_3',
        ),
        migrations.RenameField(
            model_name='firmarituale_runen',
            old_name='stufe_4_int',
            new_name='stufe_4',
        ),
        migrations.RenameField(
            model_name='firmarituale_runen',
            old_name='stufe_5_int',
            new_name='stufe_5',
        ),
    ]
