# Generated by Django 2.2.13 on 2020-10-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20201012_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('tinker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Tinker')),
            ],
            options={
                'verbose_name': 'Elektrischer Strom',
                'verbose_name_plural': 'Elektrischer Strom',
            },
            bases=('shop.tinker',),
        ),
        migrations.CreateModel(
            name='Thermal',
            fields=[
                ('tinker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Tinker')),
            ],
            options={
                'verbose_name': 'Thermische Energie',
                'verbose_name_plural': 'Thermische Energie',
            },
            bases=('shop.tinker',),
        ),
        migrations.AddField(
            model_name='tinker',
            name='needs_electricity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tinker',
            name='needs_thermic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tinker',
            name='kategorie',
            field=models.CharField(choices=[('m', 'Maschinen/Technik'), ('ru', 'Rüstungen/Schilde'), ('c', 'Cyberware'), ('n', 'N.-Waffen'), ('f', 'F.-Waffen'), ('b', 'Bioware'), ('a', 'andere Waffen'), ('w', 'Werkzeuge'), ('ro', 'Rohstoffe/Werkstoffe'), ('z', 'Zauber/Upgrades/Verbesserungen'), ('p', 'Produktionsstätten'), ('u', 'Müll'), ('e', 'Energie')], default='m', max_length=2),
        ),
    ]
