# Generated by Django 2.2.13 on 2020-10-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0052_auto_20200923_1257'),
        ('crafting', '0011_auto_20201022_1407'),
        ('shop', '0038_auto_20201019_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinker',
            name='needs_electricity',
        ),
        migrations.RemoveField(
            model_name='tinker',
            name='needs_thermic',
        ),
        migrations.DeleteModel(
            name='Electricity',
        ),
        migrations.DeleteModel(
            name='Thermal',
        ),
    ]
