# Generated by Django 3.1.7 on 2022-05-14 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20220503_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaVergessenerZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.IntegerField(default=0, null=True)),
                ('verfügbarkeit', models.PositiveIntegerField(default=0)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.firma')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VergessenerZauber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1500)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('ab_stufe', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('illegal', models.BooleanField(default=False)),
                ('lizenz_benötigt', models.BooleanField(default=False)),
                ('frei_editierbar', models.BooleanField(default=True)),
                ('stufenabhängig', models.BooleanField(default=False)),
                ('schaden', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('astralschaden', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('manaverbrauch', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('flächenzauber', models.BooleanField(default=False)),
                ('firmen', models.ManyToManyField(blank=True, through='shop.FirmaVergessenerZauber', to='shop.Firma')),
            ],
            options={
                'verbose_name': 'Vergessener Zauber',
                'verbose_name_plural': 'Vergessene Zauber',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='firmavergessenerzauber',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vergessenerzauber'),
        ),
    ]
