# Generated by Django 3.1.7 on 2022-08-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20220829_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rüstungen',
            options={'ordering': ['name'], 'verbose_name': 'Rüstung', 'verbose_name_plural': 'Rüstungen'},
        ),
        migrations.AlterModelOptions(
            name='tinker',
            options={'ordering': ['name'], 'verbose_name': 'für Selbstständige', 'verbose_name_plural': 'für Selbstständige'},
        ),
        migrations.AlterModelOptions(
            name='vergessenerzauber',
            options={'ordering': ['name'], 'verbose_name': 'vergessener Zauber', 'verbose_name_plural': 'vergessene Zauber'},
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='kategorie',
            field=models.CharField(choices=[('i', 'Items'), ('w', 'Waffen & Werkzeuge'), ('m', 'Magazine'), ('p', 'Pfeile & Bolzen'), ('s', 'Schusswaffen'), ('a', 'magische Ausrüstung'), ('r', 'Rituale & Runen'), ('u', 'Rüstungen'), ('n', 'Ausrüstung & Technik'), ('f', 'Fahrzeuge'), ('e', 'Einbauten'), ('z', 'Zauber'), ('v', 'vergessene Zauber'), ('l', 'Alchemie'), ('b', 'Begleiter'), ('t', 'für Selbstständige')], default='i', max_length=1, unique=True),
        ),
    ]
