# Generated by Django 4.1.7 on 2023-04-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_alchemie_icon_alter_ausrüstung_technik_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vergessenerzauber',
            name='flächenzauber',
        ),
        migrations.RemoveField(
            model_name='zauber',
            name='flächenzauber',
        ),
    ]
