# Generated by Django 4.1.7 on 2023-05-06 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_remove_vergessenerzauber_flächenzauber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engelsroboter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('beschreibung', models.TextField(blank=True, default='', max_length=1500)),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to='')),
                ('ab_stufe', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('illegal', models.BooleanField(default=False)),
                ('lizenz_benötigt', models.BooleanField(default=False)),
                ('frei_editierbar', models.BooleanField(default=True)),
                ('stufenabhängig', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Engelsroboter',
                'verbose_name_plural': 'Engelsroboter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirmaEngelsroboter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.IntegerField(default=0, null=True)),
                ('verfügbarkeit', models.PositiveIntegerField(default=0)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.firma')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.engelsroboter')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'ordering': ['item', 'firma'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='engelsroboter',
            name='firmen',
            field=models.ManyToManyField(blank=True, through='shop.FirmaEngelsroboter', to='shop.firma'),
        ),
    ]
