# Generated by Django 4.1.7 on 2023-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_engelsroboter_in_engelsroboter_ma_engelsroboter_st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zauber',
            name='will_create',
            field=models.BooleanField(default=False),
        ),
    ]
