# Generated by Django 4.1.7 on 2023-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_zauber_will_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='zauber',
            name='verteidigung',
            field=models.CharField(choices=[('a', 'Astralwiderstand'), ('r', 'Reaktion')], default='a', max_length=1),
        ),
    ]
