# Generated by Django 4.1.7 on 2023-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_zauber_verteidigung'),
    ]

    operations = [
        migrations.AddField(
            model_name='zauber',
            name='astralsch_is_direct',
            field=models.BooleanField(default=False, verbose_name='verursacht direkten Astralschaden'),
        ),
        migrations.AlterField(
            model_name='zauber',
            name='verteidigung',
            field=models.CharField(choices=[('n', 'kein Ziel gewählt'), ('a', 'Astralwiderstand'), ('r', 'Reaktion')], default='n', max_length=1),
        ),
    ]
