# Generated by Django 4.2.8 on 2024-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alchemie_has_implementation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfeil_bolzen',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('k', 'körperlich'), ('e', 'elementar'), ('f', 'Feuer'), ('n', 'energetisch'), ('l', 'Laser/Licht'), ('h', 'elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'korrosion (Säuren, Laugen, ...)'), ('i', 'Eis'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'radioaktiv'), ('s', 'stich'), ('w', 'wucht (mit phys. Objekt)'), ('c', 'Schall (mit Schallwellen)'), ('d', 'Druck (mit einer Welle)'), ('t', 'geistig'), ('a', 'astral')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='schusswaffen',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('k', 'körperlich'), ('e', 'elementar'), ('f', 'Feuer'), ('n', 'energetisch'), ('l', 'Laser/Licht'), ('h', 'elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'korrosion (Säuren, Laugen, ...)'), ('i', 'Eis'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'radioaktiv'), ('s', 'stich'), ('w', 'wucht (mit phys. Objekt)'), ('c', 'Schall (mit Schallwellen)'), ('d', 'Druck (mit einer Welle)'), ('t', 'geistig'), ('a', 'astral')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='waffen_werkzeuge',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('k', 'körperlich'), ('e', 'elementar'), ('f', 'Feuer'), ('n', 'energetisch'), ('l', 'Laser/Licht'), ('h', 'elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'korrosion (Säuren, Laugen, ...)'), ('i', 'Eis'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'radioaktiv'), ('s', 'stich'), ('w', 'wucht (mit phys. Objekt)'), ('c', 'Schall (mit Schallwellen)'), ('d', 'Druck (mit einer Welle)'), ('t', 'geistig'), ('a', 'astral')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='zauber',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('k', 'körperlich'), ('e', 'elementar'), ('f', 'Feuer'), ('n', 'energetisch'), ('l', 'Laser/Licht'), ('h', 'elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'korrosion (Säuren, Laugen, ...)'), ('i', 'Eis'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'radioaktiv'), ('s', 'stich'), ('w', 'wucht (mit phys. Objekt)'), ('c', 'Schall (mit Schallwellen)'), ('d', 'Druck (mit einer Welle)'), ('t', 'geistig'), ('a', 'astral')], max_length=1, null=True),
        ),
    ]
