# Generated by Django 4.2.8 on 2024-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_pfeil_bolzen_schadensart_schusswaffen_schadensart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfeil_bolzen',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='schusswaffen',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='waffen_werkzeuge',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='zauber',
            name='schadensart',
            field=models.CharField(blank=True, choices=[('_', 'Artlos'), ('k', 'Körperlich'), ('e', 'Elementar'), ('f', 'Feuer'), ('n', 'Energetisch'), ('l', 'Laser/Licht'), ('h', 'Elektrisch'), ('m', 'Mana'), ('g', 'Gift'), ('o', 'Korrosion'), ('i', 'Eis'), ('j', 'Wasser'), ('b', 'Boden/Gestein'), ('p', 'Pflanzen'), ('r', 'Radioaktiv'), ('s', 'Stich'), ('q', 'Hieb'), ('w', 'Wucht'), ('c', 'Schall'), ('d', 'Druck'), ('t', 'Geistig'), ('a', 'Astral')], max_length=1, null=True),
        ),
    ]
