# Generated by Django 4.2.8 on 2024-12-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_pfeil_bolzen_schadensart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zauber',
            name='astralsch_is_direct',
        ),
        migrations.RemoveField(
            model_name='zauber',
            name='schaden',
        ),
    ]
