# Generated by Django 4.2.8 on 2025-07-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_tinker_wooble_buy_price_tinker_wooble_sell_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rüstungen',
            old_name='stärke',
            new_name='härte',
        ),
    ]
