# Generated by Django 4.0 on 2021-12-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('pfad', models.CharField(default='/', max_length=500)),
                ('antwort', models.PositiveSmallIntegerField(default=200)),
                ('methode', models.CharField(default='GET', max_length=8)),
                ('user', models.CharField(default='', max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'ordering': ['-zeit'],
            },
        ),
    ]
