# Generated by Django 3.1.5 on 2022-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_agent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
