# Generated by Django 2.0.5 on 2019-03-11 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_auto_20181210_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='HPplus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='HPplus_fix',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='teil_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newcharakterattribut',
            name='aktuellerWert_fix',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='newcharakterattribut',
            name='maxWert_fix',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
