# Generated by Django 2.2.13 on 2020-08-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_auto_20200802_1648'),
        ('create', '0006_remove_newcharakter_magie_moeglich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcharakter',
            name='spezies',
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='gfs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Gfs'),
        ),
    ]
