# Generated by Django 2.2.13 on 2020-08-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_auto_20200805_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcharakter',
            name='magie',
        ),
        migrations.DeleteModel(
            name='NewCharakterSpezies',
        ),
    ]
