# Generated by Django 2.2.13 on 2020-08-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_auto_20200806_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcharakter',
            name='manifest',
        ),
        migrations.RemoveField(
            model_name='newcharakter',
            name='teil_error',
        ),
        migrations.RemoveField(
            model_name='newcharakter',
            name='wesenschaden_andere_gestalt',
        ),
        migrations.RemoveField(
            model_name='newcharakter',
            name='wesenschaden_waff_kampf',
        ),
        migrations.RemoveField(
            model_name='newcharakterattribut',
            name='aktuellerWert_cp',
        ),
        migrations.RemoveField(
            model_name='newcharakterattribut',
            name='fg_cp',
        ),
        migrations.RemoveField(
            model_name='newcharakterattribut',
            name='maxWert_cp',
        ),
        migrations.RemoveField(
            model_name='newcharakterfertigkeit',
            name='cp',
        ),
        migrations.AddField(
            model_name='newcharakterfertigkeit',
            name='fp_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newcharakterfertigkeit',
            name='fp',
            field=models.SmallIntegerField(default=0),
        ),
    ]
