# Generated by Django 2.2.13 on 2020-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20200806_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcharakterfertigkeit',
            options={'ordering': ['char', 'fertigkeit'], 'verbose_name': 'Startfertigkeit', 'verbose_name_plural': 'Startfertigkeiten'},
        ),
        migrations.RemoveField(
            model_name='newcharakterattribut',
            name='aktuellerWert_fix',
        ),
        migrations.RemoveField(
            model_name='newcharakterattribut',
            name='maxWert_fix',
        ),
        migrations.RemoveField(
            model_name='newcharakternachteil',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='newcharaktervorteil',
            name='extra',
        ),
        migrations.AddField(
            model_name='newcharakternachteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newcharaktervorteil',
            name='anzahl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
