# Generated by Django 2.2.14 on 2020-08-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0011_remove_newcharakter_spezial'),
        ('create', '0010_auto_20200808_0830'),
    ]

    operations = [
    ]
