# Generated by Django 2.2.13 on 2020-08-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0037_remove_professionfertigkeit_pool'),
        ('create', '0012_merge_20200810_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Profession'),
        ),
        migrations.AlterField(
            model_name='newcharakter',
            name='gfs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Gfs'),
        ),
    ]
