# Generated by Django 2.2.13 on 2020-08-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0039_auto_20200812_2336'),
        ('create', '0014_auto_20200812_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcharakterattribut',
            options={'ordering': ['char', 'attribut'], 'verbose_name': 'Startattribut', 'verbose_name_plural': 'Startattribute'},
        ),
        migrations.AlterModelOptions(
            name='newcharakterspezialfertigkeit',
            options={'ordering': ['char', 'spezialfertigkeit'], 'verbose_name': 'Spezialfertigkeit', 'verbose_name_plural': 'Spezialfertigkeiten'},
        ),
        migrations.RenameField(
            model_name='newcharakter',
            old_name='spezialfertigkeiten',
            new_name='spezial',
        ),
        migrations.CreateModel(
            name='NewCharakterWissensfertigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveIntegerField(blank=True, default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.NewCharakter')),
                ('wissensfertigkeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Wissensfertigkeit')),
            ],
            options={
                'ordering': ['char', 'wissensfertigkeit'],
                'verbose_name': 'Wissensfertigkeit',
                'unique_together': {('wissensfertigkeit', 'char')},
                'verbose_name_plural': 'Wissensfertigkeiten',
            },
        ),
        migrations.AddField(
            model_name='newcharakter',
            name='wissen',
            field=models.ManyToManyField(through='create.NewCharakterWissensfertigkeit', to='character.Wissensfertigkeit'),
        ),
    ]
