# Generated by Django 3.1.5 on 2021-06-01 14:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('create', '0018_newcharakter_larp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priotable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[('A', 0), ('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5)], unique=True)),
                ('ip', models.PositiveSmallIntegerField(default=0)),
                ('ap', models.PositiveSmallIntegerField(default=0)),
                ('sp', models.PositiveSmallIntegerField(default=0)),
                ('fp', models.PositiveSmallIntegerField(default=0)),
                ('fg', models.PositiveSmallIntegerField(default=0)),
                ('zauber', models.PositiveSmallIntegerField(default=0)),
                ('drachmen', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Priotable Zeile',
                'verbose_name_plural': 'Priotable Zeilen',
                'ordering': ['priority'],
            },
        ),
    ]
