# Generated by Django 3.1.5 on 2021-06-01 14:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('create', '0019_priotable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priotable',
            name='priority',
            field=models.CharField(choices=[('A', 0), ('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5)], max_length=1, unique=True),
        )
    ]
