# Generated by Django 3.1.5 on 2021-06-01 14:34

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('create', '0020_auto_20210601_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priotable',
            name='priority',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, unique=True),
        )
    ]
