# Generated by Django 3.1.5 on 2021-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0023_gfscharacterization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gfscharacterization',
            old_name='flying',
            new_name='can_fly',
        ),
        migrations.RenameField(
            model_name='gfscharacterization',
            old_name='has_pricy_skills',
            new_name='gets_pricy_skills',
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='state',
            field=models.CharField(choices=[('l', 'lebend'), ('t', 'tot oder untot')], help_text='.. lebend oder (un)tot sein?', max_length=1, null=True, unique=True),
        ),
    ]
