# Generated by Django 3.1.5 on 2021-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0024_auto_20210601_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gfscharacterization',
            options={'ordering': ['gfs'], 'verbose_name': 'Gfs Charakterisierung', 'verbose_name_plural': 'Gfs Charakterisierungen'},
        ),
    ]
