# Generated by Django 3.1.5 on 2021-06-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0054_auto_20201223_1709'),
        ('create', '0025_auto_20210601_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfscharacterization',
            name='gfs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.gfs', unique=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='state',
            field=models.CharField(choices=[('l', 'lebend'), ('t', 'tot oder untot')], help_text='.. lebend oder (un)tot sein?', max_length=1, null=True),
        ),
    ]
