# Generated by Django 3.1.7 on 2022-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0027_auto_20210601_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfscharacterization',
            name='attitude',
            field=models.CharField(blank=True, choices=[('g', 'gut'), ('n', 'neutral'), ('e', 'böse')], help_text='.. gut/neutral/böse gesinnt sein?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_fly',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. fliegen können?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_punch',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. Nahkampf haben?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='can_shoot',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. Fernkampf haben?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='gets_pricy_skills',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. krasse (dafür teure) Fähigkeiten bekommen?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='magical',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. magisch sein?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='social',
            field=models.CharField(blank=True, choices=[('y', 'gut'), ('m', 'durchschnittlich'), ('n', 'schlecht')], help_text='.. sozial/umgänglich sein?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gfscharacterization',
            name='state',
            field=models.CharField(blank=True, choices=[('l', 'lebend'), ('t', 'tot oder untot')], help_text='.. lebend oder (un)tot sein?', max_length=1, null=True),
        ),
    ]
