# Generated by Django 3.1.7 on 2022-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0028_auto_20220503_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='priotable',
            name='konzentration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
