# Generated by Django 3.1.7 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0029_priotable_konzentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='konzentration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
