# Generated by Django 3.1.7 on 2022-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0031_auto_20220527_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='spF_wF',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
