# Generated by Django 4.1.7 on 2023-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0034_alter_gfscharacterization_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcharakter',
            name='wp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
