# Generated by Django 4.2.8 on 2024-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0036_alter_newcharakterattribut_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priotable',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
