# pull official base image
FROM python:3.14-alpine AS backup

# create the appropriate directories
WORKDIR /var/www

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# deps with pip
RUN apk update && apk add postgresql-client
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy project to work on
COPY backend ./

# run db backup
ENTRYPOINT ["python", "manage.py"]
CMD ["dbbackup"]
