# Generated by Django 4.2.8 on 2025-07-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0181_alter_wesen_beschreibung'),
        ('crafting', '0036_alter_region_options'),
        ('combat', '0002_playerstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('char', 'profil')},
        ),
    ]
