# Generated by Django 2.0.5 on 2020-06-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200603_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Umfrage',
        ),
    ]
