# Generated by Django 3.2.16 on 2022-11-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20221119_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='appointmentnegotiation',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentnegotiation',
            name='players',
        ),
        migrations.DeleteModel(
            name='BlockedTime',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='appointment_negotiation',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='player',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentNegotiation',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
