# Generated by Django 3.2.16 on 2022-11-20 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0011_auto_20221120_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, unique=True)),
                ('open_for_participation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terminabsprache',
                'verbose_name_plural': 'Terminabsprachen',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('start', models.TimeField(default=planner.models.default_time)),
                ('note', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.day')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminvorschlag',
                'verbose_name_plural': 'Terminvorschläge',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='users',
            field=models.ManyToManyField(through='planner.Proposal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.TimeField(default=planner.models.min_time)),
                ('end', models.TimeField(default=planner.models.max_time)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.day')),
            ],
            options={
                'verbose_name': 'Blockierter Zeitraum',
                'verbose_name_plural': 'Blockierte Zeiträume',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.TimeField(default=planner.models.default_time, unique=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.day')),
                ('tags', models.ManyToManyField(to='planner.Tag')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['day'],
            },
        ),
    ]
