#! /bin/bash

BASEPATH_CONTAINER="/home/ppServer/web"
BASEPATH_HOST="/home/debian/pnpWebsite"

DATE="$(date +%y-%m-%d)"


# prepare dump disk locations
docker exec pnp-web mkdir -p ./backups/

mkdir -p $BASEPATH_HOST/backups/$DATE/media
chown -R debian:debian $BASEPATH_HOST/backups

# move to base path on actual machine (in docker container already set by default, because of the last WORKDIR in corresponding Dockerfile)
cd $BASEPATH_HOST

# stop routing to ensure consistent backup data
docker container stop pnp-webserver

# backup db
docker exec pnp-web python3 manage.py dbbackup
docker cp pnp-web:$BASEPATH_CONTAINER/backups/. ./backups/$DATE/

# backup media
docker cp pnp-web:$BASEPATH_CONTAINER/media/.  ./backups/$DATE/media

# re-enable routing, rest can be done in parallel
docker container start pnp-webserver

# compress backup
cd ./backups
tar -czf $DATE.tar.gz $DATE/

# remove original backups inside docker-container
docker exec pnp-web rm -rf ./backups

# remove all files (type f) modified longer than 30 days ago under ./backups
rm -rf ./$DATE
find . -type f -mtime +30 -delete

# copy backup over to google  cloud storage bucket
gcloud storage cp $BASEPATH_HOST/backups/$DATE.tar.gz gs://backup-goren-pnp.appspot.com/backups