# Generated by Django 4.2.8 on 2024-05-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0145_spieler_language_daemonisch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wertaenderung', models.IntegerField()),
                ('target_fieldname', models.CharField(choices=[('character.RelAttribut.aktuellerWert', 'Attribut: Wert'), ('character.RelAttribut.aktuellerWert_fix', 'Attribut: Wert fix'), ('character.RelAttribut.aktuellerWert_bonus', 'Attribut: Bonus'), ('character.RelAttribut.maxWert', 'Attribut: Maximum'), ('character.RelAttribut.maxWert_fix', 'Attribut: Maximum fix'), ('character.RelFertigkeit.fp', 'Fertigkeit: FP'), ('character.RelFertigkeit.fp_bonus', 'Fertigkeit: Bonus'), ('character.Charakter.ap', 'Charakter: AP'), ('character.Charakter.ip', 'Charakter: IP'), ('character.Charakter.fp', 'Charakter: FP'), ('character.Charakter.fg', 'Charakter: FG'), ('character.Charakter.tp', 'Charakter: TP'), ('character.Charakter.sp', 'Charakter: SP'), ('character.Charakter.geld', 'Charakter: Geld'), ('character.Charakter.prestige', 'Charakter: Prestige'), ('character.Charakter.verzehr', 'Charakter: Verzehr'), ('character.Charakter.sanität', 'Charakter: Sanität'), ('character.Charakter.glück', 'Charakter: Glück'), ('character.Charakter.sonstiger_manifestverlust', 'Charakter: Manifest'), ('character.Charakter.HPplus', 'Charakter: kHP plus'), ('character.Charakter.HPplus_fix', 'Charakter: kHP plus fix'), ('character.Charakter.HPplus_geistig', 'Charakter: gHP plus'), ('character.Charakter.rang', 'Charakter: Rang'), ('character.Charakter.crit_attack', 'Charakter: Crit-Angriff'), ('character.Charakter.crit_defense', 'Charakter: Crit-Verteidigung'), ('character.Charakter.initiative_bonus', 'Charakter: Initiative-Bonus'), ('character.Charakter.reaktion_bonus', 'Charakter: Reaktinsbonus'), ('character.Charakter.natürlicher_schadenswiderstand_bonus', 'Charakter: nat. SchaWi-Bonus'), ('character.Charakter.astralwiderstand_bonus', 'Charakter: AsWi-Bonus'), ('character.Charakter.manaoverflow_bonus', 'Charakter: Manaoverflow-Bonus')])),
                ('target_attribut', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='character.attribut')),
                ('target_fertigkeit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='character.fertigkeit')),
            ],
            options={
                'verbose_name': 'Effekt',
                'verbose_name_plural': 'Effekte',
                'ordering': ['target_fieldname'],
            },
        ),
    ]
