# Generated by Django 4.2.8 on 2024-05-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0145_spieler_language_daemonisch'),
        ('effect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='target_attribut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='character.attribut'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='target_fertigkeit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='character.fertigkeit'),
        ),
    ]
