# Generated by Django 4.2.8 on 2024-10-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0156_klasse_alter_gfs_options_relklasse'),
        ('effect', '0015_alter_effect_wertaenderung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='source_klasse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.klasse'),
        ),
        migrations.AddField(
            model_name='releffect',
            name='source_klasse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.relklasse'),
        ),
    ]
