# Generated by Django 4.2.8 on 2024-10-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0157_klasseability_relklasseability_klassestufenplan'),
        ('effect', '0016_effect_source_klasse_releffect_source_klasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='source_klasseAbility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.klasseability'),
        ),
        migrations.AddField(
            model_name='releffect',
            name='source_klasseAbility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.relklasseability'),
        ),
    ]
