# Generated by Django 4.2.8 on 2025-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0017_effect_source_klasseability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='wertaenderung',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Wertänderung'),
        ),
        migrations.AlterField(
            model_name='releffect',
            name='wertaenderung',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Wertänderung'),
        ),
    ]
