# Generated by Django 2.2.13 on 2020-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190329_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='art',
            field=models.CharField(choices=[('s', 'Shop'), ('v', 'Magie verloren'), ('d', 'Quiz-Punkte für SP')], max_length=1),
        ),
    ]
