# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0072_remove_profession_talente_and_more'),
        ('log', '0006_auto_20201212_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterField(
            model_name='log',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charakter', verbose_name='Charakter'),
        ),
    ]
