# Generated by Django 4.1.7 on 2023-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
