# Generated by Django 4.2.8 on 2024-02-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPush', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsettings',
            options={'ordering': ['user'], 'verbose_name': 'PushSettings', 'verbose_name_plural': 'PushSettings'},
        ),
        migrations.AlterField(
            model_name='pushsettings',
            name='changelog',
            field=models.BooleanField(default=True, verbose_name='Updates der Website'),
        ),
        migrations.AlterField(
            model_name='pushsettings',
            name='chat',
            field=models.BooleanField(default=True, verbose_name='neue Chat-Nachrichten'),
        ),
        migrations.AlterField(
            model_name='pushsettings',
            name='news',
            field=models.BooleanField(default=True, verbose_name='neue Goren-Newsartikel'),
        ),
        migrations.AlterField(
            model_name='pushsettings',
            name='polls',
            field=models.BooleanField(default=True, verbose_name='neue Umfragen'),
        ),
        migrations.AlterField(
            model_name='pushsettings',
            name='quiz',
            field=models.BooleanField(default=True, verbose_name='Änderungen im Quiz'),
        ),
    ]
