# Generated by Django 4.2.8 on 2024-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPush', '0002_alter_pushsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsettings',
            name='politics',
            field=models.BooleanField(default=True, verbose_name='politische Entscheidungen'),
        ),
    ]
