# Generated by Django 3.2.16 on 2022-11-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0064_gfsstufenplanbase_tp'),
        ('planner', '0002_auto_20221116_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(unique=True)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('max_waitinglist', models.PositiveSmallIntegerField(default=4)),
                ('state', models.CharField(choices=[('p', 'proposal'), ('o', 'open for participation'), ('c', 'closed')], max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='character.spieler')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('note', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.appointment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Teilnahme',
                'verbose_name_plural': 'Teilnahmen',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='players',
            field=models.ManyToManyField(through='planner.Participation', to='character.Spieler'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tags',
            field=models.ManyToManyField(to='planner.Tag'),
        ),
    ]
