# Generated by Django 3.2.16 on 2022-11-16 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20221116_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repetitions',
            new_name='Repetition',
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='repetitions',
            field=models.ManyToManyField(to='planner.Repetition'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
