# Generated by Django 3.2.16 on 2022-11-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20221116_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetition',
            name='interval',
        ),
        migrations.DeleteModel(
            name='BlockedTime',
        ),
        migrations.DeleteModel(
            name='Repetition',
        ),
    ]
