# Generated by Django 3.2.16 on 2022-11-19 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0064_gfsstufenplanbase_tp'),
        ('planner', '0006_blockedtime_repetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, unique=True)),
                ('open_for_participation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terminabsprache',
                'verbose_name_plural': 'Terminabsprachen',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('start', models.TimeField(default=planner.models.default_time)),
                ('note', models.TextField(blank=True, null=True)),
                ('appointment_negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.appointmentnegotiation')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Terminvorschlag',
                'verbose_name_plural': 'Terminvorschläge',
            },
        ),
        migrations.RemoveField(
            model_name='repetition',
            name='blocked_time',
        ),
        migrations.RemoveField(
            model_name='repetition',
            name='interval',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='blockedtime',
            options={'ordering': ['date'], 'verbose_name': 'Blockierter Zeitraum', 'verbose_name_plural': 'Blockierte Zeiträume'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='max_waitinglist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='players',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='state',
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='date',
            field=models.DateField(default=datetime.datetime.today, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.TimeField(default=datetime.datetime.now, unique=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='end',
            field=models.TimeField(default=planner.models.max_time),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start',
            field=models.TimeField(default=planner.models.min_time),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Repetition',
        ),
        migrations.AddField(
            model_name='appointmentnegotiation',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentnegotiation',
            name='players',
            field=models.ManyToManyField(through='planner.Proposal', to='character.Spieler'),
        ),
    ]
