# Generated by Django 3.2.16 on 2022-11-19 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentnegotiation',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_negotiation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.appointmentnegotiation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.TimeField(default=planner.models.default_time, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmentnegotiation',
            name='players',
            field=models.ManyToManyField(through='planner.Proposal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
