# Generated by Django 3.2.16 on 2022-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='users',
            new_name='proposals',
        ),
    ]
