# Generated by Django 4.2.8 on 2024-01-26 15:02

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import lerneinheiten.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Einheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=lerneinheiten.models.next_einheit_number, unique=True)),
                ('titel', models.CharField(max_length=256, unique=True)),
                ('klasse', models.PositiveSmallIntegerField(default=4)),
                ('fach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lerneinheiten.fach')),
            ],
            options={
                'verbose_name': 'Lerneinheit',
                'verbose_name_plural': 'Lerneinheiten',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('titel', models.CharField(max_length=256, unique=True)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('type', models.CharField(choices=[('i', 'Lerninhalt'), ('lf', 'Lückentext mit Freitext'), ('ls', 'Lückentext mit Auswahl'), ('ld', 'Lückentext mit Vorgabe'), ('do', 'Sortieren'), ('dt', 'Themen zuordnen'), ('dv', 'Verbinden'), ('cs', 'Single Choice'), ('cm', 'Multiple Choice'), ('ft', 'Freitext'), ('uc', 'Zeichnen')], max_length=2)),
                ('content', models.JSONField(default=dict)),
                ('solution', models.JSONField(default=dict)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerneinheiten.einheit')),
            ],
            options={
                'verbose_name': 'Seite',
                'verbose_name_plural': 'Seiten',
                'ordering': ['einheit__number', 'number'],
                'unique_together': {('number', 'einheit')},
            },
        ),
    ]
