# Generated by Django 4.2.8 on 2024-03-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0144_remove_charakter_sonstiges_alchemie_and_more'),
        ('lerneinheiten', '0006_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='question',
            field=models.TextField(blank=True, verbose_name='Feedback, Nachfrage oder allgemeine Verwirrtheit'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Spielleiter-Antwort'),
        ),
        migrations.CreateModel(
            name='SpielerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerneinheiten.page')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spieler')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
                'ordering': ['spieler', 'page'],
                'unique_together': {('spieler', 'page')},
            },
        ),
    ]
