# Generated by Django 4.2.8 on 2024-04-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0144_remove_charakter_sonstiges_alchemie_and_more'),
        ('lerneinheiten', '0009_spielereinheit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spielereinheit',
            unique_together={('spieler', 'einheit')},
        ),
    ]
