# Generated by Django 4.2.8 on 2025-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerneinheiten', '0010_alter_spielereinheit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Spielleitung-Antwort'),
        ),
    ]
