# Generated by Django 2.0.5 on 2018-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['file'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.CharField(blank=True, max_length=1000)),
                ('files', models.ManyToManyField(to='fileserver.File')),
                ('sichtbar_für', models.ManyToManyField(blank=True, to='character.Spieler')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
                ('beschreibung', models.CharField(blank=True, max_length=1000)),
                ('files', models.ManyToManyField(to='fileserver.File')),
                ('sichtbar_für', models.ManyToManyField(blank=True, to='character.Spieler')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Storys',
                'ordering': ['titel'],
            },
        ),
    ]
