# Generated by Django 4.1.7 on 2023-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_topic_remove_story_files_remove_story_sichtbar_für_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['titel'], 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AddField(
            model_name='topic',
            name='sichtbarkeit_eingeschränkt',
            field=models.BooleanField(default=False),
        ),
    ]
