# Generated by Django 4.1.4 on 2023-02-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_card_id_alter_card_money_alter_card_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelCard',
        ),
    ]
