# Generated by Django 4.2.8 on 2025-11-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_card_distributed_to_player_card_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='char',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.charakter'),
        ),
    ]
