# Generated by Django 4.2.8 on 2025-11-17 20:25

import math
from django.db import migrations

def add_initial_transactions_for_chars(apps, schema_editor):
    Card = apps.get_model('cards', 'Card')
    Transaction = apps.get_model('cards', 'Transaction')
    
    Transaction.objects.bulk_create([
        Transaction(receiver=card if card.money >= 0 else None, sender=card if card.money < 0 else None, amount=math.fabs(card.money), reason="Übertrag vom alten Kontostand")
        for card in Card.objects.exclude(char=None)
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_transaction_receiver_alter_transaction_sender_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_transactions_for_chars)
    ]
